<?php
/**
 * Seed real properties into the properties table
 * Based on actual market data from Gorakhpur, Lucknow, Kushinagar, Prayagraj
 */

$pdo = new PDO('mysql:host=127.0.0.1;port=3307;dbname=apsdreamhome', 'root', '');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// Check how many active properties exist
$count = $pdo->query("SELECT COUNT(*) FROM properties WHERE status='active' AND deleted_at IS NULL")->fetchColumn();
echo "Current active properties: {$count}\n";

if ($count >= 30) {
    echo "Already have enough properties. Skipping seed.\n";
    exit;
}

$properties = [
    // ===== GORAKHPUR - APS Dream Home Colonies =====
    [
        'title' => 'Premium Residential Plot in Suryoday Colony',
        'description' => 'Well-planned residential plot in Suryoday Colony, one of Gorakhpur\'s most sought-after gated communities. RERA registered with clear titles. Near Gorakhpur University, railways station, and AIIMS.',
        'price' => 650000,
        'location' => 'Suryoday Colony, Kunraghat, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1200,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Gated Community', '24x7 Security', 'Paved Roads', 'Water Supply', 'Electricity', 'Park']),
        'amenities' => json_encode(['Park', 'Temple', 'School Nearby', 'Hospital 2km']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => 'Residential Plot in Raghunath Nagri Phase 2',
        'description' => 'Spacious plot in Raghunath Nagri, a well-developed colony with excellent infrastructure. Near Deoria Road with easy access to highways. GDA approved layouts.',
        'price' => 550000,
        'location' => 'Raghunath Nagri, Deoria Road, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1000,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Gated Community', 'Paved Roads', 'Drainage System', 'Street Lights']),
        'amenities' => json_encode(['Market Nearby', 'School 1km', 'Bus Stand 2km']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => 'Premium Plot in Braj Radha Nagri',
        'description' => 'Affordable premium plots in Braj Radha Nagri, Gorakhpur. Family-friendly neighborhood with modern amenities. East-facing plots available with Vastu compliance.',
        'price' => 450000,
        'location' => 'Braj Radha Nagri, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1000,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['East Facing', 'Corner Plot Available', 'Wide Roads', 'Boundary Wall']),
        'amenities' => json_encode(['Park', 'Children Play Area', 'Temple', 'Market']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => 'Affordable Plot in Budh Bihar Colony',
        'description' => 'Budget-friendly residential plots in Budh Bihar Colony, Kushinagar. Ideal for first-time buyers and investors. Near NH-28 with excellent connectivity.',
        'price' => 350000,
        'location' => 'Budh Bihar Colony, Kushinagar',
        'city' => 'Kushinagar',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1000,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['NH-28 Access', 'Electricity', 'Water Supply', 'Road Access']),
        'amenities' => json_encode(['School 500m', 'Hospital 3km', 'Market 1km']),
        'status' => 'active',
        'featured' => 1,
    ],

    // ===== GORAKHPUR - Market Properties =====
    [
        'title' => 'Residential Plot in Taramandal',
        'description' => 'Prime residential plot in Taramandal, one of Gorakhpur\'s most premium localities. Near BRD Medical College. Well-connected to all parts of the city.',
        'price' => 1750000,
        'location' => 'Taramandal, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1000,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Prime Location', 'Medical College Nearby', 'Wide Road', 'GDA Approved']),
        'amenities' => json_encode(['Hospital 500m', 'College 1km', 'Market Walking Distance']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Commercial Plot on Deoria Road',
        'description' => 'High-visibility commercial plot on Deoria Road. Excellent for shops, showrooms, or office space. Near Ramgarh Lake and Ring Road junction.',
        'price' => 4500000,
        'location' => 'Deoria Road, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'commercial',
        'area_sqft' => 1500,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Main Road Facing', 'High Footfall', 'Parking Available', 'GDA Approved']),
        'amenities' => json_encode(['Bank 200m', 'Petrol Pump 100m', 'Bus Stop 300m']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Residential Plot in Gorakhnath Area',
        'description' => 'Peaceful residential plot near Gorakhnath Temple. Cultural hub of Gorakhpur with traditional neighborhoods and modern amenities.',
        'price' => 1200000,
        'location' => 'Gorakhnath, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 800,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Temple Nearby', 'Quiet Area', 'Residential Zone', 'School 500m']),
        'amenities' => json_encode(['Temple Walking Distance', 'Market 500m', 'School 500m']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Plot in Padri Bazar',
        'description' => 'Family-friendly plot in Padri Bazar, Gorakhpur. Near schools and hospitals. Well-connected to city center with good public transport.',
        'price' => 900000,
        'location' => 'Padri Bazar, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 900,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['School Nearby', 'Hospital Nearby', 'Public Transport', 'Market Access']),
        'amenities' => json_encode(['School 300m', 'Hospital 1km', 'Auto Stand 200m']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Residential Plot in Medical Road',
        'description' => 'Strategic plot on Medical Road near AIIMS Gorakhpur. Premium location with rapid appreciation potential. Ring Road access.',
        'price' => 2200000,
        'location' => 'Medical Road, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1500,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['AIIMS Nearby', 'Ring Road Access', 'East Facing', 'Pitch Road']),
        'amenities' => json_encode(['Hospital 200m', 'Pharmacy 100m', 'School 1km']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Plot in Rajendra Nagar Colony',
        'description' => 'Premium plot in upscale Rajendra Nagar. One of Gorakhpur\'s most expensive localities with excellent infrastructure and connectivity.',
        'price' => 3500000,
        'location' => 'Rajendra Nagar, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1200,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Upscale Area', 'Wide Roads', 'Gated Community', 'Park Facing']),
        'amenities' => json_encode(['Mall 2km', 'School 500m', 'Restaurant Walking Distance']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Commercial Shop in Mohaddipur Market',
        'description' => 'Ready-to-use commercial shop in Mohaddipur market area. High footfall location ideal for retail business. Near Gorakhpur junction.',
        'price' => 5500000,
        'location' => 'Mohaddipur, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'commercial',
        'area_sqft' => 600,
        'bedrooms' => 0,
        'bathrooms' => 1,
        'features' => json_encode(['Ground Floor', 'Main Market', 'Shutter Door', 'Storage Space']),
        'amenities' => json_encode(['Bank 100m', 'ATM 50m', 'Parking 200m']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => 'Residential Plot in Bargadwa',
        'description' => 'Affordable plot in Bargadwa, a rapidly developing area of Gorakhpur. Good road connectivity and growing infrastructure.',
        'price' => 750000,
        'location' => 'Bargadwa, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1100,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Developing Area', 'Road Access', 'Electricity', 'Water Supply']),
        'amenities' => json_encode(['Market 1km', 'School 2km', 'Bus Stand 1.5km']),
        'status' => 'active',
        'featured' => 0,
    ],

    // ===== LUCKNOW - APS Valley & Market =====
    [
        'title' => 'Residential Plot in APS Valley Lucknow',
        'description' => 'Premium plotted development by APS Dream Homes in Lucknow. Well-planned township with modern amenities and excellent connectivity to Gomti Nagar.',
        'price' => 2500000,
        'location' => 'APS Valley, Lucknow',
        'city' => 'Lucknow',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1500,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['Township', 'Gated Community', 'Park', 'Club House', 'Security']),
        'amenities' => json_encode(['School in Campus', 'Hospital 3km', 'Market in Campus']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => 'Plot in Gomti Nagar Extension',
        'description' => 'Residential plot in Gomti Nagar Extension, Lucknow\'s fastest-growing locality. Near metro and IT hub. LDA approved with clear titles.',
        'price' => 3800000,
        'location' => 'Gomti Nagar Extension, Lucknow',
        'city' => 'Lucknow',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 2152,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['LDA Approved', 'Metro Nearby', 'IT Hub', 'Wide Roads']),
        'amenities' => json_encode(['Metro 2km', 'Mall 3km', 'Hospital 2km']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => '3 BHK Apartment in Gomti Nagar',
        'description' => 'Modern 3 BHK apartment in prime Gomti Nagar, Lucknow. Near Pallasio Mall and Lohia Park. Premium construction with modular kitchen.',
        'price' => 8500000,
        'location' => 'Gomti Nagar, Lucknow',
        'city' => 'Lucknow',
        'state' => 'Uttar Pradesh',
        'type' => 'apartment',
        'area_sqft' => 1650,
        'bedrooms' => 3,
        'bathrooms' => 2,
        'features' => json_encode(['Modular Kitchen', 'Lift', 'Parking', 'Power Backup', 'Club House']),
        'amenities' => json_encode(['Mall Walking Distance', 'Park 500m', 'School 1km', 'Hospital 2km']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => '2 BHK Flat in Hazratganj',
        'description' => 'Well-furnished 2 BHK flat in the heart of Lucknow, Hazratganj. Walking distance to Hazratganj Metro, restaurants, and shopping.',
        'price' => 5500000,
        'location' => 'Hazratganj, Lucknow',
        'city' => 'Lucknow',
        'state' => 'Uttar Pradesh',
        'type' => 'apartment',
        'area_sqft' => 1100,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'features' => json_encode(['Furnished', 'Metro Nearby', 'AC', 'Modular Kitchen']),
        'amenities' => json_encode(['Metro 200m', 'Market Walking Distance', 'Restaurant 100m']),
        'status' => 'active',
        'featured' => 0,
    ],

    // ===== PRAYAGRAJ - APS Heights =====
    [
        'title' => '2 BHK Flat in APS Heights Naini',
        'description' => 'Affordable 2 BHK flat in APS Heights, Naini, Prayagraj. By APS Dream Homes with modern amenities. Near Yamuna Expressway.',
        'price' => 3500000,
        'location' => 'APS Heights, Naini, Prayagraj',
        'city' => 'Prayagraj',
        'state' => 'Uttar Pradesh',
        'type' => 'apartment',
        'area_sqft' => 1050,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'features' => json_encode(['Gated Community', 'Lift', 'Parking', 'Water Supply', 'Electricity']),
        'amenities' => json_encode(['School 1km', 'Hospital 2km', 'Market 500m', 'Expressway 5km']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => '3 BHK Flat in APS Heights Naini',
        'description' => 'Spacious 3 BHK flat in APS Heights, Naini, Prayagraj. Premium construction with balcony and modular kitchen. Ideal for families.',
        'price' => 4800000,
        'location' => 'APS Heights, Naini, Prayagraj',
        'city' => 'Prayagraj',
        'state' => 'Uttar Pradesh',
        'type' => 'apartment',
        'area_sqft' => 1450,
        'bedrooms' => 3,
        'bathrooms' => 2,
        'features' => json_encode(['Balcony', 'Modular Kitchen', 'Lift', 'Parking', 'Power Backup']),
        'amenities' => json_encode(['School 1km', 'Hospital 2km', 'Temple Walking Distance']),
        'status' => 'active',
        'featured' => 0,
    ],

    // ===== VARANASI =====
    [
        'title' => 'Residential Plot in Ganga Nagar Varanasi',
        'description' => 'Peaceful residential plot near Ganga river in Varanasi. Spiritual city with growing infrastructure and tourism potential.',
        'price' => 2800000,
        'location' => 'Ganga Nagar, Varanasi',
        'city' => 'Varanasi',
        'state' => 'Uttar Pradesh',
        'type' => 'land',
        'area_sqft' => 1200,
        'bedrooms' => 0,
        'bathrooms' => 0,
        'features' => json_encode(['River Proximity', 'Spiritual Area', 'Road Access', 'Electricity']),
        'amenities' => json_encode(['Ghat 1km', 'Temple 500m', 'Market 1km']),
        'status' => 'active',
        'featured' => 0,
    ],

    // ===== HOUSES =====
    [
        'title' => 'Independent House in Khorabar Gorakhpur',
        'description' => 'Beautiful 3 BHK independent house in Khorabar, Gorakhpur. Ready to move with all modern amenities. Near Gorakhpur University.',
        'price' => 6500000,
        'location' => 'Khorabar, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'house',
        'area_sqft' => 1800,
        'bedrooms' => 3,
        'bathrooms' => 3,
        'features' => json_encode(['Ready to Move', 'Parking for 2 Cars', 'Modular Kitchen', 'Garden', 'Servant Quarter']),
        'amenities' => json_encode(['University 1km', 'Hospital 2km', 'Market 500m']),
        'status' => 'active',
        'featured' => 1,
    ],
    [
        'title' => '2 BHK House in Kunraghat Gorakhpur',
        'description' => 'Compact 2 BHK house in Kunraghat area. Near APS Dream Home office. Affordable for small families.',
        'price' => 3800000,
        'location' => 'Kunraghat, Gorakhpur',
        'city' => 'Gorakhpur',
        'state' => 'Uttar Pradesh',
        'type' => 'house',
        'area_sqft' => 1100,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'features' => json_encode(['Ready to Move', 'Covered Parking', 'Balcony', 'Water Tank']),
        'amenities' => json_encode(['Temple 200m', 'Market 500m', 'School 1km']),
        'status' => 'active',
        'featured' => 0,
    ],
    [
        'title' => '4 BHK Villa in Sahara Estate Lucknow',
        'description' => 'Luxurious 4 BHK villa in Sahara Estate, Lucknow. Premium gated community with clubhouse and swimming pool.',
        'price' => 25000000,
        'location' => 'Sahara Estate, Lucknow',
        'city' => 'Lucknow',
        'state' => 'Uttar Pradesh',
        'type' => 'house',
        'area_sqft' => 3500,
        'bedrooms' => 4,
        'bathrooms' => 4,
        'features' => json_encode(['Swimming Pool', 'Club House', 'Garden', 'Servant Quarter', 'Modular Kitchen', 'Home Theatre']),
        'amenities' => json_encode(['Golf Course 5km', 'Hospital 3km', 'Mall 4km', 'School 2km']),
        'status' => 'active',
        'featured' => 1,
    ],
];

$inserted = 0;
$stmt = $pdo->prepare("
    INSERT INTO properties (title, description, price, location, city, state, type, area_sqft, bedrooms, bathrooms, features, amenities, status, featured, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
");

foreach ($properties as $p) {
    try {
        $stmt->execute([
            $p['title'], $p['description'], $p['price'], $p['location'],
            $p['city'], $p['state'], $p['type'], $p['area_sqft'],
            $p['bedrooms'], $p['bathrooms'], $p['features'], $p['amenities'],
            $p['status'], $p['featured']
        ]);
        $inserted++;
        echo "  ✓ {$p['title']}\n";
    } catch (PDOException $e) {
        echo "  ✗ {$p['title']}: {$e->getMessage()}\n";
    }
}

echo "\nSeeded {$inserted} real properties.\n";
$total = $pdo->query("SELECT COUNT(*) FROM properties WHERE status='active' AND deleted_at IS NULL")->fetchColumn();
echo "Total active properties now: {$total}\n";
