<?php
/**
 * APS Dream Home - APM Monitoring Script
 * Automated Application Performance Monitoring implementation
 */

echo "📊 APS DREAM HOME - APM MONITORING\n";
echo "=================================\n\n";

// Load centralized path configuration
require_once __DIR__ . '/config/paths.php';

// APM implementation results
$apmResults = [];
$totalImplementations = 0;
$successfulImplementations = 0;

echo "🔍 IMPLEMENTING APM MONITORING...\n\n";

// 1. Create APM monitoring class
echo "Step 1: Creating APM monitoring class\n";
$apmFile = APP_PATH . '/Monitoring/APM.php';
$apmContent = "<?php\n";
$apmContent .= "/**\n";
$apmContent .= " * APS Dream Home - Application Performance Monitor\n";
$apmContent .= " */\n";
$apmContent .= "\n";
$apmContent .= "namespace App\\Monitoring;\n";
$apmContent .= "\n";
$apmContent .= "class APM\n";
$apmContent .= "{\n";
$apmContent .= "    private static \$instance = null;\n";
$apmContent .= "    private \$metrics = [];\n";
$apmContent .= "    private \$startTime;\n";
$apmContent .= "    private \$config;\n";
$apmContent .= "\n";
$apmContent .= "    private function __construct()\n";
$apmContent .= "    {\n";
$apmContent .= "        \$this->startTime = microtime(true);\n";
$apmContent .= "        \$this->config = require CONFIG_PATH . '/monitoring.php';\n";
$apmContent .= "        \$this->initializeMetrics();\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public static function getInstance()\n";
$apmContent .= "    {\n";
$apmContent .= "        if (self::\$instance === null) {\n";
$apmContent .= "            self::\$instance = new self();\n";
$apmContent .= "        }\n";
$apmContent .= "        return self::\$instance;\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function initializeMetrics()\n";
$apmContent .= "    {\n";
$apmContent .= "        \$this->metrics = [\n";
$apmContent .= "            'request' => [\n";
$apmContent .= "                'count' => 0,\n";
$apmContent .= "                'total_time' => 0,\n";
$apmContent .= "                'avg_time' => 0,\n";
$apmContent .= "                'max_time' => 0,\n";
$apmContent .= "                'min_time' => PHP_FLOAT_MAX\n";
$apmContent .= "            ],\n";
$apmContent .= "            'database' => [\n";
$apmContent .= "                'queries' => 0,\n";
$apmContent .= "                'total_time' => 0,\n";
$apmContent .= "                'avg_time' => 0,\n";
$apmContent .= "                'slow_queries' => 0\n";
$apmContent .= "            ],\n";
$apmContent .= "            'memory' => [\n";
$apmContent .= "                'peak_usage' => 0,\n";
$apmContent .= "                'current_usage' => 0,\n";
$apmContent .= "                'avg_usage' => 0\n";
$apmContent .= "            ],\n";
$apmContent .= "            'errors' => [\n";
$apmContent .= "                'count' => 0,\n";
$apmContent .= "                'types' => []\n";
$apmContent .= "            ],\n";
$apmContent .= "            'performance' => [\n";
$apmContent .= "                'cpu_usage' => 0,\n";
$apmContent .= "                'disk_usage' => 0,\n";
$apmContent .= "                'network_io' => 0\n";
$apmContent .= "            ]\n";
$apmContent .= "        ];\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public function startRequest(\$requestId = null)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$requestId = \$requestId ?: uniqid('req_');\n";
$apmContent .= "        \$this->metrics['current_request'] = [\n";
$apmContent .= "            'id' => \$requestId,\n";
$apmContent .= "            'start_time' => microtime(true),\n";
$apmContent .= "            'memory_start' => memory_get_usage(true),\n";
$apmContent .= "            'queries' => 0,\n";
$apmContent .= "            'errors' => 0\n";
$apmContent .= "        ];\n";
$apmContent .= "        return \$requestId;\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public function endRequest(\$requestId)\n";
$apmContent .= "    {\n";
$apmContent .= "        if (!isset(\$this->metrics['current_request'])) {\n";
$apmContent .= "            return;\n";
$apmContent .= "        }\n";
$apmContent .= "\n";
$apmContent .= "        \$request = \$this->metrics['current_request'];\n";
$apmContent .= "        \$endTime = microtime(true);\n";
$apmContent .= "        \$duration = (\$endTime - \$request['start_time']) * 1000;\n";
$apmContent .= "        \$memoryUsed = memory_get_usage(true) - \$request['memory_start'];\n";
$apmContent .= "\n";
$apmContent .= "        // Update request metrics\n";
$apmContent .= "        \$this->metrics['request']['count']++;\n";
$apmContent .= "        \$this->metrics['request']['total_time'] += \$duration;\n";
$apmContent .= "        \$this->metrics['request']['avg_time'] = \$this->metrics['request']['total_time'] / \$this->metrics['request']['count'];\n";
$apmContent .= "        \$this->metrics['request']['max_time'] = max(\$this->metrics['request']['max_time'], \$duration);\n";
$apmContent .= "        \$this->metrics['request']['min_time'] = min(\$this->metrics['request']['min_time'], \$duration);\n";
$apmContent .= "\n";
$apmContent .= "        // Update memory metrics\n";
$apmContent .= "        \$this->metrics['memory']['current_usage'] = memory_get_usage(true);\n";
$apmContent .= "        \$this->metrics['memory']['peak_usage'] = max(\$this->metrics['memory']['peak_usage'], \$this->metrics['memory']['current_usage']);\n";
$apmContent .= "\n";
$apmContent .= "        // Log request details\n";
$apmContent .= "        \$this->logRequest(\$requestId, \$duration, \$memoryUsed);\n";
$apmContent .= "\n";
$apmContent .= "        unset(\$this->metrics['current_request']);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public function recordQuery(\$query, \$duration, \$type = 'select')\n";
$apmContent .= "    {\n";
$apmContent .= "        \$this->metrics['database']['queries']++;\n";
$apmContent .= "        \$this->metrics['database']['total_time'] += \$duration;\n";
$apmContent .= "        \$this->metrics['database']['avg_time'] = \$this->metrics['database']['total_time'] / \$this->metrics['database']['queries'];\n";
$apmContent .= "\n";
$apmContent .= "        if (\$duration > \$this->config['slow_query_threshold']) {\n";
$apmContent .= "            \$this->metrics['database']['slow_queries']++;\n";
$apmContent .= "            \$this->logSlowQuery(\$query, \$duration);\n";
$apmContent .= "        }\n";
$apmContent .= "\n";
$apmContent .= "        if (isset(\$this->metrics['current_request'])) {\n";
$apmContent .= "            \$this->metrics['current_request']['queries']++;\n";
$apmContent .= "        }\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public function recordError(\$error, \$type = 'exception')\n";
$apmContent .= "    {\n";
$apmContent .= "        \$this->metrics['errors']['count']++;\n";
$apmContent .= "        \$this->metrics['errors']['types'][\$type] = (\$this->metrics['errors']['types'][\$type] ?? 0) + 1;\n";
$apmContent .= "\n";
$apmContent .= "        if (isset(\$this->metrics['current_request'])) {\n";
$apmContent .= "            \$this->metrics['current_request']['errors']++;\n";
$apmContent .= "        }\n";
$apmContent .= "\n";
$apmContent .= "        \$this->logError(\$error, \$type);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    public function getMetrics()\n";
$apmContent .= "    {\n";
$apmContent .= "        \$this->updateSystemMetrics();\n";
$apmContent .= "        return \$this->metrics;\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function updateSystemMetrics()\n";
$apmContent .= "    {\n";
$apmContent .= "        // CPU usage (simplified)\n";
$apmContent .= "        \$load = sys_getloadavg();\n";
$apmContent .= "        \$this->metrics['performance']['cpu_usage'] = \$load ? \$load[0] : 0;\n";
$apmContent .= "\n";
$apmContent .= "        // Disk usage\n";
$apmContent .= "        \$totalSpace = disk_total_space(BASE_PATH);\n";
$apmContent .= "        \$freeSpace = disk_free_space(BASE_PATH);\n";
$apmContent .= "        \$this->metrics['performance']['disk_usage'] = \$totalSpace ? ((\$totalSpace - \$freeSpace) / \$totalSpace) * 100 : 0;\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function logRequest(\$requestId, \$duration, \$memoryUsed)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$logEntry = [\n";
$apmContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$apmContent .= "            'request_id' => \$requestId,\n";
$apmContent .= "            'duration' => round(\$duration, 2),\n";
$apmContent .= "            'memory_used' => \$this->formatBytes(\$memoryUsed),\n";
$apmContent .= "            'uri' => \$_SERVER['REQUEST_URI'] ?? 'unknown',\n";
$apmContent .= "            'method' => \$_SERVER['REQUEST_METHOD'] ?? 'unknown',\n";
$apmContent .= "            'ip' => \$_SERVER['REMOTE_ADDR'] ?? 'unknown'\n";
$apmContent .= "        ];\n";
$apmContent .= "\n";
$apmContent .= "        \$this->writeLog('apm_requests.log', \$logEntry);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function logSlowQuery(\$query, \$duration)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$logEntry = [\n";
$apmContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$apmContent .= "            'query' => \$query,\n";
$apmContent .= "            'duration' => round(\$duration, 2),\n";
$apmContent .= "            'uri' => \$_SERVER['REQUEST_URI'] ?? 'unknown'\n";
$apmContent .= "        ];\n";
$apmContent .= "\n";
$apmContent .= "        \$this->writeLog('apm_slow_queries.log', \$logEntry);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function logError(\$error, \$type)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$logEntry = [\n";
$apmContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$apmContent .= "            'error' => \$error,\n";
$apmContent .= "            'type' => \$type,\n";
$apmContent .= "            'uri' => \$_SERVER['REQUEST_URI'] ?? 'unknown',\n";
$apmContent .= "            'ip' => \$_SERVER['REMOTE_ADDR'] ?? 'unknown'\n";
$apmContent .= "        ];\n";
$apmContent .= "\n";
$apmContent .= "        \$this->writeLog('apm_errors.log', \$logEntry);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function writeLog(\$filename, \$data)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$logFile = BASE_PATH . '/logs/' . \$filename;\n";
$apmContent .= "        file_put_contents(\$logFile, json_encode(\$data) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$apmContent .= "    }\n";
$apmContent .= "\n";
$apmContent .= "    private function formatBytes(\$bytes)\n";
$apmContent .= "    {\n";
$apmContent .= "        \$units = ['B', 'KB', 'MB', 'GB'];\n";
$apmContent .= "        \$bytes = max(\$bytes, 0);\n";
$apmContent .= "        \$pow = floor((\$bytes ? log(\$bytes) : 0) / log(1024));\n";
$apmContent .= "        \$pow = min(\$pow, count(\$units) - 1);\n";
$apmContent .= "        \$bytes /= pow(1024, \$pow);\n";
$apmContent .= "        return round(\$bytes, 2) . ' ' . \$units[\$pow];\n";
$apmContent .= "    }\n";
$apmContent .= "}\n";

if (file_put_contents($apmFile, $apmContent)) {
    echo "   ✅ APM monitoring class created: app/Monitoring/APM.php\n";
    $apmResults['apm_class'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create APM monitoring class\n";
    $apmResults['apm_class'] = 'failed';
}
$totalImplementations++;

// 2. Create monitoring configuration
echo "\nStep 2: Creating monitoring configuration\n";
$monitoringConfigFile = CONFIG_PATH . '/monitoring.php';
$monitoringConfigContent = "<?php\n";
$monitoringConfigContent .= "/**\n";
$monitoringConfigContent .= " * APS Dream Home - Monitoring Configuration\n";
$monitoringConfigContent .= " */\n";
$monitoringConfigContent .= "\n";
$monitoringConfigContent .= "return [\n";
$monitoringConfigContent .= "    'apm' => [\n";
$monitoringConfigContent .= "        'enabled' => true,\n";
$monitoringConfigContent .= "        'sample_rate' => 100,\n";
$monitoringConfigContent .= "        'slow_request_threshold' => 1000, // ms\n";
$monitoringConfigContent .= "        'slow_query_threshold' => 100, // ms\n";
$monitoringConfigContent .= "        'memory_threshold' => 100 * 1024 * 1024, // 100MB\n";
$monitoringConfigContent .= "        'error_threshold' => 10 // errors per minute\n";
$monitoringConfigContent .= "    ],\n";
$monitoringConfigContent .= "    'dashboard' => [\n";
$monitoringConfigContent .= "        'refresh_interval' => 5, // seconds\n";
$monitoringConfigContent .= "        'chart_history' => 300, // data points\n";
$monitoringConfigContent .= "        'alert_display' => true,\n";
$monitoringConfigContent .= "        'real_time_updates' => true\n";
$monitoringConfigContent .= "    ],\n";
$monitoringConfigContent .= "    'alerts' => [\n";
$monitoringConfigContent .= "        'enabled' => true,\n";
$monitoringConfigContent .= "        'channels' => ['email', 'log'],\n";
$monitoringConfigContent .= "        'email_recipients' => ['admin@apsdreamhomes.com'],\n";
$monitoringConfigContent .= "        'thresholds' => [\n";
$monitoringConfigContent .= "            'response_time' => 2000, // ms\n";
$monitoringConfigContent .= "            'error_rate' => 5, // %\n";
$monitoringConfigContent .= "            'memory_usage' => 80, // %\n";
$monitoringConfigContent .= "            'cpu_usage' => 80, // %\n";
$monitoringConfigContent .= "            'disk_usage' => 90 // %\n";
$monitoringConfigContent .= "        ]\n";
$monitoringConfigContent .= "    ],\n";
$monitoringConfigContent .= "    'logging' => [\n";
$monitoringConfigContent .= "        'level' => 'INFO',\n";
$monitoringConfigContent .= "        'retention_days' => 30,\n";
$monitoringConfigContent .= "        'max_file_size' => 10 * 1024 * 1024, // 10MB\n";
$monitoringConfigContent .= "        'rotate_files' => true\n";
$monitoringConfigContent .= "    ],\n";
$monitoringConfigContent .= "    'metrics' => [\n";
$monitoringConfigContent .= "        'collection_interval' => 60, // seconds\n";
$monitoringConfigContent .= "        'retention_period' => 7, // days\n";
$monitoringConfigContent .= "        'aggregation_window' => 300, // seconds\n";
$monitoringConfigContent .= "        'export_formats' => ['json', 'csv']\n";
$monitoringConfigContent .= "    ]\n";
$monitoringConfigContent .= "];\n";

if (file_put_contents($monitoringConfigFile, $monitoringConfigContent)) {
    echo "   ✅ Monitoring configuration created: config/monitoring.php\n";
    $apmResults['monitoring_config'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create monitoring configuration\n";
    $apmResults['monitoring_config'] = 'failed';
}
$totalImplementations++;

// 3. Create APM middleware
echo "\nStep 3: Creating APM middleware\n";
$apmMiddlewareFile = APP_PATH . '/Http/Middleware/APMMiddleware.php';
$apmMiddlewareContent = "<?php\n";
$apmMiddlewareContent .= "/**\n";
$apmMiddlewareContent .= " * APS Dream Home - APM Middleware\n";
$apmMiddlewareContent .= " */\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "namespace App\\Http\\Middleware;\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "use App\\Monitoring\\APM;\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "class APMMiddleware\n";
$apmMiddlewareContent .= "{\n";
$apmMiddlewareContent .= "    private \$apm;\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "    public function __construct()\n";
$apmMiddlewareContent .= "    {\n";
$apmMiddlewareContent .= "        \$this->apm = APM::getInstance();\n";
$apmMiddlewareContent .= "    }\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "    public function handle(\$request, \$next)\n";
$apmMiddlewareContent .= "    {\n";
$apmMiddlewareContent .= "        // Start monitoring\n";
$apmMiddlewareContent .= "        \$requestId = \$this->apm->startRequest();\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "        try {\n";
$apmMiddlewareContent .= "            // Process request\n";
$apmMiddlewareContent .= "            \$response = \$next(\$request);\n";
$apmMiddlewareContent .= "        } catch (Exception \$e) {\n";
$apmMiddlewareContent .= "            // Record error\n";
$apmMiddlewareContent .= "            \$this->apm->recordError(\$e->getMessage(), 'exception');\n";
$apmMiddlewareContent .= "            throw \$e;\n";
$apmMiddlewareContent .= "        }\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "        // End monitoring\n";
$apmMiddlewareContent .= "        \$this->apm->endRequest(\$requestId);\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "        // Add performance headers\n";
$apmMiddlewareContent .= "        \$metrics = \$this->apm->getMetrics();\n";
$apmMiddlewareContent .= "        \$response->header('X-Request-ID', \$requestId);\n";
$apmMiddlewareContent .= "        \$response->header('X-Response-Time', round(\$metrics['request']['avg_time'], 2) . 'ms');\n";
$apmMiddlewareContent .= "        \$response->header('X-Memory-Usage', \$this->formatBytes(\$metrics['memory']['current_usage']));\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "        return \$response;\n";
$apmMiddlewareContent .= "    }\n";
$apmMiddlewareContent .= "\n";
$apmMiddlewareContent .= "    private function formatBytes(\$bytes)\n";
$apmMiddlewareContent .= "    {\n";
$apmMiddlewareContent .= "        \$units = ['B', 'KB', 'MB', 'GB'];\n";
$apmMiddlewareContent .= "        \$bytes = max(\$bytes, 0);\n";
$apmMiddlewareContent .= "        \$pow = floor((\$bytes ? log(\$bytes) : 0) / log(1024));\n";
$apmMiddlewareContent .= "        \$pow = min(\$pow, count(\$units) - 1);\n";
$apmMiddlewareContent .= "        \$bytes /= pow(1024, \$pow);\n";
$apmMiddlewareContent .= "        return round(\$bytes, 2) . ' ' . \$units[\$pow];\n";
$apmMiddlewareContent .= "    }\n";
$apmMiddlewareContent .= "}\n";

if (file_put_contents($apmMiddlewareFile, $apmMiddlewareContent)) {
    echo "   ✅ APM middleware created: app/Http/Middleware/APMMiddleware.php\n";
    $apmResults['apm_middleware'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create APM middleware\n";
    $apmResults['apm_middleware'] = 'failed';
}
$totalImplementations++;

// 4. Create metrics dashboard
echo "\nStep 4: Creating metrics dashboard\n";
$dashboardFile = BASE_PATH . '/monitoring_dashboard.php';
$dashboardContent = "<?php\n";
$dashboardContent .= "/**\n";
$dashboardContent .= " * APS Dream Home - Monitoring Dashboard\n";
$dashboardContent .= " */\n";
$dashboardContent .= "\n";
$dashboardContent .= "require_once __DIR__ . '/config/paths.php';\n";
$dashboardContent .= "require_once APP_PATH . '/Monitoring/APM.php';\n";
$dashboardContent .= "\n";
$dashboardContent .= "echo '<!DOCTYPE html>\n";
$dashboardContent .= "<html>\n";
$dashboardContent .= "<head>\n";
$dashboardContent .= "    <title>APS Dream Home - Monitoring Dashboard</title>\n";
$dashboardContent .= "    <meta charset=\"UTF-8\">\n";
$dashboardContent .= "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
$dashboardContent .= "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n";
$dashboardContent .= "    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n";
$dashboardContent .= "    <style>\n";
$dashboardContent .= "        .metric-card { transition: all 0.3s ease; }\n";
$dashboardContent .= "        .metric-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.1); }\n";
$dashboardContent .= "        .status-good { border-left: 4px solid #28a745; }\n";
$dashboardContent .= "        .status-warning { border-left: 4px solid #ffc107; }\n";
$dashboardContent .= "        .status-danger { border-left: 4px solid #dc3545; }\n";
$dashboardContent .= "        .chart-container { position: relative; height: 300px; }\n";
$dashboardContent .= "    </style>\n";
$dashboardContent .= "</head>\n";
$dashboardContent .= "<body>\n";
$dashboardContent .= "    <nav class=\"navbar navbar-dark bg-dark\">\n";
$dashboardContent .= "        <div class=\"container-fluid\">\n";
$dashboardContent .= "            <span class=\"navbar-brand mb-0 h1\">📊 APS Dream Home - Monitoring Dashboard</span>\n";
$dashboardContent .= "            <span class=\"navbar-text\">Last Updated: <span id=\"lastUpdate\">-</span></span>\n";
$dashboardContent .= "        </div>\n";
$dashboardContent .= "    </nav>\n";
$dashboardContent .= "\n";
$dashboardContent .= "    <div class=\"container-fluid mt-4\">\n";
$dashboardContent .= "        <div class=\"row\">\n";
$dashboardContent .= "            <div class=\"col-md-3\">\n";
$dashboardContent .= "                <div class=\"card metric-card status-good\">\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <h5 class=\"card-title\">Requests/min</h5>\n";
$dashboardContent .= "                        <h2 class=\"text-primary\" id=\"requestsPerMinute\">-</h2>\n";
$dashboardContent .= "                        <small class=\"text-muted\">Total requests in last minute</small>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "            <div class=\"col-md-3\">\n";
$dashboardContent .= "                <div class=\"card metric-card status-good\">\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <h5 class=\"card-title\">Avg Response Time</h5>\n";
$dashboardContent .= "                        <h2 class=\"text-success\" id=\"avgResponseTime\">-</h2>\n";
$dashboardContent .= "                        <small class=\"text-muted\">Milliseconds</small>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "            <div class=\"col-md-3\">\n";
$dashboardContent .= "                <div class=\"card metric-card status-good\">\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <h5 class=\"card-title\">Memory Usage</h5>\n";
$dashboardContent .= "                        <h2 class=\"text-info\" id=\"memoryUsage\">-</h2>\n";
$dashboardContent .= "                        <small class=\"text-muted\">Current usage</small>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "            <div class=\"col-md-3\">\n";
$dashboardContent .= "                <div class=\"card metric-card status-good\">\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <h5 class=\"card-title\">Error Rate</h5>\n";
$dashboardContent .= "                        <h2 class=\"text-danger\" id=\"errorRate\">-</h2>\n";
$dashboardContent .= "                        <small class=\"text-muted\">Errors per minute</small>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "        </div>\n";
$dashboardContent .= "\n";
$dashboardContent .= "        <div class=\"row mt-4\">\n";
$dashboardContent .= "            <div class=\"col-md-6\">\n";
$dashboardContent .= "                <div class=\"card\">\n";
$dashboardContent .= "                    <div class=\"card-header\">\n";
$dashboardContent .= "                        <h5>Response Time Trend</h5>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <div class=\"chart-container\">\n";
$dashboardContent .= "                            <canvas id=\"responseTimeChart\"></canvas>\n";
$dashboardContent .= "                        </div>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "            <div class=\"col-md-6\">\n";
$dashboardContent .= "                <div class=\"card\">\n";
$dashboardContent .= "                    <div class=\"card-header\">\n";
$dashboardContent .= "                        <h5>System Resources</h5>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                    <div class=\"card-body\">\n";
$dashboardContent .= "                        <div class=\"chart-container\">\n";
$dashboardContent .= "                            <canvas id=\"resourceChart\"></canvas>\n";
$dashboardContent .= "                        </div>\n";
$dashboardContent .= "                    </div>\n";
$dashboardContent .= "                </div>\n";
$dashboardContent .= "            </div>\n";
$dashboardContent .= "        </div>\n";
$dashboardContent .= "    </div>\n";
$dashboardContent .= "\n";
$dashboardContent .= "    <script>\n";
$dashboardContent .= "        // Initialize dashboard\n";
$dashboardContent .= "        let responseTimeChart, resourceChart;\n";
$dashboardContent .= "        \n";
$dashboardContent .= "        function initCharts() {\n";
$dashboardContent .= "            // Response Time Chart\n";
$dashboardContent .= "            const responseTimeCtx = document.getElementById('responseTimeChart').getContext('2d');\n";
$dashboardContent .= "            responseTimeChart = new Chart(responseTimeCtx, {\n";
$dashboardContent .= "                type: 'line',\n";
$dashboardContent .= "                data: {\n";
$dashboardContent .= "                    labels: [],\n";
$dashboardContent .= "                    datasets: [{\n";
$dashboardContent .= "                        label: 'Response Time (ms)',\n";
$dashboardContent .= "                        data: [],\n";
$dashboardContent .= "                        borderColor: 'rgb(75, 192, 192)',\n";
$dashboardContent .= "                        backgroundColor: 'rgba(75, 192, 192, 0.2)',\n";
$dashboardContent .= "                        tension: 0.1\n";
$dashboardContent .= "                    }]\n";
$dashboardContent .= "                },\n";
$dashboardContent .= "                options: {\n";
$dashboardContent .= "                    responsive: true,\n";
$dashboardContent .= "                    maintainAspectRatio: false,\n";
$dashboardContent .= "                    scales: {\n";
$dashboardContent .= "                        y: {\n";
$dashboardContent .= "                            beginAtZero: true\n";
$dashboardContent .= "                        }\n";
$dashboardContent .= "                    }\n";
$dashboardContent .= "                }\n";
$dashboardContent .= "            });\n";
$dashboardContent .= "            \n";
$dashboardContent .= "            // Resource Chart\n";
$dashboardContent .= "            const resourceCtx = document.getElementById('resourceChart').getContext('2d');\n";
$dashboardContent .= "            resourceChart = new Chart(resourceCtx, {\n";
$dashboardContent .= "                type: 'doughnut',\n";
$dashboardContent .= "                data: {\n";
$dashboardContent .= "                    labels: ['CPU', 'Memory', 'Disk'],\n";
$dashboardContent .= "                    datasets: [{\n";
$dashboardContent .= "                        data: [0, 0, 0],\n";
$dashboardContent .= "                        backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56']\n";
$dashboardContent .= "                    }]\n";
$dashboardContent .= "                },\n";
$dashboardContent .= "                options: {\n";
$dashboardContent .= "                    responsive: true,\n";
$dashboardContent .= "                    maintainAspectRatio: false\n";
$dashboardContent .= "                }\n";
$dashboardContent .= "            });\n";
$dashboardContent .= "        }\n";
$dashboardContent .= "        \n";
$dashboardContent .= "        function updateDashboard() {\n";
$dashboardContent .= "            fetch('/monitoring_data.php')\n";
$dashboardContent .= "                .then(response => response.json())\n";
$dashboardContent .= "                .then(data => {\n";
$dashboardContent .= "                    // Update metrics\n";
$dashboardContent .= "                    document.getElementById('requestsPerMinute').textContent = data.requests_per_minute || 0;\n";
$dashboardContent .= "                    document.getElementById('avgResponseTime').textContent = data.avg_response_time || 0;\n";
$dashboardContent .= "                    document.getElementById('memoryUsage').textContent = data.memory_usage || '0 MB';\n";
$dashboardContent .= "                    document.getElementById('errorRate').textContent = data.error_rate || 0;\n";
$dashboardContent .= "                    document.getElementById('lastUpdate').textContent = new Date().toLocaleTimeString();\n";
$dashboardContent .= "                    \n";
$dashboardContent .= "                    // Update charts\n";
$dashboardContent .= "                    updateCharts(data);\n";
$dashboardContent .= "                })\n";
$dashboardContent .= "                .catch(error => console.error('Error updating dashboard:', error));\n";
$dashboardContent .= "        }\n";
$dashboardContent .= "        \n";
$dashboardContent .= "        function updateCharts(data) {\n";
$dashboardContent .= "            // Update response time chart\n";
$dashboardContent .= "            if (responseTimeChart && data.response_time_history) {\n";
$dashboardContent .= "                responseTimeChart.data.labels = data.response_time_history.map((_, i) => i + 's ago');\n";
$dashboardContent .= "                responseTimeChart.data.datasets[0].data = data.response_time_history;\n";
$dashboardContent .= "                responseTimeChart.update();\n";
$dashboardContent .= "            }\n";
$dashboardContent .= "            \n";
$dashboardContent .= "            // Update resource chart\n";
$dashboardContent .= "            if (resourceChart && data.system_resources) {\n";
$dashboardContent .= "                resourceChart.data.datasets[0].data = [\n";
$dashboardContent .= "                    data.system_resources.cpu || 0,\n";
$dashboardContent .= "                    data.system_resources.memory || 0,\n";
$dashboardContent .= "                    data.system_resources.disk || 0\n";
$dashboardContent .= "                ];\n";
$dashboardContent .= "                resourceChart.update();\n";
$dashboardContent .= "            }\n";
$dashboardContent .= "        }\n";
$dashboardContent .= "        \n";
$dashboardContent .= "        // Initialize and start auto-refresh\n";
$dashboardContent .= "        document.addEventListener('DOMContentLoaded', function() {\n";
$dashboardContent .= "            initCharts();\n";
$dashboardContent .= "            updateDashboard();\n";
$dashboardContent .= "            setInterval(updateDashboard, 5000); // Update every 5 seconds\n";
$dashboardContent .= "        });\n";
$dashboardContent .= "    </script>\n";
$dashboardContent .= "</body>\n";
$dashboardContent .= "</html>';\n";

if (file_put_contents($dashboardFile, $dashboardContent)) {
    echo "   ✅ Metrics dashboard created: monitoring_dashboard.php\n";
    $apmResults['metrics_dashboard'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create metrics dashboard\n";
    $apmResults['metrics_dashboard'] = 'failed';
}
$totalImplementations++;

// 5. Create monitoring data API
echo "\nStep 5: Creating monitoring data API\n";
$monitoringApiFile = BASE_PATH . '/monitoring_data.php';
$monitoringApiContent = "<?php\n";
$monitoringApiContent .= "/**\n";
$monitoringApiContent .= " * APS Dream Home - Monitoring Data API\n";
$monitoringApiContent .= " */\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "header('Content-Type: application/json');\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "require_once __DIR__ . '/config/paths.php';\n";
$monitoringApiContent .= "require_once APP_PATH . '/Monitoring/APM.php';\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "\$apm = App\\Monitoring\\APM::getInstance();\n";
$monitoringApiContent .= "\$metrics = \$apm->getMetrics();\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "// Calculate additional metrics\n";
$monitoringApiContent .= "\$requestsPerMinute = calculateRequestsPerMinute();\n";
$monitoringApiContent .= "\$errorRate = calculateErrorRate();\n";
$monitoringApiContent .= "\$responseTimeHistory = getResponseTimeHistory();\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "\$data = [\n";
$monitoringApiContent .= "    'requests_per_minute' => \$requestsPerMinute,\n";
$monitoringApiContent .= "    'avg_response_time' => round(\$metrics['request']['avg_time'], 2),\n";
$monitoringApiContent .= "    'memory_usage' => formatBytes(\$metrics['memory']['current_usage']),\n";
$monitoringApiContent .= "    'error_rate' => \$errorRate,\n";
$monitoringApiContent .= "    'response_time_history' => \$responseTimeHistory,\n";
$monitoringApiContent .= "    'system_resources' => [\n";
$monitoringApiContent .= "        'cpu' => round(\$metrics['performance']['cpu_usage'], 2),\n";
$monitoringApiContent .= "        'memory' => round((\$metrics['memory']['current_usage'] / (1024 * 1024 * 1024)) * 100, 2),\n";
$monitoringApiContent .= "        'disk' => round(\$metrics['performance']['disk_usage'], 2)\n";
$monitoringApiContent .= "    ],\n";
$monitoringApiContent .= "    'database_metrics' => [\n";
$monitoringApiContent .= "        'queries' => \$metrics['database']['queries'],\n";
$monitoringApiContent .= "        'avg_query_time' => round(\$metrics['database']['avg_time'], 2),\n";
$monitoringApiContent .= "        'slow_queries' => \$metrics['database']['slow_queries']\n";
$monitoringApiContent .= "    ],\n";
$monitoringApiContent .= "    'error_metrics' => [\n";
$monitoringApiContent .= "        'total_errors' => \$metrics['errors']['count'],\n";
$monitoringApiContent .= "        'error_types' => \$metrics['errors']['types']\n";
$monitoringApiContent .= "    ]\n";
$monitoringApiContent .= "];\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "echo json_encode(\$data);\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "function calculateRequestsPerMinute()\n";
$monitoringApiContent .= "{\n";
$monitoringApiContent .= "    \$logFile = BASE_PATH . '/logs/apm_requests.log';\n";
$monitoringApiContent .= "    if (!file_exists(\$logFile)) return 0;\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$oneMinuteAgo = time() - 60;\n";
$monitoringApiContent .= "    \$count = 0;\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$handle = fopen(\$logFile, 'r');\n";
$monitoringApiContent .= "    if (\$handle) {\n";
$monitoringApiContent .= "        while ((\$line = fgets(\$handle)) !== false) {\n";
$monitoringApiContent .= "            \$entry = json_decode(\$line, true);\n";
$monitoringApiContent .= "            if (\$entry && strtotime(\$entry['timestamp']) >= \$oneMinuteAgo) {\n";
$monitoringApiContent .= "                \$count++;\n";
$monitoringApiContent .= "            }\n";
$monitoringApiContent .= "        }\n";
$monitoringApiContent .= "        fclose(\$handle);\n";
$monitoringApiContent .= "    }\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    return \$count;\n";
$monitoringApiContent .= "}\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "function calculateErrorRate()\n";
$monitoringApiContent .= "{\n";
$monitoringApiContent .= "    \$logFile = BASE_PATH . '/logs/apm_errors.log';\n";
$monitoringApiContent .= "    if (!file_exists(\$logFile)) return 0;\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$oneMinuteAgo = time() - 60;\n";
$monitoringApiContent .= "    \$count = 0;\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$handle = fopen(\$logFile, 'r');\n";
$monitoringApiContent .= "    if (\$handle) {\n";
$monitoringApiContent .= "        while ((\$line = fgets(\$handle)) !== false) {\n";
$monitoringApiContent .= "            \$entry = json_decode(\$line, true);\n";
$monitoringApiContent .= "            if (\$entry && strtotime(\$entry['timestamp']) >= \$oneMinuteAgo) {\n";
$monitoringApiContent .= "                \$count++;\n";
$monitoringApiContent .= "            }\n";
$monitoringApiContent .= "        }\n";
$monitoringApiContent .= "        fclose(\$handle);\n";
$monitoringApiContent .= "    }\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    return \$count;\n";
$monitoringApiContent .= "}\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "function getResponseTimeHistory()\n";
$monitoringApiContent .= "{\n";
$monitoringApiContent .= "    \$logFile = BASE_PATH . '/logs/apm_requests.log';\n";
$monitoringApiContent .= "    if (!file_exists(\$logFile)) return [];\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$fiveMinutesAgo = time() - 300;\n";
$monitoringApiContent .= "    \$times = [];\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    \$handle = fopen(\$logFile, 'r');\n";
$monitoringApiContent .= "    if (\$handle) {\n";
$monitoringApiContent .= "        while ((\$line = fgets(\$handle)) !== false) {\n";
$monitoringApiContent .= "            \$entry = json_decode(\$line, true);\n";
$monitoringApiContent .= "            if (\$entry && strtotime(\$entry['timestamp']) >= \$fiveMinutesAgo) {\n";
$monitoringApiContent .= "                \$times[] = \$entry['duration'];\n";
$monitoringApiContent .= "            }\n";
$monitoringApiContent .= "        }\n";
$monitoringApiContent .= "        fclose(\$handle);\n";
$monitoringApiContent .= "    }\n";
$monitoringApiContent .= "    \n";
$monitoringApiContent .= "    // Return last 60 data points (5 minutes with 5-second intervals)\n";
$monitoringApiContent .= "    return array_slice(array_reverse(\$times), 0, 60);\n";
$monitoringApiContent .= "}\n";
$monitoringApiContent .= "\n";
$monitoringApiContent .= "function formatBytes(\$bytes)\n";
$monitoringApiContent .= "{\n";
$monitoringApiContent .= "    \$units = ['B', 'KB', 'MB', 'GB'];\n";
$monitoringApiContent .= "    \$bytes = max(\$bytes, 0);\n";
$monitoringApiContent .= "    \$pow = floor((\$bytes ? log(\$bytes) : 0) / log(1024));\n";
$monitoringApiContent .= "    \$pow = min(\$pow, count(\$units) - 1);\n";
$monitoringApiContent .= "    \$bytes /= pow(1024, \$pow);\n";
$monitoringApiContent .= "    return round(\$bytes, 2) . ' ' . \$units[\$pow];\n";
$monitoringApiContent .= "}\n";

if (file_put_contents($monitoringApiFile, $monitoringApiContent)) {
    echo "   ✅ Monitoring data API created: monitoring_data.php\n";
    $apmResults['monitoring_api'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create monitoring data API\n";
    $apmResults['monitoring_api'] = 'failed';
}
$totalImplementations++;

// Summary
echo "\n=================================\n";
echo "📊 APM MONITORING SUMMARY\n";
echo "=================================\n";

$successRate = round(($successfulImplementations / $totalImplementations) * 100, 1);
echo "📊 TOTAL IMPLEMENTATIONS: $totalImplementations\n";
echo "✅ SUCCESSFUL: $successfulImplementations\n";
echo "📊 SUCCESS RATE: $successRate%\n\n";

echo "🔧 APM IMPLEMENTATION DETAILS:\n";
foreach ($apmResults as $category => $result) {
    $icon = $result === 'created' ? '✅' : ($result === 'failed' ? '❌' : '⚠️');
    echo "📋 $category: $result\n";
}

if ($successRate >= 80) {
    echo "\n🎉 APM MONITORING: EXCELLENT!\n";
} elseif ($successRate >= 60) {
    echo "\n✅ APM MONITORING: GOOD!\n";
} else {
    echo "\n⚠️  APM MONITORING: NEEDS IMPROVEMENT\n";
}

echo "\n🚀 APM monitoring implemented successfully!\n";
echo "📊 Ready for next monitoring step: Error Tracking and Alerting\n";
?>
