<?php

/**
 * APS Dream Home Code Coverage Analysis and Reporting
 * Comprehensive code coverage tools and reporting system
 */

class CodeCoverageAnalyzer
{
    private $coverageData;
    private $projectRoot;
    private $reportsDir;
    private $config;

    public function __construct($projectRoot = null)
    {
        $this->projectRoot = $projectRoot ?: dirname(__DIR__);
        $this->reportsDir = $this->projectRoot . '/tests/coverage';
        $this->config = $this->loadCoverageConfig();

        if (!is_dir($this->reportsDir)) {
            mkdir($this->reportsDir, 0755, true);
        }
    }

    /**
     * Run comprehensive code coverage analysis
     */
    public function runCoverageAnalysis()
    {
        echo "📊 Starting Code Coverage Analysis\n";
        echo "===================================\n\n";

        // Check if PHPUnit is available
        if (!$this->isPHPUnitAvailable()) {
            echo "❌ PHPUnit not found. Please install PHPUnit to run coverage analysis.\n";
            echo "Run: composer require --dev phpunit/phpunit\n";
            return false;
        }

        // Run tests with coverage
        $this->runTestsWithCoverage();

        // Generate coverage reports
        $this->generateCoverageReports();

        // Analyze coverage data
        $this->analyzeCoverageData();

        // Generate recommendations
        $this->generateCoverageRecommendations();

        echo "\n✅ Code coverage analysis completed!\n";
        return true;
    }

    /**
     * Check if PHPUnit is available
     */
    private function isPHPUnitAvailable()
    {
        return file_exists($this->projectRoot . '/vendor/bin/phpunit') ||
               file_exists($this->projectRoot . '/phpunit.phar') ||
               class_exists('PHPUnit\\Framework\\TestCase');
    }

    /**
     * Run tests with coverage collection
     */
    private function runTestsWithCoverage()
    {
        echo "🧪 Running tests with coverage collection...\n";

        $phpunitCommand = $this->getPHPUnitCommand();
        $coverageFile = $this->reportsDir . '/coverage.xml';

        // Run PHPUnit with coverage
        $command = sprintf(
            '%s --configuration phpunit.xml --coverage-xml %s --coverage-html %s --coverage-text --colors=never',
            $phpunitCommand,
            $coverageFile,
            $this->reportsDir . '/html'
        );

        echo "Executing: {$command}\n";

        $output = [];
        $returnCode = 0;
        exec($command, $output, $returnCode);

        echo "Test execution completed with code: {$returnCode}\n";

        // Save raw output
        file_put_contents($this->reportsDir . '/test_output.txt', implode("\n", $output));

        if ($returnCode !== 0) {
            echo "⚠️ Some tests failed, but coverage data may still be available\n";
        }

        echo "✅ Test execution completed\n\n";
    }

    /**
     * Get PHPUnit command
     */
    private function getPHPUnitCommand()
    {
        if (file_exists($this->projectRoot . '/vendor/bin/phpunit')) {
            return 'php ' . $this->projectRoot . '/vendor/bin/phpunit';
        }

        if (file_exists($this->projectRoot . '/phpunit.phar')) {
            return 'php ' . $this->projectRoot . '/phpunit.phar';
        }

        return 'phpunit';
    }

    /**
     * Generate coverage reports
     */
    private function generateCoverageReports()
    {
        echo "📈 Generating coverage reports...\n";

        $coverageFile = $this->reportsDir . '/coverage.xml';

        if (!file_exists($coverageFile)) {
            echo "❌ Coverage XML file not found. Coverage analysis may have failed.\n";
            return;
        }

        // Parse XML coverage data
        $this->parseCoverageXML($coverageFile);

        // Generate summary report
        $this->generateSummaryReport();

        // Generate detailed HTML report (if not already generated by PHPUnit)
        if (!is_dir($this->reportsDir . '/html')) {
            $this->generateCustomHTMLReport();
        }

        // Generate JSON report for API consumption
        $this->generateJSONReport();

        echo "✅ Coverage reports generated\n\n";
    }

    /**
     * Parse PHPUnit coverage XML
     */
    private function parseCoverageXML($xmlFile)
    {
        $xml = simplexml_load_file($xmlFile);

        if (!$xml) {
            echo "❌ Failed to parse coverage XML\n";
            return;
        }

        $this->coverageData = [
            'timestamp' => date('Y-m-d H:i:s'),
            'summary' => [
                'lines_total' => 0,
                'lines_covered' => 0,
                'branches_total' => 0,
                'branches_covered' => 0,
                'paths_total' => 0,
                'paths_covered' => 0,
                'functions_total' => 0,
                'functions_covered' => 0,
                'classes_total' => 0,
                'classes_covered' => 0
            ],
            'files' => []
        ];

        // Parse project metrics
        if (isset($xml->project->metrics)) {
            $metrics = $xml->project->metrics;
            $this->coverageData['summary'] = [
                'lines_total' => (int) $metrics['statements'],
                'lines_covered' => (int) $metrics['coveredstatements'],
                'branches_total' => (int) $metrics['conditionals'],
                'branches_covered' => (int) $metrics['coveredconditionals'],
                'functions_total' => (int) $metrics['methods'],
                'functions_covered' => (int) $metrics['coveredmethods'],
                'classes_total' => (int) $metrics['classes'],
                'classes_covered' => (int) $metrics['coveredclasses']
            ];
        }

        // Parse file-level data
        if (isset($xml->project->file)) {
            foreach ($xml->project->file as $file) {
                $fileName = (string) $file['name'];
                $fileMetrics = $file->metrics;

                $this->coverageData['files'][$fileName] = [
                    'lines_total' => (int) $fileMetrics['statements'],
                    'lines_covered' => (int) $fileMetrics['coveredstatements'],
                    'branches_total' => (int) $fileMetrics['conditionals'],
                    'branches_covered' => (int) $fileMetrics['coveredconditionals'],
                    'functions_total' => (int) $fileMetrics['methods'],
                    'functions_covered' => (int) $fileMetrics['coveredmethods'],
                    'classes_total' => (int) $fileMetrics['classes'],
                    'classes_covered' => (int) $fileMetrics['coveredclasses'],
                    'coverage_percentage' => $this->calculateCoveragePercentage(
                        (int) $fileMetrics['coveredstatements'],
                        (int) $fileMetrics['statements']
                    )
                ];
            }
        }
    }

    /**
     * Analyze coverage data
     */
    private function analyzeCoverageData()
    {
        echo "🔍 Analyzing coverage data...\n";

        if (empty($this->coverageData)) {
            echo "❌ No coverage data available for analysis\n";
            return;
        }

        $analysis = [
            'overall_coverage' => $this->calculateOverallCoverage(),
            'file_coverage_distribution' => $this->analyzeFileCoverage(),
            'uncovered_areas' => $this->identifyUncoveredAreas(),
            'coverage_trends' => $this->analyzeCoverageTrends(),
            'recommendations' => []
        ];

        // Generate analysis insights
        $analysis['insights'] = $this->generateCoverageInsights($analysis);

        $this->coverageData['analysis'] = $analysis;

        echo "✅ Coverage analysis completed\n\n";
    }

    /**
     * Calculate overall coverage percentage
     */
    private function calculateOverallCoverage()
    {
        $summary = $this->coverageData['summary'];

        return [
            'line_coverage' => $this->calculateCoveragePercentage(
                $summary['lines_covered'], $summary['lines_total']
            ),
            'branch_coverage' => $this->calculateCoveragePercentage(
                $summary['branches_covered'], $summary['branches_total']
            ),
            'function_coverage' => $this->calculateCoveragePercentage(
                $summary['functions_covered'], $summary['functions_total']
            ),
            'class_coverage' => $this->calculateCoveragePercentage(
                $summary['classes_covered'], $summary['classes_total']
            )
        ];
    }

    /**
     * Analyze file coverage distribution
     */
    private function analyzeFileCoverage()
    {
        $files = $this->coverageData['files'];
        $distribution = [
            'excellent' => 0, // > 80%
            'good' => 0,      // 60-80%
            'fair' => 0,      // 40-60%
            'poor' => 0,      // 20-40%
            'critical' => 0   // < 20%
        ];

        $fileDetails = [];

        foreach ($files as $fileName => $metrics) {
            $coverage = $metrics['coverage_percentage'];

            if ($coverage >= 80) $distribution['excellent']++;
            elseif ($coverage >= 60) $distribution['good']++;
            elseif ($coverage >= 40) $distribution['fair']++;
            elseif ($coverage >= 20) $distribution['poor']++;
            else $distribution['critical']++;

            $fileDetails[] = [
                'file' => $fileName,
                'coverage' => $coverage,
                'lines_covered' => $metrics['lines_covered'],
                'lines_total' => $metrics['lines_total']
            ];
        }

        // Sort by coverage (lowest first)
        usort($fileDetails, function($a, $b) {
            return $a['coverage'] <=> $b['coverage'];
        });

        return [
            'distribution' => $distribution,
            'file_details' => array_slice($fileDetails, 0, 20), // Top 20 lowest coverage files
            'total_files' => count($files)
        ];
    }

    /**
     * Identify uncovered areas
     */
    private function identifyUncoveredAreas()
    {
        $uncovered = [
            'files_with_zero_coverage' => [],
            'low_coverage_files' => [],
            'uncovered_functions' => [],
            'uncovered_classes' => []
        ];

        foreach ($this->coverageData['files'] as $fileName => $metrics) {
            if ($metrics['coverage_percentage'] == 0) {
                $uncovered['files_with_zero_coverage'][] = $fileName;
            } elseif ($metrics['coverage_percentage'] < 50) {
                $uncovered['low_coverage_files'][] = [
                    'file' => $fileName,
                    'coverage' => $metrics['coverage_percentage']
                ];
            }

            if ($metrics['functions_total'] > $metrics['functions_covered']) {
                $uncovered['uncovered_functions'][] = [
                    'file' => $fileName,
                    'covered' => $metrics['functions_covered'],
                    'total' => $metrics['functions_total']
                ];
            }

            if ($metrics['classes_total'] > $metrics['classes_covered']) {
                $uncovered['uncovered_classes'][] = [
                    'file' => $fileName,
                    'covered' => $metrics['classes_covered'],
                    'total' => $metrics['classes_total']
                ];
            }
        }

        return $uncovered;
    }

    /**
     * Analyze coverage trends (placeholder for historical comparison)
     */
    private function analyzeCoverageTrends()
    {
        // In a real implementation, this would compare with previous runs
        return [
            'trend' => 'stable', // stable, increasing, decreasing
            'change_percentage' => 0,
            'previous_coverage' => null,
            'recommendation' => 'Implement historical trend tracking for better insights'
        ];
    }

    /**
     * Generate coverage insights
     */
    private function generateCoverageInsights($analysis)
    {
        $insights = [];

        $overall = $analysis['overall_coverage']['line_coverage'];

        if ($overall >= 80) {
            $insights[] = "Excellent coverage! Your codebase is well-tested.";
        } elseif ($overall >= 60) {
            $insights[] = "Good coverage, but room for improvement in critical areas.";
        } elseif ($overall >= 40) {
            $insights[] = "Fair coverage. Consider adding more tests for better reliability.";
        } else {
            $insights[] = "Low coverage. Significant testing improvements needed.";
        }

        $zeroCoverage = count($analysis['uncovered_areas']['files_with_zero_coverage']);
        if ($zeroCoverage > 0) {
            $insights[] = "{$zeroCoverage} files have zero test coverage and should be prioritized.";
        }

        $lowCoverage = count($analysis['uncovered_areas']['low_coverage_files']);
        if ($lowCoverage > 5) {
            $insights[] = "Multiple files have low coverage. Focus testing efforts on these areas.";
        }

        return $insights;
    }

    /**
     * Generate coverage recommendations
     */
    private function generateCoverageRecommendations()
    {
        $recommendations = [];

        $overall = $this->calculateOverallCoverage()['line_coverage'];

        if ($overall < 70) {
            $recommendations[] = "Aim for at least 70% line coverage for better code reliability";
            $recommendations[] = "Focus on testing critical business logic first";
        }

        if (!empty($this->coverageData['analysis']['uncovered_areas']['files_with_zero_coverage'])) {
            $recommendations[] = "Write tests for files with zero coverage before release";
        }

        $recommendations[] = "Implement test-driven development (TDD) for new features";
        $recommendations[] = "Set up automated coverage reporting in CI/CD pipeline";
        $recommendations[] = "Regularly review and update test cases as code evolves";
        $recommendations[] = "Consider integration tests for complex workflows";

        $this->coverageData['recommendations'] = $recommendations;
    }

    /**
     * Generate summary report
     */
    private function generateSummaryReport()
    {
        $report = "APS DREAM HOME - CODE COVERAGE REPORT\n";
        $report .= "=====================================\n\n";
        $report .= "Generated: {$this->coverageData['timestamp']}\n\n";

        if (isset($this->coverageData['summary'])) {
            $summary = $this->coverageData['summary'];
            $report .= "OVERALL COVERAGE:\n";
            $report .= sprintf("Lines: %d/%d (%.1f%%)\n",
                $summary['lines_covered'], $summary['lines_total'],
                $this->calculateCoveragePercentage($summary['lines_covered'], $summary['lines_total']));
            $report .= sprintf("Functions: %d/%d (%.1f%%)\n",
                $summary['functions_covered'], $summary['functions_total'],
                $this->calculateCoveragePercentage($summary['functions_covered'], $summary['functions_total']));
            $report .= sprintf("Classes: %d/%d (%.1f%%)\n",
                $summary['classes_covered'], $summary['classes_total'],
                $this->calculateCoveragePercentage($summary['classes_covered'], $summary['classes_total']));
            $report .= "\n";
        }

        if (isset($this->coverageData['analysis'])) {
            $analysis = $this->coverageData['analysis'];

            $report .= "COVERAGE ANALYSIS:\n";
            $report .= "Files with zero coverage: " . count($analysis['uncovered_areas']['files_with_zero_coverage']) . "\n";
            $report .= "Files with low coverage (<50%): " . count($analysis['uncovered_areas']['low_coverage_files']) . "\n";
            $report .= "\n";

            if (!empty($analysis['insights'])) {
                $report .= "INSIGHTS:\n";
                foreach ($analysis['insights'] as $insight) {
                    $report .= "• {$insight}\n";
                }
                $report .= "\n";
            }
        }

        if (isset($this->coverageData['recommendations'])) {
            $report .= "RECOMMENDATIONS:\n";
            foreach ($this->coverageData['recommendations'] as $rec) {
                $report .= "• {$rec}\n";
            }
        }

        file_put_contents($this->reportsDir . '/coverage_summary.txt', $report);
    }

    /**
     * Generate custom HTML report
     */
    private function generateCustomHTMLReport()
    {
        $html = $this->getHTMLReportTemplate();

        // Replace placeholders with actual data
        $html = str_replace('{{TIMESTAMP}}', $this->coverageData['timestamp'], $html);
        $html = str_replace('{{OVERALL_COVERAGE}}', json_encode($this->calculateOverallCoverage()), $html);
        $html = str_replace('{{COVERAGE_DATA}}', json_encode($this->coverageData), $html);

        file_put_contents($this->reportsDir . '/custom_report.html', $html);
    }

    /**
     * Generate JSON report
     */
    private function generateJSONReport()
    {
        $jsonReport = [
            'metadata' => [
                'generated_at' => $this->coverageData['timestamp'],
                'tool' => 'APS Dream Home Coverage Analyzer',
                'version' => '1.0'
            ],
            'summary' => $this->coverageData['summary'],
            'overall_coverage' => $this->calculateOverallCoverage(),
            'file_coverage' => $this->analyzeFileCoverage(),
            'uncovered_areas' => isset($this->coverageData['analysis']) ?
                $this->coverageData['analysis']['uncovered_areas'] : [],
            'recommendations' => $this->coverageData['recommendations'] ?? []
        ];

        file_put_contents($this->reportsDir . '/coverage_report.json', json_encode($jsonReport, JSON_PRETTY_PRINT));
    }

    /**
     * Calculate coverage percentage
     */
    private function calculateCoveragePercentage($covered, $total)
    {
        return $total > 0 ? round(($covered / $total) * 100, 1) : 0;
    }

    /**
     * Load coverage configuration
     */
    private function loadCoverageConfig()
    {
        return [
            'min_coverage' => 70, // Minimum acceptable coverage percentage
            'critical_coverage' => 50, // Below this is critical
            'report_formats' => ['html', 'xml', 'json', 'text'],
            'exclude_paths' => ['vendor/', 'tests/', 'storage/']
        ];
    }

    /**
     * Get HTML report template
     */
    private function getHTMLReportTemplate()
    {
        return '
        <!DOCTYPE html>
        <html>
        <head>
            <title>APS Dream Home Code Coverage Report</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { background: #667eea; color: white; padding: 20px; border-radius: 8px; }
                .summary { background: #f8f9fa; padding: 15px; margin: 20px 0; border-radius: 8px; }
                .coverage-bar { height: 20px; background: #eee; border-radius: 10px; overflow: hidden; margin: 5px 0; }
                .coverage-fill { height: 100%; background: linear-gradient(90deg, #dc3545 0%, #ffc107 50%, #28a745 100%); }
                .file-list { max-height: 400px; overflow-y: auto; }
                .file-item { padding: 8px; border-bottom: 1px solid #eee; }
                .excellent { background: #d4edda; }
                .good { background: #cce5ff; }
                .fair { background: #fff3cd; }
                .poor { background: #f8d7da; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📊 APS Dream Home Code Coverage Report</h1>
                <p>Generated on: {{TIMESTAMP}}</p>
            </div>

            <div class="summary">
                <h2>Coverage Summary</h2>
                <div id="coverage-summary"></div>
            </div>

            <div class="summary">
                <h2>File Coverage Details</h2>
                <div class="file-list" id="file-coverage"></div>
            </div>

            <script>
                // Load coverage data
                const coverageData = {{COVERAGE_DATA}};
                const overallCoverage = {{OVERALL_COVERAGE}};

                // Display summary
                const summaryDiv = document.getElementById("coverage-summary");
                summaryDiv.innerHTML = `
                    <h3>Line Coverage: ${overallCoverage.line_coverage}%</h3>
                    <div class="coverage-bar">
                        <div class="coverage-fill" style="width: ${overallCoverage.line_coverage}%"></div>
                    </div>
                    <p>Functions: ${overallCoverage.function_coverage}% | Classes: ${overallCoverage.class_coverage}%</p>
                `;

                // Display file details
                const fileDiv = document.getElementById("file-coverage");
                if (coverageData.files) {
                    const sortedFiles = Object.entries(coverageData.files)
                        .sort(([,a], [,b]) => a.coverage_percentage - b.coverage_percentage);

                    sortedFiles.forEach(([file, data]) => {
                        const coverageClass = data.coverage_percentage >= 80 ? "excellent" :
                                            data.coverage_percentage >= 60 ? "good" :
                                            data.coverage_percentage >= 40 ? "fair" : "poor";

                        fileDiv.innerHTML += `
                            <div class="file-item ${coverageClass}">
                                <strong>${file.split("/").pop()}</strong>
                                <div class="coverage-bar">
                                    <div class="coverage-fill" style="width: ${data.coverage_percentage}%"></div>
                                </div>
                                <small>${data.coverage_percentage}% (${data.lines_covered}/${data.lines_total} lines)</small>
                            </div>
                        `;
                    });
                }
            </script>
        </body>
        </html>';
    }

    /**
     * Display coverage results in console
     */
    public function displayResults()
    {
        if (empty($this->coverageData)) {
            echo "❌ No coverage data available. Run analysis first.\n";
            return;
        }

        echo "\n📊 CODE COVERAGE ANALYSIS RESULTS\n";
        echo "=================================\n\n";

        $overall = $this->calculateOverallCoverage();

        echo "🎯 OVERALL COVERAGE:\n";
        echo "-------------------\n";
        printf("Line Coverage: %.1f%%\n", $overall['line_coverage']);
        printf("Function Coverage: %.1f%%\n", $overall['function_coverage']);
        printf("Class Coverage: %.1f%%\n", $overall['class_coverage']);
        printf("Branch Coverage: %.1f%%\n", $overall['branch_coverage']);

        $grade = $this->getCoverageGrade($overall['line_coverage']);
        echo "\n🏆 Coverage Grade: {$grade['grade']} ({$grade['description']})\n\n";

        if (isset($this->coverageData['analysis'])) {
            $analysis = $this->coverageData['analysis'];

            echo "📈 COVERAGE DISTRIBUTION:\n";
            echo "-------------------------\n";
            $dist = $analysis['file_coverage_distribution']['distribution'];
            printf("Excellent (≥80%%): %d files\n", $dist['excellent']);
            printf("Good (60-80%%): %d files\n", $dist['good']);
            printf("Fair (40-60%%): %d files\n", $dist['fair']);
            printf("Poor (20-40%%): %d files\n", $dist['poor']);
            printf("Critical (<20%%): %d files\n", $dist['critical']);

            if (!empty($analysis['uncovered_areas']['files_with_zero_coverage'])) {
                echo "\n🚨 FILES WITH ZERO COVERAGE:\n";
                echo "-----------------------------\n";
                foreach (array_slice($analysis['uncovered_areas']['files_with_zero_coverage'], 0, 5) as $file) {
                    echo "• " . basename($file) . "\n";
                }
                if (count($analysis['uncovered_areas']['files_with_zero_coverage']) > 5) {
                    echo "• ... and " . (count($analysis['uncovered_areas']['files_with_zero_coverage']) - 5) . " more\n";
                }
            }
        }

        echo "\n📋 REPORTS GENERATED:\n";
        echo "--------------------\n";
        echo "• HTML Report: {$this->reportsDir}/html/index.html\n";
        echo "• XML Report: {$this->reportsDir}/coverage.xml\n";
        echo "• JSON Report: {$this->reportsDir}/coverage_report.json\n";
        echo "• Text Summary: {$this->reportsDir}/coverage_summary.txt\n";
        echo "• Custom HTML: {$this->reportsDir}/custom_report.html\n";

        echo "\n💡 RECOMMENDATIONS:\n";
        echo "------------------\n";
        if (isset($this->coverageData['recommendations'])) {
            foreach ($this->coverageData['recommendations'] as $rec) {
                echo "• {$rec}\n";
            }
        }
    }

    /**
     * Get coverage grade
     */
    private function getCoverageGrade($percentage)
    {
        if ($percentage >= 90) return ['grade' => 'A+', 'description' => 'Exceptional coverage'];
        if ($percentage >= 80) return ['grade' => 'A', 'description' => 'Excellent coverage'];
        if ($percentage >= 70) return ['grade' => 'B', 'description' => 'Good coverage'];
        if ($percentage >= 60) return ['grade' => 'C', 'description' => 'Fair coverage'];
        if ($percentage >= 50) return ['grade' => 'D', 'description' => 'Poor coverage'];
        return ['grade' => 'F', 'description' => 'Critical - immediate action required'];
    }
}

// Run coverage analysis if called directly
if (basename(__FILE__) === basename($_SERVER['PHP_SELF'] ?? '')) {
    $analyzer = new CodeCoverageAnalyzer();
    $success = $analyzer->runCoverageAnalysis();

    if ($success) {
        $analyzer->displayResults();
    }
}
