<?php
/**
 * APS Dream Home - Error Tracking and Alerting Script
 * Automated error tracking and alerting system implementation
 */

echo "🚨 APS DREAM HOME - ERROR TRACKING AND ALERTING\n";
echo "=============================================\n\n";

// Load centralized path configuration
require_once __DIR__ . '/config/paths.php';

// Error tracking results
$errorResults = [];
$totalImplementations = 0;
$successfulImplementations = 0;

echo "🔍 IMPLEMENTING ERROR TRACKING AND ALERTING...\n\n";

// 1. Create error tracking class
echo "Step 1: Creating error tracking class\n";
$errorTrackerFile = APP_PATH . '/Monitoring/ErrorTracker.php';
$errorTrackerContent = "<?php\n";
$errorTrackerContent .= "/**\n";
$errorTrackerContent .= " * APS Dream Home - Error Tracker\n";
$errorTrackerContent .= " */\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "namespace App\\Monitoring;\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "class ErrorTracker\n";
$errorTrackerContent .= "{\n";
$errorTrackerContent .= "    private static \$instance = null;\n";
$errorTrackerContent .= "    private \$config;\n";
$errorTrackerContent .= "    private \$errorCounts = [];\n";
$errorTrackerContent .= "    private \$alertThresholds;\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function __construct()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$this->config = require CONFIG_PATH . '/monitoring.php';\n";
$errorTrackerContent .= "        \$this->alertThresholds = \$this->config['alerts']['thresholds'];\n";
$errorTrackerContent .= "        \$this->initializeErrorCounts();\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    public static function getInstance()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        if (self::\$instance === null) {\n";
$errorTrackerContent .= "            self::\$instance = new self();\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        return self::\$instance;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function initializeErrorCounts()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$this->errorCounts = [\n";
$errorTrackerContent .= "            'total' => 0,\n";
$errorTrackerContent .= "            'by_type' => [],\n";
$errorTrackerContent .= "            'by_severity' => [\n";
$errorTrackerContent .= "                'critical' => 0,\n";
$errorTrackerContent .= "                'high' => 0,\n";
$errorTrackerContent .= "                'medium' => 0,\n";
$errorTrackerContent .= "                'low' => 0\n";
$errorTrackerContent .= "            ],\n";
$errorTrackerContent .= "            'recent' => [],\n";
$errorTrackerContent .= "            'trends' => []\n";
$errorTrackerContent .= "        ];\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    public function trackError(\$error, \$type = 'exception', \$severity = 'medium', \$context = [])\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$errorData = [\n";
$errorTrackerContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$errorTrackerContent .= "            'error' => \$error,\n";
$errorTrackerContent .= "            'type' => \$type,\n";
$errorTrackerContent .= "            'severity' => \$severity,\n";
$errorTrackerContent .= "            'context' => array_merge([\n";
$errorTrackerContent .= "                'uri' => \$_SERVER['REQUEST_URI'] ?? 'unknown',\n";
$errorTrackerContent .= "                'method' => \$_SERVER['REQUEST_METHOD'] ?? 'unknown',\n";
$errorTrackerContent .= "                'ip' => \$_SERVER['REMOTE_ADDR'] ?? 'unknown',\n";
$errorTrackerContent .= "                'user_agent' => \$_SERVER['HTTP_USER_AGENT'] ?? 'unknown',\n";
$errorTrackerContent .= "                'referer' => \$_SERVER['HTTP_REFERER'] ?? 'unknown'\n";
$errorTrackerContent .= "            ], \$context),\n";
$errorTrackerContent .= "            'stack_trace' => \$this->getStackTrace(),\n";
$errorTrackerContent .= "            'request_id' => uniqid('error_')\n";
$errorTrackerContent .= "        ];\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Update error counts\n";
$errorTrackerContent .= "        \$this->updateErrorCounts(\$errorData);\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Log error\n";
$errorTrackerContent .= "        \$this->logError(\$errorData);\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Check alert conditions\n";
$errorTrackerContent .= "        \$this->checkAlertConditions(\$errorData);\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        return \$errorData['request_id'];\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function updateErrorCounts(\$errorData)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$this->errorCounts['total']++;\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        // Count by type\n";
$errorTrackerContent .= "        \$type = \$errorData['type'];\n";
$errorTrackerContent .= "        \$this->errorCounts['by_type'][\$type] = (\$this->errorCounts['by_type'][\$type] ?? 0) + 1;\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        // Count by severity\n";
$errorTrackerContent .= "        \$severity = \$errorData['severity'];\n";
$errorTrackerContent .= "        if (isset(\$this->errorCounts['by_severity'][\$severity])) {\n";
$errorTrackerContent .= "            \$this->errorCounts['by_severity'][\$severity]++;\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        // Add to recent errors (keep last 100)\n";
$errorTrackerContent .= "        array_unshift(\$this->errorCounts['recent'], \$errorData);\n";
$errorTrackerContent .= "        \$this->errorCounts['recent'] = array_slice(\$this->errorCounts['recent'], 0, 100);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function getStackTrace()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);\n";
$errorTrackerContent .= "        \$formattedTrace = [];\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        foreach (\$trace as \$i => \$frame) {\n";
$errorTrackerContent .= "            \$formattedTrace[] = [\n";
$errorTrackerContent .= "                'file' => \$frame['file'] ?? 'unknown',\n";
$errorTrackerContent .= "                'line' => \$frame['line'] ?? 0,\n";
$errorTrackerContent .= "                'function' => \$frame['function'] ?? 'unknown',\n";
$errorTrackerContent .= "                'class' => \$frame['class'] ?? null\n";
$errorTrackerContent .= "            ];\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        return \$formattedTrace;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function logError(\$errorData)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$logFile = BASE_PATH . '/logs/error_tracking.log';\n";
$errorTrackerContent .= "        file_put_contents(\$logFile, json_encode(\$errorData) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function checkAlertConditions(\$errorData)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        // Check severity-based alerts\n";
$errorTrackerContent .= "        if (\$errorData['severity'] === 'critical') {\n";
$errorTrackerContent .= "            \$this->sendAlert(\$errorData, 'critical_error');\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Check error rate alerts\n";
$errorTrackerContent .= "        \$errorRate = \$this->getErrorRate();\n";
$errorTrackerContent .= "        if (\$errorRate > \$this->alertThresholds['error_rate']) {\n";
$errorTrackerContent .= "            \$this->sendAlert(\$errorData, 'high_error_rate');\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Check error type spikes\n";
$errorTrackerContent .= "        \$this->checkErrorTypeSpikes(\$errorData);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function getErrorRate()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$oneMinuteAgo = time() - 60;\n";
$errorTrackerContent .= "        \$recentErrors = 0;\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        foreach (\$this->errorCounts['recent'] as \$error) {\n";
$errorTrackerContent .= "            if (strtotime(\$error['timestamp']) >= \$oneMinuteAgo) {\n";
$errorTrackerContent .= "                \$recentErrors++;\n";
$errorTrackerContent .= "            }\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        return \$recentErrors;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function checkErrorTypeSpikes(\$errorData)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$type = \$errorData['type'];\n";
$errorTrackerContent .= "        \$recentTypeErrors = 0;\n";
$errorTrackerContent .= "        \$fiveMinutesAgo = time() - 300;\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        foreach (\$this->errorCounts['recent'] as \$error) {\n";
$errorTrackerContent .= "            if (\$error['type'] === \$type && strtotime(\$error['timestamp']) >= \$fiveMinutesAgo) {\n";
$errorTrackerContent .= "                \$recentTypeErrors++;\n";
$errorTrackerContent .= "            }\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        // Alert if more than 10 errors of same type in 5 minutes\n";
$errorTrackerContent .= "        if (\$recentTypeErrors > 10) {\n";
$errorTrackerContent .= "            \$this->sendAlert(\$errorData, 'error_type_spike');\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function sendAlert(\$errorData, \$alertType)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        if (!\$this->config['alerts']['enabled']) {\n";
$errorTrackerContent .= "            return;\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        \$alert = [\n";
$errorTrackerContent .= "            'id' => uniqid('alert_'),\n";
$errorTrackerContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$errorTrackerContent .= "            'type' => \$alertType,\n";
$errorTrackerContent .= "            'severity' => \$errorData['severity'],\n";
$errorTrackerContent .= "            'message' => \$this->getAlertMessage(\$alertType, \$errorData),\n";
$errorTrackerContent .= "            'error_data' => \$errorData,\n";
$errorTrackerContent .= "            'status' => 'active'\n";
$errorTrackerContent .= "        ];\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Log alert\n";
$errorTrackerContent .= "        \$this->logAlert(\$alert);\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        // Send notifications\n";
$errorTrackerContent .= "        \$this->sendNotifications(\$alert);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function getAlertMessage(\$alertType, \$errorData)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$messages = [\n";
$errorTrackerContent .= "            'critical_error' => 'Critical error detected: ' . \$errorData['error'],\n";
$errorTrackerContent .= "            'high_error_rate' => 'High error rate detected: ' . \$this->getErrorRate() . ' errors per minute',\n";
$errorTrackerContent .= "            'error_type_spike' => 'Error type spike detected: ' . \$errorData['type'] . ' errors increasing rapidly'\n";
$errorTrackerContent .= "        ];\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        return \$messages[\$alertType] ?? 'Unknown alert type: ' . \$alertType;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function logAlert(\$alert)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$alertFile = BASE_PATH . '/logs/error_alerts.log';\n";
$errorTrackerContent .= "        file_put_contents(\$alertFile, json_encode(\$alert) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function sendNotifications(\$alert)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$channels = \$this->config['alerts']['channels'];\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        foreach (\$channels as \$channel) {\n";
$errorTrackerContent .= "            switch (\$channel) {\n";
$errorTrackerContent .= "                case 'email':\n";
$errorTrackerContent .= "                    \$this->sendEmailAlert(\$alert);\n";
$errorTrackerContent .= "                    break;\n";
$errorTrackerContent .= "                case 'log':\n";
$errorTrackerContent .= "                    // Already logged in logAlert()\n";
$errorTrackerContent .= "                    break;\n";
$errorTrackerContent .= "                case 'webhook':\n";
$errorTrackerContent .= "                    \$this->sendWebhookAlert(\$alert);\n";
$errorTrackerContent .= "                    break;\n";
$errorTrackerContent .= "            }\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function sendEmailAlert(\$alert)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$to = \$this->config['alerts']['email_recipients'];\n";
$errorTrackerContent .= "        \$subject = 'APS Dream Home - ' . strtoupper(\$alert['severity']) . ' Alert';\n";
$errorTrackerContent .= "        \$message = \$this->formatEmailMessage(\$alert);\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        \$headers = [\n";
$errorTrackerContent .= "            'From: noreply@apsdreamhomes.com',\n";
$errorTrackerContent .= "            'Content-Type: text/html; charset=UTF-8'\n";
$errorTrackerContent .= "        ];\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "        foreach (\$to as \$recipient) {\n";
$errorTrackerContent .= "            mail(\$recipient, \$subject, \$message, implode(\"\\r\\n\", \$headers));\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function formatEmailMessage(\$alert)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$html = '<html><body>';\n";
$errorTrackerContent .= "        \$html .= '<h2>APS Dream Home - Error Alert</h2>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Alert Type:</strong> ' . ucfirst(\$alert['type']) . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Severity:</strong> ' . ucfirst(\$alert['severity']) . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Time:</strong> ' . \$alert['timestamp'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Message:</strong> ' . \$alert['message'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<h3>Error Details:</h3>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Error:</strong> ' . \$alert['error_data']['error'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>Type:</strong> ' . \$alert['error_data']['type'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>URI:</strong> ' . \$alert['error_data']['context']['uri'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '<p><strong>IP:</strong> ' . \$alert['error_data']['context']['ip'] . '</p>';\n";
$errorTrackerContent .= "        \$html .= '</body></html>';\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        return \$html;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    private function sendWebhookAlert(\$alert)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        // Placeholder for webhook implementation\n";
$errorTrackerContent .= "        // Could integrate with Slack, Discord, or other webhook services\n";
$errorTrackerContent .= "        \$webhookUrl = \$this->config['alerts']['webhook_url'] ?? null;\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        if (\$webhookUrl) {\n";
$errorTrackerContent .= "            \$payload = json_encode(\$alert);\n";
$errorTrackerContent .= "            \$ch = curl_init(\$webhookUrl);\n";
$errorTrackerContent .= "            curl_setopt(\$ch, CURLOPT_POST, true);\n";
$errorTrackerContent .= "            curl_setopt(\$ch, CURLOPT_POSTFIELDS, \$payload);\n";
$errorTrackerContent .= "            curl_setopt(\$ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);\n";
$errorTrackerContent .= "            curl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n";
$errorTrackerContent .= "            curl_exec(\$ch);\n";
$errorTrackerContent .= "            curl_close(\$ch);\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    public function getErrorStats()\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        return \$this->errorCounts;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    public function getRecentErrors(\$limit = 50)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        return array_slice(\$this->errorCounts['recent'], 0, \$limit);\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "\n";
$errorTrackerContent .= "    public function getErrorTrends(\$hours = 24)\n";
$errorTrackerContent .= "    {\n";
$errorTrackerContent .= "        \$trends = [];\n";
$errorTrackerContent .= "        \$startTime = time() - (\$hours * 3600);\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        foreach (\$this->errorCounts['recent'] as \$error) {\n";
$errorTrackerContent .= "            if (strtotime(\$error['timestamp']) >= \$startTime) {\n";
$errorTrackerContent .= "                \$hour = date('H', strtotime(\$error['timestamp']));\n";
$errorTrackerContent .= "                if (!isset(\$trends[\$hour])) {\n";
$errorTrackerContent .= "                    \$trends[\$hour] = 0;\n";
$errorTrackerContent .= "                }\n";
$errorTrackerContent .= "                \$trends[\$hour]++;\n";
$errorTrackerContent .= "            }\n";
$errorTrackerContent .= "        }\n";
$errorTrackerContent .= "        \n";
$errorTrackerContent .= "        return \$trends;\n";
$errorTrackerContent .= "    }\n";
$errorTrackerContent .= "}\n";

if (file_put_contents($errorTrackerFile, $errorTrackerContent)) {
    echo "   ✅ Error tracking class created: app/Monitoring/ErrorTracker.php\n";
    $errorResults['error_tracker'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create error tracking class\n";
    $errorResults['error_tracker'] = 'failed';
}
$totalImplementations++;

// 2. Create alerting system
echo "\nStep 2: Creating alerting system\n";
$alertingSystemFile = APP_PATH . '/Monitoring/AlertingSystem.php';
$alertingSystemContent = "<?php\n";
$alertingSystemContent .= "/**\n";
$alertingSystemContent .= " * APS Dream Home - Alerting System\n";
$alertingSystemContent .= " */\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "namespace App\\Monitoring;\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "class AlertingSystem\n";
$alertingSystemContent .= "{\n";
$alertingSystemContent .= "    private static \$instance = null;\n";
$alertingSystemContent .= "    private \$config;\n";
$alertingSystemContent .= "    private \$activeAlerts = [];\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function __construct()\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$this->config = require CONFIG_PATH . '/monitoring.php';\n";
$alertingSystemContent .= "        \$this->loadActiveAlerts();\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public static function getInstance()\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        if (self::\$instance === null) {\n";
$alertingSystemContent .= "            self::\$instance = new self();\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "        return self::\$instance;\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public function createAlert(\$type, \$message, \$severity = 'medium', \$data = [])\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$alert = [\n";
$alertingSystemContent .= "            'id' => uniqid('alert_'),\n";
$alertingSystemContent .= "            'type' => \$type,\n";
$alertingSystemContent .= "            'message' => \$message,\n";
$alertingSystemContent .= "            'severity' => \$severity,\n";
$alertingSystemContent .= "            'data' => \$data,\n";
$alertingSystemContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$alertingSystemContent .= "            'status' => 'active',\n";
$alertingSystemContent .= "            'acknowledged' => false,\n";
$alertingSystemContent .= "            'resolved' => false,\n";
$alertingSystemContent .= "            'resolved_at' => null,\n";
$alertingSystemContent .= "            'acknowledged_at' => null,\n";
$alertingSystemContent .= "            'acknowledged_by' => null\n";
$alertingSystemContent .= "        ];\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alert['id']] = \$alert;\n";
$alertingSystemContent .= "        \$this->saveAlert(\$alert);\n";
$alertingSystemContent .= "        \$this->sendNotification(\$alert);\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        return \$alert['id'];\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public function acknowledgeAlert(\$alertId, \$acknowledgedBy)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        if (!isset(\$this->activeAlerts[\$alertId])) {\n";
$alertingSystemContent .= "            return false;\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['acknowledged'] = true;\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['acknowledged_at'] = date('Y-m-d H:i:s');\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['acknowledged_by'] = \$acknowledgedBy;\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['status'] = 'acknowledged';\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$this->saveAlert(\$this->activeAlerts[\$alertId]);\n";
$alertingSystemContent .= "        return true;\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public function resolveAlert(\$alertId)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        if (!isset(\$this->activeAlerts[\$alertId])) {\n";
$alertingSystemContent .= "            return false;\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['resolved'] = true;\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['resolved_at'] = date('Y-m-d H:i:s');\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alertId]['status'] = 'resolved';\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$this->saveAlert(\$this->activeAlerts[\$alertId]);\n";
$alertingSystemContent .= "        return true;\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public function getActiveAlerts()\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        return array_filter(\$this->activeAlerts, function(\$alert) {\n";
$alertingSystemContent .= "            return !\$alert['resolved'];\n";
$alertingSystemContent .= "        });\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    public function getAlertsBySeverity(\$severity)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        return array_filter(\$this->activeAlerts, function(\$alert) use (\$severity) {\n";
$alertingSystemContent .= "            return \$alert['severity'] === \$severity && !\$alert['resolved'];\n";
$alertingSystemContent .= "        });\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function loadActiveAlerts()\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$alertFile = BASE_PATH . '/logs/active_alerts.json';\n";
$alertingSystemContent .= "        if (file_exists(\$alertFile)) {\n";
$alertingSystemContent .= "            \$alerts = json_decode(file_get_contents(\$alertFile), true);\n";
$alertingSystemContent .= "            if (is_array(\$alerts)) {\n";
$alertingSystemContent .= "                \$this->activeAlerts = \$alerts;\n";
$alertingSystemContent .= "            }\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function saveAlert(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$this->activeAlerts[\$alert['id']] = \$alert;\n";
$alertingSystemContent .= "        \$alertFile = BASE_PATH . '/logs/active_alerts.json';\n";
$alertingSystemContent .= "        file_put_contents(\$alertFile, json_encode(\$this->activeAlerts), LOCK_EX);\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function sendNotification(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        if (!\$this->config['alerts']['enabled']) {\n";
$alertingSystemContent .= "            return;\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        \$channels = \$this->config['alerts']['channels'];\n";
$alertingSystemContent .= "        \n";
$alertingSystemContent .= "        foreach (\$channels as \$channel) {\n";
$alertingSystemContent .= "            switch (\$channel) {\n";
$alertingSystemContent .= "                case 'email':\n";
$alertingSystemContent .= "                    \$this->sendEmailNotification(\$alert);\n";
$alertingSystemContent .= "                    break;\n";
$alertingSystemContent .= "                case 'log':\n";
$alertingSystemContent .= "                    \$this->logAlert(\$alert);\n";
$alertingSystemContent .= "                    break;\n";
$alertingSystemContent .= "                case 'webhook':\n";
$alertingSystemContent .= "                    \$this->sendWebhookNotification(\$alert);\n";
$alertingSystemContent .= "                    break;\n";
$alertingSystemContent .= "            }\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function sendEmailNotification(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$to = \$this->config['alerts']['email_recipients'];\n";
$alertingSystemContent .= "        \$subject = 'APS Dream Home Alert: ' . ucfirst(\$alert['type']);\n";
$alertingSystemContent .= "        \$message = \$this->formatAlertMessage(\$alert);\n";
$alertingSystemContent .= "        \n";
$alertingSystemContent .= "        \$headers = [\n";
$alertingSystemContent .= "            'From: noreply@apsdreamhomes.com',\n";
$alertingSystemContent .= "            'Content-Type: text/html; charset=UTF-8'\n";
$alertingSystemContent .= "        ];\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "        foreach (\$to as \$recipient) {\n";
$alertingSystemContent .= "            mail(\$recipient, \$subject, \$message, implode(\"\\r\\n\", \$headers));\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function formatAlertMessage(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$html = '<html><body>';\n";
$alertingSystemContent .= "        \$html .= '<h2>APS Dream Home - System Alert</h2>';\n";
$alertingSystemContent .= "        \$html .= '<p><strong>Alert Type:</strong> ' . ucfirst(\$alert['type']) . '</p>';\n";
$alertingSystemContent .= "        \$html .= '<p><strong>Severity:</strong> ' . ucfirst(\$alert['severity']) . '</p>';\n";
$alertingSystemContent .= "        \$html .= '<p><strong>Time:</strong> ' . \$alert['timestamp'] . '</p>';\n";
$alertingSystemContent .= "        \$html .= '<p><strong>Message:</strong> ' . \$alert['message'] . '</p>';\n";
$alertingSystemContent .= "        \$html .= '<p><strong>Status:</strong> ' . ucfirst(\$alert['status']) . '</p>';\n";
$alertingSystemContent .= "        \$html .= '</body></html>';\n";
$alertingSystemContent .= "        \n";
$alertingSystemContent .= "        return \$html;\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function logAlert(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$logFile = BASE_PATH . '/logs/alerts.log';\n";
$alertingSystemContent .= "        file_put_contents(\$logFile, json_encode(\$alert) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "\n";
$alertingSystemContent .= "    private function sendWebhookNotification(\$alert)\n";
$alertingSystemContent .= "    {\n";
$alertingSystemContent .= "        \$webhookUrl = \$this->config['alerts']['webhook_url'] ?? null;\n";
$alertingSystemContent .= "        \n";
$alertingSystemContent .= "        if (\$webhookUrl) {\n";
$alertingSystemContent .= "            \$payload = json_encode(\$alert);\n";
$alertingSystemContent .= "            \$ch = curl_init(\$webhookUrl);\n";
$alertingSystemContent .= "            curl_setopt(\$ch, CURLOPT_POST, true);\n";
$alertingSystemContent .= "            curl_setopt(\$ch, CURLOPT_POSTFIELDS, \$payload);\n";
$alertingSystemContent .= "            curl_setopt(\$ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);\n";
$alertingSystemContent .= "            curl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n";
$alertingSystemContent .= "            curl_exec(\$ch);\n";
$alertingSystemContent .= "            curl_close(\$ch);\n";
$alertingSystemContent .= "        }\n";
$alertingSystemContent .= "    }\n";
$alertingSystemContent .= "}\n";

if (file_put_contents($alertingSystemFile, $alertingSystemContent)) {
    echo "   ✅ Alerting system created: app/Monitoring/AlertingSystem.php\n";
    $errorResults['alerting_system'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create alerting system\n";
    $errorResults['alerting_system'] = 'failed';
}
$totalImplementations++;

// 3. Create error tracking middleware
echo "\nStep 3: Creating error tracking middleware\n";
$errorMiddlewareFile = APP_PATH . '/Http/Middleware/ErrorTrackingMiddleware.php';
$errorMiddlewareContent = "<?php\n";
$errorMiddlewareContent .= "/**\n";
$errorMiddlewareContent .= " * APS Dream Home - Error Tracking Middleware\n";
$errorMiddlewareContent .= " */\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "namespace App\\Http\\Middleware;\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "use App\\Monitoring\\ErrorTracker;\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "class ErrorTrackingMiddleware\n";
$errorMiddlewareContent .= "{\n";
$errorMiddlewareContent .= "    private \$errorTracker;\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "    public function __construct()\n";
$errorMiddlewareContent .= "    {\n";
$errorMiddlewareContent .= "        \$this->errorTracker = ErrorTracker::getInstance();\n";
$errorMiddlewareContent .= "    }\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "    public function handle(\$request, \$next)\n";
$errorMiddlewareContent .= "    {\n";
$errorMiddlewareContent .= "        try {\n";
$errorMiddlewareContent .= "            // Process request\n";
$errorMiddlewareContent .= "            \$response = \$next(\$request);\n";
$errorMiddlewareContent .= "        } catch (Exception \$e) {\n";
$errorMiddlewareContent .= "            // Track error\n";
$errorMiddlewareContent .= "            \$this->errorTracker->trackError(\n";
$errorMiddlewareContent .= "                \$e->getMessage(),\n";
$errorMiddlewareContent .= "                'exception',\n";
$errorMiddlewareContent .= "                \$this->determineSeverity(\$e),\n";
$errorMiddlewareContent .= "                [\n";
$errorMiddlewareContent .= "                    'file' => \$e->getFile(),\n";
$errorMiddlewareContent .= "                    'line' => \$e->getLine(),\n";
$errorMiddlewareContent .= "                    'trace' => \$e->getTraceAsString()\n";
$errorMiddlewareContent .= "                ]\n";
$errorMiddlewareContent .= "            );\n";
$errorMiddlewareContent .= "            \n";
$errorMiddlewareContent .= "            // Re-throw exception\n";
$errorMiddlewareContent .= "            throw \$e;\n";
$errorMiddlewareContent .= "        }\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "        return \$response;\n";
$errorMiddlewareContent .= "    }\n";
$errorMiddlewareContent .= "\n";
$errorMiddlewareContent .= "    private function determineSeverity(\$exception)\n";
$errorMiddlewareContent .= "    {\n";
$errorMiddlewareContent .= "        \$message = \$exception->getMessage();\n";
$errorMiddlewareContent .= "        \n";
$errorMiddlewareContent .= "        // Critical errors\n";
$errorMiddlewareContent .= "        if (strpos(\$message, 'database') !== false || \n";
$errorMiddlewareContent .= "            strpos(\$message, 'connection') !== false ||\n";
$errorMiddlewareContent .= "            strpos(\$message, 'fatal') !== false) {\n";
$errorMiddlewareContent .= "            return 'critical';\n";
$errorMiddlewareContent .= "        }\n";
$errorMiddlewareContent .= "        \n";
$errorMiddlewareContent .= "        // High severity errors\n";
$errorMiddlewareContent .= "        if (strpos(\$message, 'permission') !== false || \n";
$errorMiddlewareContent .= "            strpos(\$message, 'access denied') !== false ||\n";
$errorMiddlewareContent .= "            strpos(\$message, 'security') !== false) {\n";
$errorMiddlewareContent .= "            return 'high';\n";
$errorMiddlewareContent .= "        }\n";
$errorMiddlewareContent .= "        \n";
$errorMiddlewareContent .= "        // Default to medium\n";
$errorMiddlewareContent .= "        return 'medium';\n";
$errorMiddlewareContent .= "    }\n";
$errorMiddlewareContent .= "}\n";

if (file_put_contents($errorMiddlewareFile, $errorMiddlewareContent)) {
    echo "   ✅ Error tracking middleware created: app/Http/Middleware/ErrorTrackingMiddleware.php\n";
    $errorResults['error_middleware'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create error tracking middleware\n";
    $errorResults['error_middleware'] = 'failed';
}
$totalImplementations++;

// 4. Create error dashboard
echo "\nStep 4: Creating error dashboard\n";
$errorDashboardFile = BASE_PATH . '/error_dashboard.php';
$errorDashboardContent = "<?php\n";
$errorDashboardContent .= "/**\n";
$errorDashboardContent .= " * APS Dream Home - Error Dashboard\n";
$errorDashboardContent .= " */\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "require_once __DIR__ . '/config/paths.php';\n";
$errorDashboardContent .= "require_once APP_PATH . '/Monitoring/ErrorTracker.php';\n";
$errorDashboardContent .= "require_once APP_PATH . '/Monitoring/AlertingSystem.php';\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "echo '<!DOCTYPE html>\n";
$errorDashboardContent .= "<html>\n";
$errorDashboardContent .= "<head>\n";
$errorDashboardContent .= "    <title>APS Dream Home - Error Dashboard</title>\n";
$errorDashboardContent .= "    <meta charset=\"UTF-8\">\n";
$errorDashboardContent .= "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
$errorDashboardContent .= "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n";
$errorDashboardContent .= "    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n";
$errorDashboardContent .= "    <style>\n";
$errorDashboardContent .= "        .error-card { transition: all 0.3s ease; }\n";
$errorDashboardContent .= "        .error-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.1); }\n";
$errorDashboardContent .= "        .severity-critical { border-left: 4px solid #dc3545; }\n";
$errorDashboardContent .= "        .severity-high { border-left: 4px solid #fd7e14; }\n";
$errorDashboardContent .= "        .severity-medium { border-left: 4px solid #ffc107; }\n";
$errorDashboardContent .= "        .severity-low { border-left: 4px solid #28a745; }\n";
$errorDashboardContent .= "        .chart-container { position: relative; height: 300px; }\n";
$errorDashboardContent .= "        .error-details { max-height: 400px; overflow-y: auto; }\n";
$errorDashboardContent .= "    </style>\n";
$errorDashboardContent .= "</head>\n";
$errorDashboardContent .= "<body>\n";
$errorDashboardContent .= "    <nav class=\"navbar navbar-dark bg-dark\">\n";
$errorDashboardContent .= "        <div class=\"container-fluid\">\n";
$errorDashboardContent .= "            <span class=\"navbar-brand mb-0 h1\">🚨 APS Dream Home - Error Dashboard</span>\n";
$errorDashboardContent .= "            <span class=\"navbar-text\">Last Updated: <span id=\"lastUpdate\">-</span></span>\n";
$errorDashboardContent .= "        </div>\n";
$errorDashboardContent .= "    </nav>\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "    <div class=\"container-fluid mt-4\">\n";
$errorDashboardContent .= "        <div class=\"row\">\n";
$errorDashboardContent .= "            <div class=\"col-md-3\">\n";
$errorDashboardContent .= "                <div class=\"card error-card severity-critical\">\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <h5 class=\"card-title\">Critical Errors</h5>\n";
$errorDashboardContent .= "                        <h2 class=\"text-danger\" id=\"criticalErrors\">-</h2>\n";
$errorDashboardContent .= "                        <small class=\"text-muted\">Last 24 hours</small>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "            <div class=\"col-md-3\">\n";
$errorDashboardContent .= "                <div class=\"card error-card severity-high\">\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <h5 class=\"card-title\">High Errors</h5>\n";
$errorDashboardContent .= "                        <h2 class=\"text-warning\" id=\"highErrors\">-</h2>\n";
$errorDashboardContent .= "                        <small class=\"text-muted\">Last 24 hours</small>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "            <div class=\"col-md-3\">\n";
$errorDashboardContent .= "                <div class=\"card error-card severity-medium\">\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <h5 class=\"card-title\">Medium Errors</h5>\n";
$errorDashboardContent .= "                        <h2 class=\"text-info\" id=\"mediumErrors\">-</h2>\n";
$errorDashboardContent .= "                        <small class=\"text-muted\">Last 24 hours</small>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "            <div class=\"col-md-3\">\n";
$errorDashboardContent .= "                <div class=\"card error-card severity-low\">\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <h5 class=\"card-title\">Low Errors</h5>\n";
$errorDashboardContent .= "                        <h2 class=\"text-success\" id=\"lowErrors\">-</h2>\n";
$errorDashboardContent .= "                        <small class=\"text-muted\">Last 24 hours</small>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "        </div>\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "        <div class=\"row mt-4\">\n";
$errorDashboardContent .= "            <div class=\"col-md-6\">\n";
$errorDashboardContent .= "                <div class=\"card\">\n";
$errorDashboardContent .= "                    <div class=\"card-header\">\n";
$errorDashboardContent .= "                        <h5>Error Trends</h5>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <div class=\"chart-container\">\n";
$errorDashboardContent .= "                            <canvas id=\"errorTrendsChart\"></canvas>\n";
$errorDashboardContent .= "                        </div>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "            <div class=\"col-md-6\">\n";
$errorDashboardContent .= "                <div class=\"card\">\n";
$errorDashboardContent .= "                    <div class=\"card-header\">\n";
$errorDashboardContent .= "                        <h5>Error Types</h5>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                    <div class=\"card-body\">\n";
$errorDashboardContent .= "                        <div class=\"chart-container\">\n";
$errorDashboardContent .= "                            <canvas id=\"errorTypesChart\"></canvas>\n";
$errorDashboardContent .= "                        </div>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "        </div>\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "        <div class=\"row mt-4\">\n";
$errorDashboardContent .= "            <div class=\"col-12\">\n";
$errorDashboardContent .= "                <div class=\"card\">\n";
$errorDashboardContent .= "                    <div class=\"card-header\">\n";
$errorDashboardContent .= "                        <h5>Recent Errors</h5>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                    <div class=\"card-body error-details\">\n";
$errorDashboardContent .= "                        <div id=\"recentErrors\">Loading...</div>\n";
$errorDashboardContent .= "                    </div>\n";
$errorDashboardContent .= "                </div>\n";
$errorDashboardContent .= "            </div>\n";
$errorDashboardContent .= "        </div>\n";
$errorDashboardContent .= "    </div>\n";
$errorDashboardContent .= "\n";
$errorDashboardContent .= "    <script>\n";
$errorDashboardContent .= "        // Initialize dashboard\n";
$errorDashboardContent .= "        let errorTrendsChart, errorTypesChart;\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        function initCharts() {\n";
$errorDashboardContent .= "            // Error Trends Chart\n";
$errorDashboardContent .= "            const trendsCtx = document.getElementById('errorTrendsChart').getContext('2d');\n";
$errorDashboardContent .= "            errorTrendsChart = new Chart(trendsCtx, {\n";
$errorDashboardContent .= "                type: 'line',\n";
$errorDashboardContent .= "                data: {\n";
$errorDashboardContent .= "                    labels: [],\n";
$errorDashboardContent .= "                    datasets: [{\n";
$errorDashboardContent .= "                        label: 'Errors per Hour',\n";
$errorDashboardContent .= "                        data: [],\n";
$errorDashboardContent .= "                        borderColor: 'rgb(255, 99, 132)',\n";
$errorDashboardContent .= "                        backgroundColor: 'rgba(255, 99, 132, 0.2)',\n";
$errorDashboardContent .= "                        tension: 0.1\n";
$errorDashboardContent .= "                    }]\n";
$errorDashboardContent .= "                },\n";
$errorDashboardContent .= "                options: {\n";
$errorDashboardContent .= "                    responsive: true,\n";
$errorDashboardContent .= "                    maintainAspectRatio: false,\n";
$errorDashboardContent .= "                    scales: {\n";
$errorDashboardContent .= "                        y: {\n";
$errorDashboardContent .= "                            beginAtZero: true\n";
$errorDashboardContent .= "                        }\n";
$errorDashboardContent .= "                    }\n";
$errorDashboardContent .= "                }\n";
$errorDashboardContent .= "            });\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            // Error Types Chart\n";
$errorDashboardContent .= "            const typesCtx = document.getElementById('errorTypesChart').getContext('2d');\n";
$errorDashboardContent .= "            errorTypesChart = new Chart(typesCtx, {\n";
$errorDashboardContent .= "                type: 'doughnut',\n";
$errorDashboardContent .= "                data: {\n";
$errorDashboardContent .= "                    labels: [],\n";
$errorDashboardContent .= "                    datasets: [{\n";
$errorDashboardContent .= "                        data: [],\n";
$errorDashboardContent .= "                        backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF']\n";
$errorDashboardContent .= "                    }]\n";
$errorDashboardContent .= "                },\n";
$errorDashboardContent .= "                options: {\n";
$errorDashboardContent .= "                    responsive: true,\n";
$errorDashboardContent .= "                    maintainAspectRatio: false\n";
$errorDashboardContent .= "                }\n";
$errorDashboardContent .= "            });\n";
$errorDashboardContent .= "        }\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        function updateDashboard() {\n";
$errorDashboardContent .= "            fetch('/error_data.php')\n";
$errorDashboardContent .= "                .then(response => response.json())\n";
$errorDashboardContent .= "                .then(data => {\n";
$errorDashboardContent .= "                    // Update metrics\n";
$errorDashboardContent .= "                    document.getElementById('criticalErrors').textContent = data.critical_errors || 0;\n";
$errorDashboardContent .= "                    document.getElementById('highErrors').textContent = data.high_errors || 0;\n";
$errorDashboardContent .= "                    document.getElementById('mediumErrors').textContent = data.medium_errors || 0;\n";
$errorDashboardContent .= "                    document.getElementById('lowErrors').textContent = data.low_errors || 0;\n";
$errorDashboardContent .= "                    document.getElementById('lastUpdate').textContent = new Date().toLocaleTimeString();\n";
$errorDashboardContent .= "                    \n";
$errorDashboardContent .= "                    // Update charts\n";
$errorDashboardContent .= "                    updateCharts(data);\n";
$errorDashboardContent .= "                    \n";
$errorDashboardContent .= "                    // Update recent errors\n";
$errorDashboardContent .= "                    updateRecentErrors(data.recent_errors);\n";
$errorDashboardContent .= "                })\n";
$errorDashboardContent .= "                .catch(error => console.error('Error updating dashboard:', error));\n";
$errorDashboardContent .= "        }\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        function updateCharts(data) {\n";
$errorDashboardContent .= "            // Update error trends chart\n";
$errorDashboardContent .= "            if (errorTrendsChart && data.error_trends) {\n";
$errorDashboardContent .= "                errorTrendsChart.data.labels = Object.keys(data.error_trends);\n";
$errorDashboardContent .= "                errorTrendsChart.data.datasets[0].data = Object.values(data.error_trends);\n";
$errorDashboardContent .= "                errorTrendsChart.update();\n";
$errorDashboardContent .= "            }\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            // Update error types chart\n";
$errorDashboardContent .= "            if (errorTypesChart && data.error_types) {\n";
$errorDashboardContent .= "                errorTypesChart.data.labels = Object.keys(data.error_types);\n";
$errorDashboardContent .= "                errorTypesChart.data.datasets[0].data = Object.values(data.error_types);\n";
$errorDashboardContent .= "                errorTypesChart.update();\n";
$errorDashboardContent .= "            }\n";
$errorDashboardContent .= "        }\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        function updateRecentErrors(errors) {\n";
$errorDashboardContent .= "            const container = document.getElementById('recentErrors');\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            if (!errors || errors.length === 0) {\n";
$errorDashboardContent .= "                container.innerHTML = '<p class=\"text-muted\">No recent errors</p>';\n";
$errorDashboardContent .= "                return;\n";
$errorDashboardContent .= "            }\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            let html = '<div class=\"table-responsive\"><table class=\"table table-sm\">';\n";
$errorDashboardContent .= "            html += '<thead><tr><th>Time</th><th>Type</th><th>Severity</th><th>Error</th><th>URI</th></tr></thead><tbody>';\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            errors.forEach(error => {\n";
$errorDashboardContent .= "                const severityClass = 'severity-' + error.severity;\n";
$errorDashboardContent .= "                html += '<tr class=\"' + severityClass + '\">';\n";
$errorDashboardContent .= "                html += '<td>' + error.timestamp + '</td>';\n";
$errorDashboardContent .= "                html += '<td>' + error.type + '</td>';\n";
$errorDashboardContent .= "                html += '<td><span class=\"badge bg-' + getSeverityColor(error.severity) + '\">' + error.severity.toUpperCase() + '</span></td>';\n";
$errorDashboardContent .= "                html += '<td>' + error.error.substring(0, 100) + (error.error.length > 100 ? '...' : '') + '</td>';\n";
$errorDashboardContent .= "                html += '<td>' + error.context.uri + '</td>';\n";
$errorDashboardContent .= "                html += '</tr>';\n";
$errorDashboardContent .= "            });\n";
$errorDashboardContent .= "            \n";
$errorDashboardContent .= "            html += '</tbody></table></div>';\n";
$errorDashboardContent .= "            container.innerHTML = html;\n";
$errorDashboardContent .= "        }\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        function getSeverityColor(severity) {\n";
$errorDashboardContent .= "            switch(severity) {\n";
$errorDashboardContent .= "                case 'critical': return 'danger';\n";
$errorDashboardContent .= "                case 'high': return 'warning';\n";
$errorDashboardContent .= "                case 'medium': return 'info';\n";
$errorDashboardContent .= "                case 'low': return 'success';\n";
$errorDashboardContent .= "                default: return 'secondary';\n";
$errorDashboardContent .= "            }\n";
$errorDashboardContent .= "        }\n";
$errorDashboardContent .= "        \n";
$errorDashboardContent .= "        // Initialize and start auto-refresh\n";
$errorDashboardContent .= "        document.addEventListener('DOMContentLoaded', function() {\n";
$errorDashboardContent .= "            initCharts();\n";
$errorDashboardContent .= "            updateDashboard();\n";
$errorDashboardContent .= "            setInterval(updateDashboard, 10000); // Update every 10 seconds\n";
$errorDashboardContent .= "        });\n";
$errorDashboardContent .= "    </script>\n";
$errorDashboardContent .= "</body>\n";
$errorDashboardContent .= "</html>';\n";

if (file_put_contents($errorDashboardFile, $errorDashboardContent)) {
    echo "   ✅ Error dashboard created: error_dashboard.php\n";
    $errorResults['error_dashboard'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create error dashboard\n";
    $errorResults['error_dashboard'] = 'failed';
}
$totalImplementations++;

// 5. Create error data API
echo "\nStep 5: Creating error data API\n";
$errorApiFile = BASE_PATH . '/error_data.php';
$errorApiContent = "<?php\n";
$errorApiContent .= "/**\n";
$errorApiContent .= " * APS Dream Home - Error Data API\n";
$errorApiContent .= " */\n";
$errorApiContent .= "\n";
$errorApiContent .= "header('Content-Type: application/json');\n";
$errorApiContent .= "\n";
$errorApiContent .= "require_once __DIR__ . '/config/paths.php';\n";
$errorApiContent .= "require_once APP_PATH . '/Monitoring/ErrorTracker.php';\n";
$errorApiContent .= "require_once APP_PATH . '/Monitoring/AlertingSystem.php';\n";
$errorApiContent .= "\n";
$errorApiContent .= "\$errorTracker = App\\Monitoring\\ErrorTracker::getInstance();\n";
$errorApiContent .= "\$alertingSystem = App\\Monitoring\\AlertingSystem::getInstance();\n";
$errorApiContent .= "\n";
$errorApiContent .= "\$errorStats = \$errorTracker->getErrorStats();\n";
$errorApiContent .= "\$recentErrors = \$errorTracker->getRecentErrors(20);\n";
$errorApiContent .= "\$errorTrends = \$errorTracker->getErrorTrends(24);\n";
$errorApiContent .= "\$activeAlerts = \$alertingSystem->getActiveAlerts();\n";
$errorApiContent .= "\n";
$errorApiContent .= "\$data = [\n";
$errorApiContent .= "    'critical_errors' => \$errorStats['by_severity']['critical'] ?? 0,\n";
$errorApiContent .= "    'high_errors' => \$errorStats['by_severity']['high'] ?? 0,\n";
$errorApiContent .= "    'medium_errors' => \$errorStats['by_severity']['medium'] ?? 0,\n";
$errorApiContent .= "    'low_errors' => \$errorStats['by_severity']['low'] ?? 0,\n";
$errorApiContent .= "    'total_errors' => \$errorStats['total'],\n";
$errorApiContent .= "    'error_types' => \$errorStats['by_type'],\n";
$errorApiContent .= "    'error_trends' => \$errorTrends,\n";
$errorApiContent .= "    'recent_errors' => \$recentErrors,\n";
$errorApiContent .= "    'active_alerts' => count(\$activeAlerts),\n";
$errorApiContent .= "    'error_rate' => calculateErrorRate(),\n";
$errorApiContent .= "    'most_common_error' => getMostCommonError(\$errorStats['by_type'])\n";
$errorApiContent .= "];\n";
$errorApiContent .= "\n";
$errorApiContent .= "echo json_encode(\$data);\n";
$errorApiContent .= "\n";
$errorApiContent .= "function calculateErrorRate()\n";
$errorApiContent .= "{\n";
$errorApiContent .= "    \$logFile = BASE_PATH . '/logs/error_tracking.log';\n";
$errorApiContent .= "    if (!file_exists(\$logFile)) return 0;\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    \$oneMinuteAgo = time() - 60;\n";
$errorApiContent .= "    \$count = 0;\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    \$handle = fopen(\$logFile, 'r');\n";
$errorApiContent .= "    if (\$handle) {\n";
$errorApiContent .= "        while ((\$line = fgets(\$handle)) !== false) {\n";
$errorApiContent .= "            \$entry = json_decode(\$line, true);\n";
$errorApiContent .= "            if (\$entry && strtotime(\$entry['timestamp']) >= \$oneMinuteAgo) {\n";
$errorApiContent .= "                \$count++;\n";
$errorApiContent .= "            }\n";
$errorApiContent .= "        }\n";
$errorApiContent .= "        fclose(\$handle);\n";
$errorApiContent .= "    }\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    return \$count;\n";
$errorApiContent .= "}\n";
$errorApiContent .= "\n";
$errorApiContent .= "function getMostCommonError(\$errorTypes)\n";
$errorApiContent .= "{\n";
$errorApiContent .= "    if (empty(\$errorTypes)) return null;\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    \$maxCount = 0;\n";
$errorApiContent .= "    \$mostCommon = null;\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    foreach (\$errorTypes as \$type => \$count) {\n";
$errorApiContent .= "        if (\$count > \$maxCount) {\n";
$errorApiContent .= "            \$maxCount = \$count;\n";
$errorApiContent .= "            \$mostCommon = \$type;\n";
$errorApiContent .= "        }\n";
$errorApiContent .= "    }\n";
$errorApiContent .= "    \n";
$errorApiContent .= "    return \$mostCommon;\n";
$errorApiContent .= "}\n";

if (file_put_contents($errorApiFile, $errorApiContent)) {
    echo "   ✅ Error data API created: error_data.php\n";
    $errorResults['error_api'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create error data API\n";
    $errorResults['error_api'] = 'failed';
}
$totalImplementations++;

// Summary
echo "\n=============================================\n";
echo "📊 ERROR TRACKING AND ALERTING SUMMARY\n";
echo "=============================================\n";

$successRate = round(($successfulImplementations / $totalImplementations) * 100, 1);
echo "📊 TOTAL IMPLEMENTATIONS: $totalImplementations\n";
echo "✅ SUCCESSFUL: $successfulImplementations\n";
echo "📊 SUCCESS RATE: $successRate%\n\n";

echo "🔧 ERROR TRACKING IMPLEMENTATION DETAILS:\n";
foreach ($errorResults as $category => $result) {
    $icon = $result === 'created' ? '✅' : ($result === 'failed' ? '❌' : '⚠️');
    echo "📋 $category: $result\n";
}

if ($successRate >= 80) {
    echo "\n🎉 ERROR TRACKING AND ALERTING: EXCELLENT!\n";
} elseif ($successRate >= 60) {
    echo "\n✅ ERROR TRACKING AND ALERTING: GOOD!\n";
} else {
    echo "\n⚠️  ERROR TRACKING AND ALERTING: NEEDS IMPROVEMENT\n";
}

echo "\n🚀 Error tracking and alerting implemented successfully!\n";
echo "📊 Ready for next monitoring step: User Experience Monitoring\n";
?>
