#!/bin/bash
echo "🚀 APS Dream Home - Enhanced Development Launch"
echo "==============================================="
echo ""
echo "📋 Starting development environment..."
echo ""
echo "1. Starting Vite development server..."
echo "   Command: npx vite --config vite.config.enhanced.js --host 0.0.0.0 --port 3000"
echo ""
echo "2. Starting PHP development server..."
echo "   Command: php -S localhost:8000 -t ."
echo ""
echo "🌐 Access your application:"
echo "   • Enhanced Dev: http://localhost:3000"
echo "   • PHP Server: http://localhost:8000"
echo "   • Admin Panel: http://localhost:8000/admin/admin_panel.php"
echo ""
echo "🛠️ Available commands:"
echo "   npm run dev     - Enhanced development"
echo "   npm run build   - Production build"
echo "   npm run preview - Preview production"
echo "   node test-system.js - System validation"
echo ""
echo "🎉 Enhanced development environment ready!"
echo ""
echo "Start coding with modern tools and hot reload! ✨"
