<?php
/**
 * APS Dream Home - SQL Injection Protection Script
 * Automated SQL injection protection implementation
 */

echo "🗄️ APS DREAM HOME - SQL INJECTION PROTECTION\n";
echo "==========================================\n\n";

// Load centralized path configuration
require_once __DIR__ . '/config/paths.php';

// Security implementation results
$securityResults = [];
$totalImplementations = 0;
$successfulImplementations = 0;

echo "🔍 IMPLEMENTING SQL INJECTION PROTECTION...\n\n";

// 1. Create secure database class
echo "Step 1: Creating secure database class\n";
$secureDbFile = APP_PATH . '/Security/SecureDatabase.php';
$secureDbContent = "<?php\n";
$secureDbContent .= "/**\n";
$secureDbContent .= " * APS Dream Home - Secure Database Handler\n";
$secureDbContent .= " */\n";
$secureDbContent .= "\n";
$secureDbContent .= "namespace App\\Security;\n";
$secureDbContent .= "\n";
$secureDbContent .= "class SecureDatabase\n";
$secureDbContent .= "{\n";
$secureDbContent .= "    private static \$instance = null;\n";
$secureDbContent .= "    private \$connection;\n";
$secureDbContent .= "    private \$config;\n";
$secureDbContent .= "\n";
$secureDbContent .= "    private function __construct()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$this->config = require CONFIG_PATH . '/database.php';\n";
$secureDbContent .= "        \$this->connect();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public static function getInstance()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        if (self::\$instance === null) {\n";
$secureDbContent .= "            self::\$instance = new self();\n";
$secureDbContent .= "        }\n";
$secureDbContent .= "        return self::\$instance;\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    private function connect()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        try {\n";
$secureDbContent .= "            \$dsn = 'mysql:host=' . \$this->config['host'] . ';dbname=' . \$this->config['database'] . ';charset=utf8mb4';\n";
$secureDbContent .= "            \$this->connection = new PDO(\$dsn, \$this->config['username'], \$this->config['password']);\n";
$secureDbContent .= "            \$this->connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n";
$secureDbContent .= "            \$this->connection->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);\n";
$secureDbContent .= "            \$this->connection->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);\n";
$secureDbContent .= "        } catch (PDOException \$e) {\n";
$secureDbContent .= "            throw new Exception('Database connection failed: ' . \$e->getMessage());\n";
$secureDbContent .= "        }\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function query(\$sql, \$params = [])\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        try {\n";
$secureDbContent .= "            \$stmt = \$this->connection->prepare(\$sql);\n";
$secureDbContent .= "            \$stmt->execute(\$params);\n";
$secureDbContent .= "            return \$stmt;\n";
$secureDbContent .= "        } catch (PDOException \$e) {\n";
$secureDbContent .= "            \$this->logError(\$sql, \$params, \$e->getMessage());\n";
$secureDbContent .= "            throw new Exception('Query failed: ' . \$e->getMessage());\n";
$secureDbContent .= "        }\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function select(\$sql, \$params = [])\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$stmt = \$this->query(\$sql, \$params);\n";
$secureDbContent .= "        return \$stmt->fetchAll();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function selectOne(\$sql, \$params = [])\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$stmt = \$this->query(\$sql, \$params);\n";
$secureDbContent .= "        return \$stmt->fetch();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function insert(\$table, \$data)\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$columns = implode(', ', array_keys(\$data));\n";
$secureDbContent .= "        \$placeholders = ':' . implode(', :', array_keys(\$data));\n";
$secureDbContent .= "        \$sql = \"INSERT INTO \$table (\$columns) VALUES (\$placeholders)\";\n";
$secureDbContent .= "        \n";
$secureDbContent .= "        \$this->query(\$sql, \$data);\n";
$secureDbContent .= "        return \$this->connection->lastInsertId();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function update(\$table, \$data, \$where, \$whereParams = [])\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$set = [];\n";
$secureDbContent .= "        foreach (\$data as \$key => \$value) {\n";
$secureDbContent .= "            \$set[] = \"\$key = :\$key\";\n";
$secureDbContent .= "        }\n";
$secureDbContent .= "        \n";
$secureDbContent .= "        \$sql = \"UPDATE \$table SET \" . implode(', ', \$set) . \" WHERE \$where\";\n";
$secureDbContent .= "        \$params = array_merge(\$data, \$whereParams);\n";
$secureDbContent .= "        \n";
$secureDbContent .= "        \$stmt = \$this->query(\$sql, \$params);\n";
$secureDbContent .= "        return \$stmt->rowCount();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function delete(\$table, \$where, \$params = [])\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$sql = \"DELETE FROM \$table WHERE \$where\";\n";
$secureDbContent .= "        \$stmt = \$this->query(\$sql, \$params);\n";
$secureDbContent .= "        return \$stmt->rowCount();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function escape(\$value)\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        return \$this->connection->quote(\$value);\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function getLastInsertId()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        return \$this->connection->lastInsertId();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function beginTransaction()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        return \$this->connection->beginTransaction();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function commit()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        return \$this->connection->commit();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    public function rollback()\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        return \$this->connection->rollback();\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "\n";
$secureDbContent .= "    private function logError(\$sql, \$params, \$error)\n";
$secureDbContent .= "    {\n";
$secureDbContent .= "        \$logEntry = [\n";
$secureDbContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$secureDbContent .= "            'sql' => \$sql,\n";
$secureDbContent .= "            'params' => \$params,\n";
$secureDbContent .= "            'error' => \$error,\n";
$secureDbContent .= "            'ip' => \$_SERVER['REMOTE_ADDR'] ?? 'unknown',\n";
$secureDbContent .= "            'user_agent' => \$_SERVER['HTTP_USER_AGENT'] ?? 'unknown'\n";
$secureDbContent .= "        ];\n";
$secureDbContent .= "        \n";
$secureDbContent .= "        \$logFile = BASE_PATH . '/logs/database_errors.log';\n";
$secureDbContent .= "        file_put_contents(\$logFile, json_encode(\$logEntry) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$secureDbContent .= "    }\n";
$secureDbContent .= "}\n";

if (file_put_contents($secureDbFile, $secureDbContent)) {
    echo "   ✅ Secure database class created: app/Security/SecureDatabase.php\n";
    $securityResults['secure_database'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create secure database class\n";
    $securityResults['secure_database'] = 'failed';
}
$totalImplementations++;

// 2. Create query builder class
echo "\nStep 2: Creating query builder class\n";
$queryBuilderFile = APP_PATH . '/Security/QueryBuilder.php';
$queryBuilderContent = "<?php\n";
$queryBuilderContent .= "/**\n";
$queryBuilderContent .= " * APS Dream Home - Query Builder\n";
$queryBuilderContent .= " */\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "namespace App\\Security;\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "class QueryBuilder\n";
$queryBuilderContent .= "{\n";
$queryBuilderContent .= "    private \$table;\n";
$queryBuilderContent .= "    private \$select = '*';\n";
$queryBuilderContent .= "    private \$where = [];\n";
$queryBuilderContent .= "    private \$orderBy = [];\n";
$queryBuilderContent .= "    private \$limit;\n";
$queryBuilderContent .= "    private \$offset;\n";
$queryBuilderContent .= "    private \$joins = [];\n";
$queryBuilderContent .= "    private \$groupBy = [];\n";
$queryBuilderContent .= "    private \$having = [];\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function __construct(\$table)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->table = \$table;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function select(\$columns = '*')\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->select = is_array(\$columns) ? implode(', ', \$columns) : \$columns;\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function where(\$column, \$operator = null, \$value = null)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        if (func_num_args() === 2) {\n";
$queryBuilderContent .= "            \$value = \$operator;\n";
$queryBuilderContent .= "            \$operator = '=';\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        \$this->where[] = [\$column, \$operator, \$value];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function whereIn(\$column, \$values)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$placeholders = str_repeat('?,', count(\$values) - 1) . '?';\n";
$queryBuilderContent .= "        \$this->where[] = [\$column, 'IN', \$values];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function whereLike(\$column, \$value)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->where[] = [\$column, 'LIKE', \$value];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function orderBy(\$column, \$direction = 'ASC')\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->orderBy[] = [\$column, strtoupper(\$direction)];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function limit(\$limit)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->limit = \$limit;\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function offset(\$offset)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->offset = \$offset;\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function join(\$table, \$first, \$operator = null, \$second = null)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        if (func_num_args() === 3) {\n";
$queryBuilderContent .= "            \$second = \$operator;\n";
$queryBuilderContent .= "            \$operator = '=';\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        \$this->joins[] = ['INNER', \$table, \$first, \$operator, \$second];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function leftJoin(\$table, \$first, \$operator = null, \$second = null)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        if (func_num_args() === 3) {\n";
$queryBuilderContent .= "            \$second = \$operator;\n";
$queryBuilderContent .= "            \$operator = '=';\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        \$this->joins[] = ['LEFT', \$table, \$first, \$operator, \$second];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function groupBy(\$columns)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$this->groupBy = is_array(\$columns) ? \$columns : [\$columns];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function having(\$column, \$operator = null, \$value = null)\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        if (func_num_args() === 2) {\n";
$queryBuilderContent .= "            \$value = \$operator;\n";
$queryBuilderContent .= "            \$operator = '=';\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        \$this->having[] = [\$column, \$operator, \$value];\n";
$queryBuilderContent .= "        return \$this;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function build()\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$sql = \"SELECT {\$this->select} FROM {\$this->table}\";\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add joins\n";
$queryBuilderContent .= "        foreach (\$this->joins as \$join) {\n";
$queryBuilderContent .= "            \$sql .= \" {\$join[0]} JOIN {\$join[1]} ON {\$join[2]} {\$join[3]} {\$join[4]}\";\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add where conditions\n";
$queryBuilderContent .= "        if (!empty(\$this->where)) {\n";
$queryBuilderContent .= "            \$sql .= ' WHERE ';\n";
$queryBuilderContent .= "            \$conditions = [];\n";
$queryBuilderContent .= "            foreach (\$this->where as \$where) {\n";
$queryBuilderContent .= "                if (\$where[1] === 'IN') {\n";
$queryBuilderContent .= "                    \$conditions[] = \"{\$where[0]} {\$where[1]} (\" . str_repeat('?,', count(\$where[2]) - 1) . '?)';\n";
$queryBuilderContent .= "                } else {\n";
$queryBuilderContent .= "                    \$conditions[] = \"{\$where[0]} {\$where[1]} ?\";\n";
$queryBuilderContent .= "                }\n";
$queryBuilderContent .= "            }\n";
$queryBuilderContent .= "            \$sql .= implode(' AND ', \$conditions);\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add group by\n";
$queryBuilderContent .= "        if (!empty(\$this->groupBy)) {\n";
$queryBuilderContent .= "            \$sql .= ' GROUP BY ' . implode(', ', \$this->groupBy);\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add having conditions\n";
$queryBuilderContent .= "        if (!empty(\$this->having)) {\n";
$queryBuilderContent .= "            \$sql .= ' HAVING ';\n";
$queryBuilderContent .= "            \$conditions = [];\n";
$queryBuilderContent .= "            foreach (\$this->having as \$having) {\n";
$queryBuilderContent .= "                \$conditions[] = \"{\$having[0]} {\$having[1]} ?\";\n";
$queryBuilderContent .= "            }\n";
$queryBuilderContent .= "            \$sql .= implode(' AND ', \$conditions);\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add order by\n";
$queryBuilderContent .= "        if (!empty(\$this->orderBy)) {\n";
$queryBuilderContent .= "            \$orders = [];\n";
$queryBuilderContent .= "            foreach (\$this->orderBy as \$order) {\n";
$queryBuilderContent .= "                \$orders[] = \"{\$order[0]} {\$order[1]}\";\n";
$queryBuilderContent .= "            }\n";
$queryBuilderContent .= "            \$sql .= ' ORDER BY ' . implode(', ', \$orders);\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add limit\n";
$queryBuilderContent .= "        if (\$this->limit !== null) {\n";
$queryBuilderContent .= "            \$sql .= \" LIMIT {\$this->limit}\";\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add offset\n";
$queryBuilderContent .= "        if (\$this->offset !== null) {\n";
$queryBuilderContent .= "            \$sql .= \" OFFSET {\$this->offset}\";\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        return \$sql;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "    public function getParams()\n";
$queryBuilderContent .= "    {\n";
$queryBuilderContent .= "        \$params = [];\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add where parameters\n";
$queryBuilderContent .= "        foreach (\$this->where as \$where) {\n";
$queryBuilderContent .= "            if (\$where[1] === 'IN') {\n";
$queryBuilderContent .= "                foreach (\$where[2] as \$value) {\n";
$queryBuilderContent .= "                    \$params[] = \$value;\n";
$queryBuilderContent .= "                }\n";
$queryBuilderContent .= "            } else {\n";
$queryBuilderContent .= "                \$params[] = \$where[2];\n";
$queryBuilderContent .= "            }\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        // Add having parameters\n";
$queryBuilderContent .= "        foreach (\$this->having as \$having) {\n";
$queryBuilderContent .= "            \$params[] = \$having[2];\n";
$queryBuilderContent .= "        }\n";
$queryBuilderContent .= "\n";
$queryBuilderContent .= "        return \$params;\n";
$queryBuilderContent .= "    }\n";
$queryBuilderContent .= "}\n";

if (file_put_contents($queryBuilderFile, $queryBuilderContent)) {
    echo "   ✅ Query builder class created: app/Security/QueryBuilder.php\n";
    $securityResults['query_builder'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create query builder class\n";
    $securityResults['query_builder'] = 'failed';
}
$totalImplementations++;

// 3. Create SQL injection detection class
echo "\nStep 3: Creating SQL injection detection class\n";
$detectionFile = APP_PATH . '/Security/SQLInjectionDetector.php';
$detectionContent = "<?php\n";
$detectionContent .= "/**\n";
$detectionContent .= " * APS Dream Home - SQL Injection Detector\n";
$detectionContent .= " */\n";
$detectionContent .= "\n";
$detectionContent .= "namespace App\\Security;\n";
$detectionContent .= "\n";
$detectionContent .= "class SQLInjectionDetector\n";
$detectionContent .= "{\n";
$detectionContent .= "    private static \$instance = null;\n";
$detectionContent .= "    private \$patterns;\n";
$detectionContent .= "\n";
$detectionContent .= "    private function __construct()\n";
$detectionContent .= "    {\n";
$detectionContent .= "        \$this->initializePatterns();\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    public static function getInstance()\n";
$detectionContent .= "    {\n";
$detectionContent .= "        if (self::\$instance === null) {\n";
$detectionContent .= "            self::\$instance = new self();\n";
$detectionContent .= "        }\n";
$detectionContent .= "        return self::\$instance;\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    private function initializePatterns()\n";
$detectionContent .= "    {\n";
$detectionContent .= "        \$this->patterns = [\n";
$detectionContent .= "            // SQL keywords\n";
$detectionContent .= "            '/(union|select|insert|update|delete|drop|create|alter|exec|script|truncate)/i',\n";
$detectionContent .= "            // SQL comments\n";
$detectionContent .= "            '/(\\/\\*|\\*\\/|--|#)/i',\n";
$detectionContent .= "            // SQL operators\n";
$detectionContent .= "            '/(or|and|not|like|between|in|exists|is|null)/i',\n";
$detectionContent .= "            // SQL functions\n";
$detectionContent .= "            '/(concat|substring|char|ascii|ord|length|user|database|version)/i',\n";
$detectionContent .= "            // SQL syntax\n";
$detectionContent .= "            '/(\\\"|\\'|\\\\|;|xp_|sp_|0x[0-9a-f]+)/i',\n";
$detectionContent .= "            // Boolean-based injection\n";
$detectionContent .= "            '/(1=1|1=2|true|false)/i',\n";
$detectionContent .= "            // Time-based injection\n";
$detectionContent .= "            '/(sleep|benchmark|waitfor)/i'\n";
$detectionContent .= "        ];\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    public function detect(\$input)\n";
$detectionContent .= "    {\n";
$detectionContent .= "        if (is_array(\$input)) {\n";
$detectionContent .= "            return \$this->detectArray(\$input);\n";
$detectionContent .= "        }\n";
$detectionContent .= "\n";
$detectionContent .= "        return \$this->detectString(\$input);\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    private function detectArray(\$input)\n";
$detectionContent .= "    {\n";
$detectionContent .= "        foreach (\$input as \$key => \$value) {\n";
$detectionContent .= "            if (\$this->detect(\$value)) {\n";
$detectionContent .= "                return true;\n";
$detectionContent .= "            }\n";
$detectionContent .= "        }\n";
$detectionContent .= "        return false;\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    private function detectString(\$input)\n";
$detectionContent .= "    {\n";
$detectionContent .= "        foreach (\$this->patterns as \$pattern) {\n";
$detectionContent .= "            if (preg_match(\$pattern, \$input)) {\n";
$detectionContent .= "                return true;\n";
$detectionContent .= "            }\n";
$detectionContent .= "        }\n";
$detectionContent .= "        return false;\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    public function getThreatLevel(\$input)\n";
$detectionContent .= "    {\n";
$detectionContent .= "        \$threats = 0;\n";
$detectionContent .= "        \$highRiskPatterns = ['/(union|select|insert|update|delete|drop|create|alter|exec|script)/i', '/(\\/\\*|\\*\\/|--|#)/i'];\n";
$detectionContent .= "        \$mediumRiskPatterns = ['/(or|and|not|like|between|in|exists|is|null)/i', '/(\\\"|\\'|\\\\|;|xp_|sp_|0x[0-9a-f]+)/i'];\n";
$detectionContent .= "\n";
$detectionContent .= "        foreach (\$highRiskPatterns as \$pattern) {\n";
$detectionContent .= "            if (preg_match(\$pattern, \$input)) {\n";
$detectionContent .= "                \$threats += 3;\n";
$detectionContent .= "            }\n";
$detectionContent .= "        }\n";
$detectionContent .= "\n";
$detectionContent .= "        foreach (\$mediumRiskPatterns as \$pattern) {\n";
$detectionContent .= "            if (preg_match(\$pattern, \$input)) {\n";
$detectionContent .= "                \$threats += 2;\n";
$detectionContent .= "            }\n";
$detectionContent .= "        }\n";
$detectionContent .= "\n";
$detectionContent .= "        if (\$threats >= 5) {\n";
$detectionContent .= "            return 'HIGH';\n";
$detectionContent .= "        } elseif (\$threats >= 2) {\n";
$detectionContent .= "            return 'MEDIUM';\n";
$detectionContent .= "        } elseif (\$threats >= 1) {\n";
$detectionContent .= "            return 'LOW';\n";
$detectionContent .= "        }\n";
$detectionContent .= "\n";
$detectionContent .= "        return 'NONE';\n";
$detectionContent .= "    }\n";
$detectionContent .= "\n";
$detectionContent .= "    public function logAttempt(\$input, \$threatLevel)\n";
$detectionContent .= "    {\n";
$detectionContent .= "        \$logEntry = [\n";
$detectionContent .= "            'timestamp' => date('Y-m-d H:i:s'),\n";
$detectionContent .= "            'ip' => \$_SERVER['REMOTE_ADDR'] ?? 'unknown',\n";
$detectionContent .= "            'user_agent' => \$_SERVER['HTTP_USER_AGENT'] ?? 'unknown',\n";
$detectionContent .= "            'input' => \$input,\n";
$detectionContent .= "            'threat_level' => \$threatLevel,\n";
$detectionContent .= "            'uri' => \$_SERVER['REQUEST_URI'] ?? 'unknown'\n";
$detectionContent .= "        ];\n";
$detectionContent .= "\n";
$detectionContent .= "        \$logFile = BASE_PATH . '/logs/sql_injection_attempts.log';\n";
$detectionContent .= "        file_put_contents(\$logFile, json_encode(\$logEntry) . PHP_EOL, FILE_APPEND | LOCK_EX);\n";
$detectionContent .= "    }\n";
$detectionContent .= "}\n";

if (file_put_contents($detectionFile, $detectionContent)) {
    echo "   ✅ SQL injection detector class created: app/Security/SQLInjectionDetector.php\n";
    $securityResults['sql_injection_detector'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create SQL injection detector class\n";
    $securityResults['sql_injection_detector'] = 'failed';
}
$totalImplementations++;

// 4. Create SQL injection protection middleware
echo "\nStep 4: Creating SQL injection protection middleware\n";
$middlewareFile = APP_PATH . '/Http/Middleware/SQLInjectionProtectionMiddleware.php';
$middlewareContent = "<?php\n";
$middlewareContent .= "/**\n";
$middlewareContent .= " * APS Dream Home - SQL Injection Protection Middleware\n";
$middlewareContent .= " */\n";
$middlewareContent .= "\n";
$middlewareContent .= "namespace App\\Http\\Middleware;\n";
$middlewareContent .= "\n";
$middlewareContent .= "use App\\Security\\SQLInjectionDetector;\n";
$middlewareContent .= "\n";
$middlewareContent .= "class SQLInjectionProtectionMiddleware\n";
$middlewareContent .= "{\n";
$middlewareContent .= "    private \$detector;\n";
$middlewareContent .= "\n";
$middlewareContent .= "    public function __construct()\n";
$middlewareContent .= "    {\n";
$middlewareContent .= "        \$this->detector = SQLInjectionDetector::getInstance();\n";
$middlewareContent .= "    }\n";
$middlewareContent .= "\n";
$middlewareContent .= "    public function handle(\$request, \$next)\n";
$middlewareContent .= "    {\n";
$middlewareContent .= "        // Get all input data\n";
$middlewareContent .= "        \$inputData = \$request->getAllInput();\n";
$middlewareContent .= "\n";
$middlewareContent .= "        // Check for SQL injection attempts\n";
$middlewareContent .= "        if (\$this->detector->detect(\$inputData)) {\n";
$middlewareContent .= "            \$threatLevel = \$this->detector->getThreatLevel(json_encode(\$inputData));\n";
$middlewareContent .= "            \$this->detector->logAttempt(json_encode(\$inputData), \$threatLevel);\n";
$middlewareContent .= "\n";
$middlewareContent .= "            return response()->json([\n";
$middlewareContent .= "                'success' => false,\n";
$middlewareContent .= "                'message' => 'Security violation detected',\n";
$middlewareContent .= "                'error' => 'SQL injection attempt blocked'\n";
$middlewareContent .= "            ], 403);\n";
$middlewareContent .= "        }\n";
$middlewareContent .= "\n";
$middlewareContent .= "        return \$next(\$request);\n";
$middlewareContent .= "    }\n";
$middlewareContent .= "}\n";

if (file_put_contents($middlewareFile, $middlewareContent)) {
    echo "   ✅ SQL injection protection middleware created: app/Http/Middleware/SQLInjectionProtectionMiddleware.php\n";
    $securityResults['sql_injection_middleware'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create SQL injection protection middleware\n";
    $securityResults['sql_injection_middleware'] = 'failed';
}
$totalImplementations++;

// 5. Create SQL injection testing script
echo "\nStep 5: Creating SQL injection testing script\n";
$testingScriptFile = BASE_PATH . '/test_sql_injection_protection.php';
$testingScriptContent = "<?php\n";
$testingScriptContent .= "/**\n";
$testingScriptContent .= " * APS Dream Home - SQL Injection Protection Testing Script\n";
$testingScriptContent .= " */\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "require_once __DIR__ . '/config/paths.php';\n";
$testingScriptContent .= "require_once APP_PATH . '/Security/SQLInjectionDetector.php';\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "echo '🗄️ APS DREAM HOME - SQL INJECTION PROTECTION TESTING\\n';\n";
$testingScriptContent .= "echo '==========================================\\n\\n';\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "\$detector = App\\Security\\SQLInjectionDetector::getInstance();\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "// Test cases\n";
$testingScriptContent .= "\$testCases = [\n";
$testingScriptContent .= "    'normal_input' => ['name' => 'John Doe', 'email' => 'john@example.com'],\n";
$testingScriptContent .= "    'union_attack' => ['id' => \"1 UNION SELECT username, password FROM users--\"],\n";
$testingScriptContent .= "    'comment_attack' => ['query' => \"SELECT * FROM users WHERE id = 1; DROP TABLE users--\"],\n";
$testingScriptContent .= "    'boolean_attack' => ['login' => \"admin' OR '1'='1\"],\n";
$testingScriptContent .= "    'time_attack' => ['search' => \"test'; SELECT SLEEP(5)--\"],\n";
$testingScriptContent .= "    'hex_attack' => ['id' => \"0x414243\"],\n";
$testingScriptContent .= "    'xss_sql_mix' => ['input' => \"<script>alert('xss')</script> UNION SELECT * FROM users--\"]\n";
$testingScriptContent .= "];\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "echo '🔍 Testing SQL Injection Detection:\\n';\n";
$testingScriptContent .= "foreach (\$testCases as \$testName => \$data) {\n";
$testingScriptContent .= "    echo \"Testing \$testName...\\n\";\n";
$testingScriptContent .= "    \n";
$testingScriptContent .= "    \$isDetected = \$detector->detect(\$data);\n";
$testingScriptContent .= "    \$threatLevel = \$detector->getThreatLevel(json_encode(\$data));\n";
$testingScriptContent .= "    \n";
$testingScriptContent .= "    \$status = \$isDetected ? '🚨 DETECTED' : '✅ SAFE';\n";
$testingScriptContent .= "    echo \"  Detection: \$status\\n\";\n";
$testingScriptContent .= "    echo \"  Threat Level: \$threatLevel\\n\";\n";
$testingScriptContent .= "    \n";
$testingScriptContent .= "    if (\$isDetected) {\n";
$testingScriptContent .= "        \$detector->logAttempt(json_encode(\$data), \$threatLevel);\n";
$testingScriptContent .= "    }\n";
$testingScriptContent .= "    echo \"\\n\";\n";
$testingScriptContent .= "}\n";
$testingScriptContent .= "\n";
$testingScriptContent .= "echo '🎉 SQL injection protection testing completed!\\n';\n";

if (file_put_contents($testingScriptFile, $testingScriptContent)) {
    echo "   ✅ SQL injection testing script created: test_sql_injection_protection.php\n";
    $securityResults['sql_injection_testing_script'] = 'created';
    $successfulImplementations++;
} else {
    echo "   ❌ Failed to create SQL injection testing script\n";
    $securityResults['sql_injection_testing_script'] = 'failed';
}
$totalImplementations++;

// Summary
echo "\n==========================================\n";
echo "📊 SQL INJECTION PROTECTION SUMMARY\n";
echo "==========================================\n";

$successRate = round(($successfulImplementations / $totalImplementations) * 100, 1);
echo "📊 TOTAL IMPLEMENTATIONS: $totalImplementations\n";
echo "✅ SUCCESSFUL: $successfulImplementations\n";
echo "📊 SUCCESS RATE: $successRate%\n\n";

echo "🔧 SECURITY IMPLEMENTATION DETAILS:\n";
foreach ($securityResults as $category => $result) {
    $icon = $result === 'created' ? '✅' : ($result === 'failed' ? '❌' : '⚠️');
    echo "📋 $category: $result\n";
}

if ($successRate >= 80) {
    echo "\n🎉 SQL INJECTION PROTECTION: EXCELLENT!\n";
} elseif ($successRate >= 60) {
    echo "\n✅ SQL INJECTION PROTECTION: GOOD!\n";
} else {
    echo "\n⚠️  SQL INJECTION PROTECTION: NEEDS IMPROVEMENT\n";
}

echo "\n🚀 SQL injection protection implemented successfully!\n";
echo "📊 Ready for next security step: XSS Protection\n";
?>
