<?php
// Auto-generated by Cascade: proxy to the actual SessionManager class.
// This file resolves the 'Critical system file missing: session_manager.php' error.
// If your application expects a class here, ensure it matches the real implementation.

require_once __DIR__ . '/../../includes/classes/SessionManager.php';
