<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title ?? 'Payment Receipt'; ?></title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        .receipt-header { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }
        .receipt-title { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .company-info { margin-top: 10px; font-size: 14px; color: #7f8c8d; }
        .receipt-details { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .customer-info, .payment-info { width: 48%; }
        .info-group { margin-bottom: 15px; }
        .label { font-weight: bold; display: block; margin-bottom: 5px; color: #7f8c8d; font-size: 12px; text-transform: uppercase; }
        .value { font-size: 16px; }
        .amount-box { background: #f8f9fa; border: 1px solid #e9ecef; padding: 20px; text-align: center; margin-bottom: 30px; border-radius: 5px; }
        .amount-label { font-size: 14px; color: #7f8c8d; margin-bottom: 5px; }
        .amount-value { font-size: 32px; font-weight: bold; color: #27ae60; }
        .footer { text-align: center; font-size: 12px; color: #95a5a6; margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; }
        .print-btn { display: block; width: 100%; padding: 10px; background: #3498db; color: white; border: none; cursor: pointer; text-align: center; font-size: 16px; margin-top: 20px; text-decoration: none; border-radius: 5px; }
        @media print {
            .print-btn { display: none; }
            body { padding: 0; }
            .amount-box { border: 1px solid #ccc; }
        }
    </style>
</head>
<body>
    <div class="receipt-header">
        <div class="receipt-title">PAYMENT RECEIPT</div>
        <div class="company-info">
            APS Dream Home<br>
            Real Estate & Developers
        </div>
    </div>

    <div class="receipt-details">
        <div class="customer-info">
            <div class="info-group">
                <span class="label">Received From</span>
                <span class="value"><?php echo htmlspecialchars($payment['customer_name'] ?? 'N/A'); ?></span>
            </div>
            <div class="info-group">
                <span class="label">Customer Contact</span>
                <span class="value">
                    <?php echo htmlspecialchars($payment['customer_mobile'] ?? 'N/A'); ?><br>
                    <?php echo htmlspecialchars($payment['customer_email'] ?? ''); ?>
                </span>
            </div>
        </div>
        <div class="payment-info">
            <div class="info-group">
                <span class="label">Receipt No</span>
                <span class="value"><?php echo htmlspecialchars($payment['transaction_id'] ?? 'N/A'); ?></span>
            </div>
            <div class="info-group">
                <span class="label">Date</span>
                <span class="value"><?php echo date('d M Y, h:i A', strtotime($payment['payment_date'])); ?></span>
            </div>
            <div class="info-group">
                <span class="label">Payment Method</span>
                <span class="value"><?php echo ucwords(str_replace('_', ' ', $payment['payment_method'])); ?></span>
            </div>
        </div>
    </div>

    <div class="amount-box">
        <div class="amount-label">Amount Received</div>
        <div class="amount-value">₹<?php echo number_format($payment['amount'], 2); ?></div>
        <div style="margin-top: 5px; font-size: 14px; color: #7f8c8d;">
            <?php echo ucwords(str_replace('_', ' ', $payment['payment_type'])); ?> Payment
        </div>
    </div>

    <?php if (!empty($payment['notes'])): ?>
    <div class="info-group">
        <span class="label">Description / Notes</span>
        <span class="value"><?php echo nl2br(htmlspecialchars($payment['notes'])); ?></span>
    </div>
    <?php endif; ?>

    <div class="footer">
        <p>This is a computer generated receipt and does not require a physical signature.</p>
        <p>Generated by: <?php echo htmlspecialchars($payment['created_by_name'] ?? 'System'); ?> on <?php echo date('d M Y h:i A'); ?></p>
    </div>

    <a href="javascript:window.print()" class="print-btn">Print Receipt</a>
</body>
</html>
