<?php
/**
 * Advanced Features Migration - Complete
 * Creates tables for: Advanced Search, Wishlist, EMI, Site Visits, Alerts, SEO, Modern UI
 * Created: Auto-generated by Cascade - May 2026
 */

require_once __DIR__ . '/../../vendor/autoload.php';

use App\Core\Database\Database;

echo "🚀 Starting Advanced Features Migration...\n\n";

try {
    $db = Database::getInstance();
    $pdo = $db->getConnection();
    
    // 1. Search Indices (for Advanced Search)
    echo "🔍 Creating search_indices table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS search_indices (
        id INT AUTO_INCREMENT PRIMARY KEY,
        entity_type VARCHAR(50) NOT NULL,
        entity_id INT NOT NULL,
        search_text TEXT NOT NULL,
        search_keywords JSON NULL,
        location_data JSON NULL,
        price_range_min DECIMAL(15,2) NULL,
        price_range_max DECIMAL(15,2) NULL,
        area_range_min DECIMAL(10,2) NULL,
        area_range_max DECIMAL(10,2) NULL,
        attributes JSON NULL,
        popularity_score INT DEFAULT 0,
        last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_entity (entity_type, entity_id),
        FULLTEXT INDEX idx_search (search_text)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 2. Saved Searches
    echo "💾 Creating saved_searches table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS saved_searches (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        name VARCHAR(100) NOT NULL,
        search_criteria JSON NOT NULL,
        alert_enabled TINYINT(1) DEFAULT 1,
        alert_frequency ENUM('daily', 'weekly', 'instant') DEFAULT 'daily',
        last_alert_sent TIMESTAMP NULL,
        result_count INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_alerts (alert_enabled, alert_frequency)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 3. Search Suggestions
    echo "💡 Creating search_suggestions table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS search_suggestions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        query VARCHAR(255) NOT NULL,
        suggestion_type ENUM('location', 'property_type', 'amenity', 'price_range') NOT NULL,
        result_count INT DEFAULT 0,
        search_count INT DEFAULT 1,
        last_searched TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_query (query),
        INDEX idx_type (suggestion_type),
        INDEX idx_count (search_count)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 4. Search Logs
    echo "📝 Creating search_logs table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS search_logs (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NULL,
        session_id VARCHAR(64) NULL,
        search_query TEXT NULL,
        filters_applied JSON NULL,
        results_count INT DEFAULT 0,
        clicked_results JSON NULL,
        search_duration_ms INT NULL,
        ip_address VARCHAR(45) NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_created (created_at),
        INDEX idx_query (search_query(255))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 5. Wishlists
    echo "❤️ Creating wishlists table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS wishlists (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        property_id INT NOT NULL,
        notes TEXT NULL,
        priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_wish (user_id, property_id),
        INDEX idx_user (user_id),
        INDEX idx_property (property_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 6. Recently Viewed
    echo "👁️ Creating recently_viewed table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS recently_viewed (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        property_id INT NOT NULL,
        view_count INT DEFAULT 1,
        last_viewed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_view (user_id, property_id),
        INDEX idx_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 7. Price Alerts
    echo "💰 Creating price_alerts table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS price_alerts (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        property_id INT NOT NULL,
        target_price DECIMAL(15,2) NOT NULL,
        alert_type ENUM('below', 'above', 'drop_percent') DEFAULT 'below',
        drop_percent INT NULL,
        is_active TINYINT(1) DEFAULT 1,
        triggered_at TIMESTAMP NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_active (is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 8. EMI Calculations
    echo "📊 Creating emi_calculations table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS emi_calculations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NULL,
        property_id INT NULL,
        principal_amount DECIMAL(15,2) NOT NULL,
        interest_rate DECIMAL(5,2) NOT NULL,
        tenure_years INT NOT NULL,
        emi_amount DECIMAL(15,2) NOT NULL,
        total_interest DECIMAL(15,2) NOT NULL,
        total_payment DECIMAL(15,2) NOT NULL,
        bank_code VARCHAR(20) NULL,
        calculation_data JSON NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_property (property_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 9. Bank Interest Rates
    echo "🏦 Creating bank_interest_rates table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS bank_interest_rates (
        id INT AUTO_INCREMENT PRIMARY KEY,
        bank_code VARCHAR(20) NOT NULL UNIQUE,
        bank_name VARCHAR(100) NOT NULL,
        rate DECIMAL(5,2) NOT NULL,
        max_tenure INT DEFAULT 30,
        processing_fee_percent DECIMAL(5,2) DEFAULT 0.5,
        min_loan_amount DECIMAL(15,2) DEFAULT 100000,
        max_loan_amount DECIMAL(15,2) DEFAULT 100000000,
        is_active TINYINT(1) DEFAULT 1,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 10. Payment Plans
    echo "💳 Creating payment_plans table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS payment_plans (
        id INT AUTO_INCREMENT PRIMARY KEY,
        property_id INT NOT NULL,
        plan_name VARCHAR(100) NOT NULL,
        plan_type ENUM('construction', 'possession', 'custom') NOT NULL,
        total_amount DECIMAL(15,2) NOT NULL,
        down_payment_percent DECIMAL(5,2) DEFAULT 20,
        number_of_installments INT NOT NULL,
        installment_frequency ENUM('monthly', 'quarterly', 'milestone') DEFAULT 'milestone',
        interest_applicable TINYINT(1) DEFAULT 0,
        interest_rate DECIMAL(5,2) NULL,
        description TEXT NULL,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_property (property_id),
        INDEX idx_active (is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 11. Payment Plan Milestones
    echo "📅 Creating payment_plan_milestones table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS payment_plan_milestones (
        id INT AUTO_INCREMENT PRIMARY KEY,
        plan_id INT NOT NULL,
        milestone_order INT NOT NULL,
        milestone_name VARCHAR(100) NOT NULL,
        percentage DECIMAL(5,2) NOT NULL,
        amount DECIMAL(15,2) NOT NULL,
        due_date DATE NULL,
        description TEXT NULL,
        FOREIGN KEY (plan_id) REFERENCES payment_plans(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 12. Site Visits
    echo "🏠 Creating site_visits table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS site_visits (
        id INT AUTO_INCREMENT PRIMARY KEY,
        property_id INT NOT NULL,
        lead_id INT NULL,
        user_id INT NULL,
        visitor_name VARCHAR(100) NOT NULL,
        visitor_phone VARCHAR(20) NOT NULL,
        visitor_email VARCHAR(100) NULL,
        visit_date DATE NOT NULL,
        visit_time TIME NOT NULL,
        duration_minutes INT DEFAULT 60,
        visit_type ENUM('site_visit', 'virtual_tour', 'office_meeting', 'video_call') DEFAULT 'site_visit',
        status ENUM('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show') DEFAULT 'scheduled',
        assigned_to INT NULL,
        pickup_required TINYINT(1) DEFAULT 0,
        pickup_location VARCHAR(255) NULL,
        notes TEXT NULL,
        feedback TEXT NULL,
        rating INT NULL,
        reminder_sent TINYINT(1) DEFAULT 0,
        confirmation_sent TINYINT(1) DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_property (property_id),
        INDEX idx_date (visit_date),
        INDEX idx_status (status),
        INDEX idx_assigned (assigned_to)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 13. Site Availability
    echo "📆 Creating site_availability table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS site_availability (
        id INT AUTO_INCREMENT PRIMARY KEY,
        property_id INT NOT NULL,
        available_date DATE NOT NULL,
        start_time TIME NOT NULL,
        end_time TIME NOT NULL,
        slot_duration INT DEFAULT 60,
        max_visits_per_slot INT DEFAULT 1,
        is_blocked TINYINT(1) DEFAULT 0,
        block_reason VARCHAR(255) NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY unique_slot (property_id, available_date, start_time),
        INDEX idx_date (available_date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 14. Property Alerts
    echo "🔔 Creating property_alerts table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS property_alerts (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        alert_name VARCHAR(100) NULL,
        property_type VARCHAR(50) NULL,
        location VARCHAR(100) NULL,
        city VARCHAR(50) NULL,
        min_price DECIMAL(15,2) NULL,
        max_price DECIMAL(15,2) NULL,
        min_area DECIMAL(10,2) NULL,
        max_area DECIMAL(10,2) NULL,
        bedrooms INT NULL,
        furnishing VARCHAR(50) NULL,
        amenities JSON NULL,
        frequency ENUM('instant', 'daily', 'weekly') DEFAULT 'daily',
        last_sent TIMESTAMP NULL,
        is_active TINYINT(1) DEFAULT 1,
        total_matches INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_active (is_active),
        INDEX idx_frequency (frequency)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 15. Alert Matches
    echo "🎯 Creating alert_matches table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS alert_matches (
        id INT AUTO_INCREMENT PRIMARY KEY,
        alert_id INT NOT NULL,
        property_id INT NOT NULL,
        match_score DECIMAL(3,2) DEFAULT 1.00,
        notification_sent TINYINT(1) DEFAULT 0,
        sent_at TIMESTAMP NULL,
        clicked TINYINT(1) DEFAULT 0,
        clicked_at TIMESTAMP NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY unique_match (alert_id, property_id),
        FOREIGN KEY (alert_id) REFERENCES property_alerts(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 16. SEO Meta Tags
    echo "🌐 Creating seo_meta_tags table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS seo_meta_tags (
        id INT AUTO_INCREMENT PRIMARY KEY,
        entity_type VARCHAR(50) NOT NULL,
        entity_id INT NOT NULL,
        page_url VARCHAR(255) NULL,
        title VARCHAR(70) NULL,
        description VARCHAR(160) NULL,
        keywords VARCHAR(255) NULL,
        og_title VARCHAR(100) NULL,
        og_description VARCHAR(200) NULL,
        og_image VARCHAR(255) NULL,
        twitter_card VARCHAR(50) DEFAULT 'summary_large_image',
        canonical_url VARCHAR(255) NULL,
        robots_meta VARCHAR(50) DEFAULT 'index,follow',
        schema_markup JSON NULL,
        priority DECIMAL(2,1) DEFAULT 0.5,
        change_frequency ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never') DEFAULT 'weekly',
        is_auto_generated TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_entity (entity_type, entity_id),
        INDEX idx_url (page_url)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 17. URL Redirects
    echo "↪️ Creating url_redirects table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS url_redirects (
        id INT AUTO_INCREMENT PRIMARY KEY,
        old_url VARCHAR(255) NOT NULL,
        new_url VARCHAR(255) NOT NULL,
        redirect_type ENUM('301', '302', '307') DEFAULT '301',
        hit_count INT DEFAULT 0,
        last_accessed TIMESTAMP NULL,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY unique_old_url (old_url),
        INDEX idx_active (is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 18. User Theme Preferences
    echo "🎨 Creating user_theme_preferences table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS user_theme_preferences (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        user_type ENUM('admin', 'employee', 'associate', 'customer') DEFAULT 'admin',
        theme_preset VARCHAR(20) DEFAULT 'light',
        is_dark_mode TINYINT(1) DEFAULT 0,
        sidebar_collapsed TINYINT(1) DEFAULT 0,
        compact_mode TINYINT(1) DEFAULT 0,
        custom_colors JSON NULL,
        font_size ENUM('small', 'normal', 'large') DEFAULT 'normal',
        animations_enabled TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_user (user_id, user_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 19. User Quick Actions
    echo "⚡ Creating user_quick_actions table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS user_quick_actions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        user_type ENUM('admin', 'employee', 'associate', 'customer') DEFAULT 'admin',
        action_name VARCHAR(50) NOT NULL,
        action_icon VARCHAR(50) NULL,
        action_url VARCHAR(255) NOT NULL,
        display_order INT DEFAULT 0,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user (user_id, user_type),
        INDEX idx_order (display_order)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // Seed default bank rates
    echo "\n🌱 Seeding bank interest rates...\n";
    $banks = [
        ['sbi', 'State Bank of India', 8.50, 30],
        ['hdfc', 'HDFC Bank', 8.60, 30],
        ['icici', 'ICICI Bank', 8.65, 30],
        ['axis', 'Axis Bank', 8.70, 30],
        ['pnb', 'Punjab National Bank', 8.55, 30],
        ['bob', 'Bank of Baroda', 8.50, 30],
        ['lic', 'LIC Housing Finance', 8.50, 30],
    ];
    
    $stmt = $pdo->prepare("INSERT IGNORE INTO bank_interest_rates (bank_code, bank_name, rate, max_tenure) VALUES (?, ?, ?, ?)");
    foreach ($banks as $bank) {
        $stmt->execute($bank);
    }
    
    echo "\n✅ All tables created successfully!\n";
    echo "📊 Migration Summary:\n";
    echo "   - Search Tables: 4 (indices, saved_searches, suggestions, logs)\n";
    echo "   - Customer Tables: 3 (wishlists, recently_viewed, price_alerts)\n";
    echo "   - Finance Tables: 4 (emi, bank_rates, payment_plans, milestones)\n";
    echo "   - Operations Tables: 2 (site_visits, site_availability)\n";
    echo "   - Alert Tables: 2 (property_alerts, alert_matches)\n";
    echo "   - SEO Tables: 2 (seo_meta_tags, url_redirects)\n";
    echo "   - UI Tables: 2 (theme_prefs, quick_actions)\n";
    echo "\n🎉 Total: 19 new tables created!\n";
    
} catch (\Exception $e) {
    echo "\n❌ Error: " . $e->getMessage() . "\n";
    exit(1);
}
