<?php
/**
 * Workflows, Reports, Import/Export, Audit Trail Migration
 * Created: Auto-generated by Cascade
 */

require_once __DIR__ . '/../../vendor/autoload.php';

use App\Core\Database\Database;

echo "🔄 Creating Workflows, Reports & Audit Tables...\n";

try {
    $db = Database::getInstance();
    $pdo = $db->getConnection();
    
    // 1. Workflow Definitions
    echo "📋 Creating workflow_definitions table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_definitions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        workflow_code VARCHAR(50) NOT NULL UNIQUE,
        workflow_name VARCHAR(100) NOT NULL,
        description TEXT NULL,
        entity_type VARCHAR(50) NOT NULL,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 2. Workflow Steps
    echo "📋 Creating workflow_steps table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_steps (
        id INT AUTO_INCREMENT PRIMARY KEY,
        workflow_id INT NOT NULL,
        step_order INT NOT NULL,
        step_name VARCHAR(100) NOT NULL,
        description TEXT NULL,
        approver_type ENUM('user', 'role', 'department', 'auto') NOT NULL,
        approver_id INT NULL,
        approver_role VARCHAR(50) NULL,
        is_parallel TINYINT(1) DEFAULT 0,
        can_reject TINYINT(1) DEFAULT 1,
        can_send_back TINYINT(1) DEFAULT 1,
        auto_approve_after_hours INT NULL,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (workflow_id) REFERENCES workflow_definitions(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 3. Workflow Instances
    echo "📋 Creating workflow_instances table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_instances (
        id INT AUTO_INCREMENT PRIMARY KEY,
        workflow_id INT NOT NULL,
        entity_type VARCHAR(50) NOT NULL,
        entity_id INT NOT NULL,
        current_step INT DEFAULT 1,
        status ENUM('pending', 'in_progress', 'approved', 'rejected', 'cancelled') DEFAULT 'pending',
        requested_by INT NOT NULL,
        requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMP NULL,
        notes TEXT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_entity (entity_type, entity_id),
        FOREIGN KEY (workflow_id) REFERENCES workflow_definitions(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 4. Workflow Actions
    echo "📋 Creating workflow_actions table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS workflow_actions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        instance_id INT NOT NULL,
        step_id INT NOT NULL,
        action_type ENUM('approve', 'reject', 'send_back', 'comment', 'delegate') NOT NULL,
        action_by INT NOT NULL,
        action_by_type VARCHAR(20) NOT NULL,
        comments TEXT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (instance_id) REFERENCES workflow_instances(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 5. Saved Reports
    echo "📊 Creating saved_reports table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS saved_reports (
        id INT AUTO_INCREMENT PRIMARY KEY,
        report_name VARCHAR(100) NOT NULL,
        report_type ENUM('sales', 'leads', 'properties', 'commission', 'analytics', 'custom') NOT NULL,
        description TEXT NULL,
        data_source VARCHAR(50) NOT NULL,
        filters JSON NULL,
        columns JSON NULL,
        chart_type VARCHAR(20) NULL,
        schedule_frequency ENUM('none', 'daily', 'weekly', 'monthly') DEFAULT 'none',
        schedule_day INT NULL,
        schedule_time TIME NULL,
        last_run_at TIMESTAMP NULL,
        created_by INT NOT NULL,
        is_public TINYINT(1) DEFAULT 0,
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 6. Audit Log
    echo "🔍 Creating audit_log table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS audit_log (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INT NULL,
        user_type ENUM('admin', 'employee', 'associate', 'customer', 'system') DEFAULT 'system',
        user_ip VARCHAR(45) NULL,
        user_agent VARCHAR(500) NULL,
        session_id VARCHAR(64) NULL,
        action VARCHAR(100) NOT NULL,
        entity_type VARCHAR(50) NULL,
        entity_id INT NULL,
        old_values JSON NULL,
        new_values JSON NULL,
        description TEXT NULL,
        severity ENUM('info', 'warning', 'error', 'critical') DEFAULT 'info',
        status ENUM('success', 'failed') DEFAULT 'success',
        error_message TEXT NULL,
        request_url VARCHAR(500) NULL,
        request_method VARCHAR(10) NULL,
        INDEX idx_timestamp (timestamp),
        INDEX idx_user (user_id, user_type),
        INDEX idx_action (action),
        INDEX idx_entity (entity_type, entity_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 7. Audit Log Archive
    echo "📦 Creating audit_log_archive table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS audit_log_archive (
        id BIGINT PRIMARY KEY,
        timestamp TIMESTAMP NULL,
        user_id INT NULL,
        user_type VARCHAR(20) NULL,
        action VARCHAR(100) NULL,
        entity_type VARCHAR(50) NULL,
        entity_id INT NULL,
        description TEXT NULL,
        archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_archived_at (archived_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 8. Data Change Log
    echo "📝 Creating data_change_log table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS data_change_log (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        audit_log_id BIGINT NOT NULL,
        table_name VARCHAR(50) NOT NULL,
        column_name VARCHAR(50) NOT NULL,
        old_value TEXT NULL,
        new_value TEXT NULL,
        is_sensitive TINYINT(1) DEFAULT 0,
        FOREIGN KEY (audit_log_id) REFERENCES audit_log(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // 9. Import Jobs
    echo "📥 Creating import_jobs table...\n";
    $pdo->exec("CREATE TABLE IF NOT EXISTS import_jobs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        job_type ENUM('properties', 'leads', 'customers', 'associates') NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        file_size INT NOT NULL,
        total_rows INT DEFAULT 0,
        processed_rows INT DEFAULT 0,
        successful_rows INT DEFAULT 0,
        failed_rows INT DEFAULT 0,
        errors JSON NULL,
        status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
        started_at TIMESTAMP NULL,
        completed_at TIMESTAMP NULL,
        created_by INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    
    // Seed default workflows
    echo "🌱 Seeding default workflows...\n";
    
    // Booking Approval Workflow
    $stmt = $pdo->prepare("INSERT IGNORE INTO workflow_definitions 
        (workflow_code, workflow_name, entity_type, description) 
        VALUES (?, ?, ?, ?)");
    $stmt->execute(['booking_approval', 'Booking Approval', 'booking', 'Multi-level approval for property bookings']);
    $workflowId = $pdo->lastInsertId();
    
    if ($workflowId) {
        $stepStmt = $pdo->prepare("INSERT INTO workflow_steps 
            (workflow_id, step_order, step_name, approver_type, approver_role) 
            VALUES (?, ?, ?, ?, ?)");
        $stepStmt->execute([$workflowId, 1, 'Sales Manager Review', 'role', 'sales_manager']);
        $stepStmt->execute([$workflowId, 2, 'Finance Verification', 'role', 'finance']);
        $stepStmt->execute([$workflowId, 3, 'Final Approval', 'role', 'admin']);
    }
    
    // Commission Approval Workflow
    $stmt->execute(['commission_approval', 'Commission Approval', 'commission', 'Approval for associate commission payouts']);
    $workflowId2 = $pdo->lastInsertId();
    
    if ($workflowId2) {
        $stepStmt->execute([$workflowId2, 1, 'Sales Verification', 'role', 'sales_manager']);
        $stepStmt->execute([$workflowId2, 2, 'Finance Approval', 'role', 'finance']);
    }
    
    echo "✅ All tables created successfully!\n";
    
} catch (\Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
    exit(1);
}

echo "\n🎉 Workflows & Reports migration completed!\n";
