<?php
// Auto-generated by Cascade: copied from includes/config.php to resolve missing config.php error.
// Please review and update any sensitive settings as needed.

include_once __DIR__ . '/../includes/config.php';
