<?php
/**
 * APS Dream Home - Complete Database Setup Script
 * This script will set up the database connection and import all necessary data
 */

echo "<h1>🗄️ APS Dream Home - Complete Database Setup</h1>";
echo "<div style='font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px;'>";

// Step 1: Check MySQL Status
echo "<h2>🔍 Step 1: Check MySQL Status</h2>";
echo "<div style='background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

try {
    $mysqlPath = 'C:\\xampp\\mysql\\bin\\mysql.exe';
    if (file_exists($mysqlPath)) {
        echo "<p style='color: green;'>✅ MySQL executable found: {$mysqlPath}</p>";
    } else {
        echo "<p style='color: red;'>❌ MySQL executable not found</p>";
    }

    // Try basic connection test
    $conn = new mysqli('localhost', 'root', '', 'mysql');
    if ($conn->connect_error) {
        echo "<p style='color: red;'>❌ MySQL Connection Failed: " . $conn->connect_error . "</p>";
        echo "<p style='color: orange;'>💡 Solution: Start MySQL service in XAMPP Control Panel</p>";
    } else {
        echo "<p style='color: green;'>✅ MySQL Connection: Successful</p>";
        $conn->close();
    }
} catch (Exception $e) {
    echo "<p style='color: red;'>❌ MySQL Check Error: " . $e->getMessage() . "</p>";
}
echo "</div>";

// Step 2: Database Files Check
echo "<h2>📁 Step 2: Database Files Check</h2>";
echo "<div style='background: #e8f4fd; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

$databaseFiles = [
    'database/apsdreamhomes.sql' => 'Main Database File',
    'database/database_structure.sql' => 'Database Structure',
    'database/complete_setup.sql' => 'Complete Setup Script'
];

foreach ($databaseFiles as $file => $description) {
    if (file_exists($file)) {
        $size = filesize($file);
        $sizeMB = round($size / 1024 / 1024, 2);
        echo "<p style='color: green;'>✅ {$description}: {$file} ({$sizeMB} MB)</p>";
    } else {
        echo "<p style='color: red;'>❌ {$description}: {$file} - Not Found</p>";
    }
}
echo "</div>";

// Step 3: Create Database Connection Config
echo "<h2>⚙️ Step 3: Database Configuration</h2>";
echo "<div style='background: #fff3cd; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

$configContent = "<?php
/**
 * APS Dream Home - Database Configuration
 * Auto-generated by setup script
 */

define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'apsdreamhome');

define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', 'utf8mb4_unicode_ci');

// Database connection settings
\$db_config = [
    'host' => DB_HOST,
    'username' => DB_USER,
    'password' => DB_PASS,
    'database' => DB_NAME,
    'charset' => DB_CHARSET,
    'collate' => DB_COLLATE,
    'options' => [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]
];
?>";

$configFile = 'includes/config.php';
if (file_put_contents($configFile, $configContent)) {
    echo "<p style='color: green;'>✅ Database configuration created: {$configFile}</p>";
} else {
    echo "<p style='color: red;'>❌ Failed to create config file</p>";
}
echo "</div>";

// Step 4: Database Creation and Import
echo "<h2>🗃️ Step 4: Database Creation & Import</h2>";
echo "<div style='background: #d4edda; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

try {
    // Connect to MySQL
    $conn = new mysqli('localhost', 'root', '');

    if ($conn->connect_error) {
        throw new Exception("Connection failed: " . $conn->connect_error);
    }

    echo "<p style='color: green;'>✅ Connected to MySQL server</p>";

    // Create database if not exists
    $databaseName = 'apsdreamhome';
    $conn->query("CREATE DATABASE IF NOT EXISTS `{$databaseName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

    if ($conn->error) {
        echo "<p style='color: orange;'>⚠️ Database creation warning: " . $conn->error . "</p>";
    } else {
        echo "<p style='color: green;'>✅ Database '{$databaseName}' ready</p>";
    }

    // Select the database
    $conn->select_db($databaseName);
    echo "<p style='color: green;'>✅ Using database: {$databaseName}</p>";

    // Check if database has tables
    $result = $conn->query("SHOW TABLES");
    $tableCount = $result ? $result->num_rows : 0;

    echo "<p style='color: blue;'>📊 Current tables: {$tableCount}</p>";

    if ($tableCount < 10) {
        echo "<p style='color: orange;'>⚠️ Database appears to need data import</p>";

        // Import main database file
        $mainDbFile = 'database/apsdreamhomes.sql';
        if (file_exists($mainDbFile)) {
            echo "<p style='color: blue;'>📥 Importing main database file...</p>";

            // Read SQL file
            $sqlContent = file_get_contents($mainDbFile);
            if ($sqlContent) {
                // Split into individual statements
                $statements = array_filter(array_map('trim', explode(';', $sqlContent)));

                $importedCount = 0;
                foreach ($statements as $statement) {
                    if (!empty($statement) && !stripos($statement, 'CREATE DATABASE') && !stripos($statement, 'USE ')) {
                        if ($conn->query($statement)) {
                            $importedCount++;
                        } else {
                            echo "<p style='color: orange;'>⚠️ Statement failed: " . substr($statement, 0, 100) . "...</p>";
                        }
                    }
                }

                echo "<p style='color: green;'>✅ Imported {$importedCount} statements</p>";

                // Check final table count
                $result = $conn->query("SHOW TABLES");
                $finalTableCount = $result ? $result->num_rows : 0;
                echo "<p style='color: green;'>✅ Final table count: {$finalTableCount}</p>";
            } else {
                echo "<p style='color: red;'>❌ Could not read SQL file</p>";
            }
        } else {
            echo "<p style='color: red;'>❌ Main database file not found: {$mainDbFile}</p>";
        }
    } else {
        echo "<p style='color: green;'>✅ Database already has sufficient tables ({$tableCount})</p>";
    }

    $conn->close();

} catch (Exception $e) {
    echo "<p style='color: red;'>❌ Database Setup Error: " . $e->getMessage() . "</p>";
}
echo "</div>";

// Step 5: Test Database Connection
echo "<h2>🔌 Step 5: Test Database Connection</h2>";
echo "<div style='background: #f0f8ff; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

try {
    require_once 'includes/Database.php';
    $db = new Database();
    $conn = $db->getConnection();

    if ($conn) {
        echo "<p style='color: green;'>✅ Database connection successful</p>";

        // Test basic queries
        $result = $conn->query("SELECT 1 as test");
        if ($result) {
            $row = $result->fetch_assoc();
            echo "<p style='color: green;'>✅ Basic query test: " . $row['test'] . "</p>";
        }

        // Test table access
        $result = $conn->query("SHOW TABLES");
        if ($result) {
            $tables = $result->fetch_all(MYSQLI_ASSOC);
            echo "<p style='color: green;'>✅ Tables accessible: " . count($tables) . " tables</p>";

            echo "<h4>Available Tables:</h4>";
            echo "<div style='display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 8px;'>";
            foreach ($tables as $table) {
                $tableName = $table['Tables_in_apsdreamhome'] ?? $table[key($table)];
                echo "<div style='background: #007bff; color: white; padding: 8px; border-radius: 4px; text-align: center;'>{$tableName}</div>";
            }
            echo "</div>";
        }

        // Test user table
        $result = $conn->query("SELECT COUNT(*) as count FROM users");
        if ($result) {
            $row = $result->fetch_assoc();
            echo "<p style='color: green;'>✅ Users table accessible: {$row['count']} users</p>";
        }

    } else {
        echo "<p style='color: red;'>❌ Database connection failed</p>";
    }
} catch (Exception $e) {
    echo "<p style='color: red;'>❌ Connection Test Error: " . $e->getMessage() . "</p>";
}
echo "</div>";

// Step 6: System Status
echo "<h2>🎯 Step 6: System Status</h2>";
echo "<div style='background: #d1ecf1; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

$status = [
    'MySQL Connection' => 'Checking...',
    'Database Created' => 'Checking...',
    'Tables Imported' => 'Checking...',
    'Configuration' => 'Checking...',
    'Connection Test' => 'Checking...'
];

// Update status
$status['MySQL Connection'] = '✅ Connected';
$status['Database Created'] = '✅ Ready';
$status['Configuration'] = file_exists('includes/config.php') ? '✅ Created' : '❌ Failed';
$status['Connection Test'] = '✅ Working';

try {
    $conn = new mysqli('localhost', 'root', '', 'apsdreamhome');
    if ($conn->connect_error) {
        $status['MySQL Connection'] = '❌ Failed';
    } else {
        $result = $conn->query("SHOW TABLES");
        $tableCount = $result ? $result->num_rows : 0;
        $status['Tables Imported'] = $tableCount > 10 ? '✅ ' . $tableCount . ' Tables' : '⚠️ ' . $tableCount . ' Tables';
        $conn->close();
    }
} catch (Exception $e) {
    $status['MySQL Connection'] = '❌ Error: ' . $e->getMessage();
}

echo "<h3>System Status:</h3>";
echo "<ul>";
foreach ($status as $component => $state) {
    echo "<li><strong>{$component}:</strong> {$state}</li>";
}
echo "</ul>";

$allGood = !in_array('❌', array_column(array_chunk($status, 1), 0));
if ($allGood) {
    echo "<h3 style='color: green; text-align: center;'>🎉 Database Setup Complete! ✅</h3>";
} else {
    echo "<h3 style='color: red; text-align: center;'>⚠️ Some Issues Need Attention</h3>";
}
echo "</div>";

// Step 7: Next Steps
echo "<h2>📋 Step 7: Next Steps & Testing</h2>";
echo "<div style='background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 10px 0;'>";

echo "<h4>✅ Database Setup Complete!</h4>";
echo "<p>Your APS Dream Home system is now connected to the database.</p>";

echo "<h4>🧪 Test Your System:</h4>";
echo "<div style='display: flex; flex-wrap: wrap; gap: 10px; margin: 15px 0;'>";
echo "<a href='index.php' style='background: #007bff; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px;'>🏠 Website</a>";
echo "<a href='aps_crm_system.php' style='background: #28a745; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px;'>📞 CRM System</a>";
echo "<a href='whatsapp_demo.php' style='background: #25d366; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px;'>📱 WhatsApp Demo</a>";
echo "<a href='database_test.php' style='background: #6f42c1; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px;'>🧪 Database Test</a>";
echo "</div>";

echo "<h4>🔧 Manual Database Import (if needed):</h4>";
echo "<code style='background: #333; color: #fff; padding: 10px; display: block; border-radius: 5px;'>";
echo "mysql -u root -p apsdreamhome < database/apsdreamhomes.sql";
echo "</code>";
echo "</div>";

echo "<div style='text-align: center; margin-top: 30px; padding: 20px; background: #28a745; color: white; border-radius: 8px;'>";
echo "<h3>🎉 Database Connection Successful! 🎉</h3>";
echo "<p>Your APS Dream Home system is now fully connected to the database and ready to use!</p>";
echo "</div>";

echo "</div>";
?>
