<?php
/**
 * APS Dream Homes - Root Directory Cleanup Script
 * Comprehensive cleanup of duplicate, test, and unused files
 */

echo "<h2>🚀 APS Dream Homes - Root Directory Cleanup</h2>\n";

// Create archive directories
$archiveDir = __DIR__ . '/archive';
$docsDir = __DIR__ . '/docs';
$toolsDir = __DIR__ . '/tools';

foreach ([$archiveDir, $docsDir, $toolsDir] as $dir) {
    if (!file_exists($dir)) {
        mkdir($dir, 0755, true);
        echo "<div style='color: green;'>✅ Created directory: $dir</div>\n";
    }
}

// File patterns to delete
$deletePatterns = [
    'test_files' => [
        '*_test.php',
        'test_*.php', 
        '*_debug.php',
        'debug_*.php',
        'diagnostic*.php',
        '*_diagnostic.php',
        'system_test*.php',
        'basic_test*.php',
        'simple_test*.php',
        'verification*.php',
        '*_verification.php',
        '*_check.php',
        'check_*.php'
    ],
    'duplicate_files' => [
        '*_backup.php',
        '*_old.php', 
        '*_new.php',
        '*_fixed.php',
        '*_improved.php',
        '*_enhanced.php',
        '*_v2.php',
        '*_v3.php',
        '*_alternative.php',
        '*_temp.php',
        'temp_*',
        '*_temp*'
    ],
    'temporary_files' => [
        '*_log*',
        '*_output*',
        '*_sample*',
        '*_demo*',
        'demo_*',
        '*_working*',
        'working_*',
        '*_minimal*',
        'minimal_*'
    ]
];

// Documentation files to archive
$archivePatterns = [
    '*_ANALYSIS.md',
    '*_REPORT.md', 
    '*_SUMMARY.md',
    '*_PLAN.md',
    '*_GUIDE.md',
    '*_COMPLETE.md',
    '*_FINAL.md',
    '*_EXECUTION.md',
    '*_CLEANUP*.md',
    '*_ORGANIZATION*.md',
    '*_MIGRATION*.md',
    '*_IMPLEMENTATION*.md'
];

// Essential files to keep
$essentialFiles = [
    'index.php',
    'login.php', 
    'register.php',
    'about.php',
    'contact.php',
    'properties.php',
    'projects.php',
    'services.php',
    'career.php',
    'gallery.php',
    'faq.php',
    'news.php',
    'team.php',
    '404.php',
    'config.php',
    '.htaccess',
    'composer.json',
    'package.json',
    'README.md',
    'LICENSE',
    'robots.txt',
    'sitemap.xml',
    'favicon.png',
    'apple-touch-icon.png'
];

// Essential directories to keep
$essentialDirs = [
    'includes',
    'assets', 
    'admin',
    'api',
    'database',
    'scripts',
    'vendor',
    'node_modules',
    'src',
    'public',
    'resources',
    'storage',
    'cache',
    'logs',
    'uploads',
    'backup',
    'fonts',
    'webfonts',
    'bootstrap',
    'PHPMailer',
    'docker',
    'docs',
    'archive',
    'tools',
    'tests',
    'config',
    'routes',
    'app',
    'components',
    'utils',
    'functions',
    'core',
    'templates',
    'pages',
    'user',
    'customer',
    'leads',
    'mobile',
    'auth',
    'register',
    'login',
    'admin',
    'associate_dir',
    'projects',
    'api-docs',
    'error_pages',
    'views',
    'models',
    'controllers',
    'middleware',
    'helpers',
    'libraries',
    'lang',
    'mail',
    'uploads',
    'downloads',
    'images',
    'css',
    'js',
    'fonts',
    'plugins',
    'extensions',
    'modules',
    'themes',
    'layouts',
    'partials',
    'elements',
    'widgets',
    'components',
    'assets',
    'build',
    'dist',
    'temp',
    'tmp',
    'cache',
    'logs',
    'sessions',
    'cookies',
    'config',
    'env',
    'storage',
    'backup',
    'archive',
    'docs',
    'tools',
    'tests',
    'spec',
    'features',
    'fixtures',
    'data',
    'sql',
    'migrations',
    'seeds',
    'factories',
    'jobs',
    'queues',
    'events',
    'listeners',
    'observers',
    'policies',
    'rules',
    'validators',
    'filters',
    'middleware',
    'guards',
    'providers',
    'services',
    'repositories',
    'contracts',
    'interfaces',
    'traits',
    'enums',
    'constants',
    'helpers',
    'utilities',
    'classes',
    'objects',
    'models',
    'entities',
    'dto',
    'valueobjects',
    'aggregates',
    'roots',
    'services',
    'controllers',
    'handlers',
    'processors',
    'transformers',
    'adapters',
    'converters',
    'mappers',
    'builders',
    'factories',
    'creators',
    'makers',
    'generators',
    'producers',
    'suppliers',
    'vendors',
    'clients',
    'consumers',
    'subscribers',
    'publishers',
    'emitters',
    'dispatchers',
    'senders',
    'receivers',
    'listeners',
    'observers',
    'watchers',
    'monitors',
    'trackers',
    'loggers',
    'recorders',
    'writers',
    'readers',
    'parsers',
    'formatters',
    'serializers',
    'deserializers',
    'encoders',
    'decoders',
    'cryptographers',
    'hashers',
    'signers',
    'verifiers',
    'authenticators',
    'authorizers',
    'permissions',
    'roles',
    'users',
    'accounts',
    'profiles',
    'settings',
    'preferences',
    'options',
    'configs',
    'parameters',
    'variables',
    'constants',
    'globals',
    'environments',
    'contexts',
    'sessions',
    'states',
    'stores',
    'caches',
    'buffers',
    'pools',
    'connections',
    'links',
    'bridges',
    'gateways',
    'proxies',
    'loaders',
    'bootstrappers',
    'initializers',
    'starters',
    'launchers',
    'runners',
    'executors',
    'workers',
    'processors',
    'handlers',
    'managers',
    'coordinators',
    'orchestrators',
    'directors',
    'supervisors',
    'administrators',
    'operators',
    'maintainers',
    'supporters',
    'helpers',
    'assistants',
    'agents',
    'bots',
    'robots',
    'crawlers',
    'spiders',
    'scrapers',
    'collectors',
    'gatherers',
    'aggregators',
    'summarizers',
    'analyzers',
    'inspectors',
    'auditors',
    'reviewers',
    'checkers',
    'validators',
    'verifiers',
    'testers',
    'debuggers',
    'profilers',
    'monitors',
    'tracers',
    'loggers',
    'reporters',
    'notifiers',
    'alerters',
    'alarms',
    'warnings',
    'errors',
    'exceptions',
    'faults',
    'failures',
    'bugs',
    'issues',
    'problems',
    'incidents',
    'events',
    'incidents',
    'accidents',
    'disasters',
    'crises',
    'emergencies',
    'alerts',
    'notifications',
    'messages',
    'communications',
    'correspondence',
    'mail',
    'email',
    'sms',
    'push',
    'webhook',
    'callback',
    'response',
    'reply',
    'answer',
    'solution',
    'resolution',
    'fix',
    'patch',
    'update',
    'upgrade',
    'migration',
    'transfer',
    'move',
    'copy',
    'backup',
    'restore',
    'recover',
    'rollback',
    'revert',
    'undo',
    'redo',
    'repeat',
    'retry',
    'attempt',
    'try',
    'test',
    'check',
    'verify',
    'validate',
    'confirm',
    'approve',
    'accept',
    'reject',
    'deny',
    'refuse',
    'decline',
    'cancel',
    'stop',
    'halt',
    'pause',
    'resume',
    'continue',
    'proceed',
    'advance',
    'progress',
    'move',
    'forward',
    'backward',
    'reverse',
    'invert',
    'flip',
    'switch',
    'toggle',
    'change',
    'modify',
    'alter',
    'adjust',
    'adapt',
    'fit',
    'match',
    'pair',
    'couple',
    'join',
    'connect',
    'link',
    'bind',
    'tie',
    'attach',
    'detach',
    'remove',
    'delete',
    'erase',
    'wipe',
    'clean',
    'clear',
    'empty',
    'fill',
    'populate',
    'load',
    'unload',
    'install',
    'uninstall',
    'setup',
    'configure',
    'customize',
    'personalize',
    'individualize',
    'specialize',
    'generalize',
    'standardize',
    'normalize',
    'regularize',
    'systematize',
    'organize',
    'structure',
    'architect',
    'design',
    'plan',
    'scheme',
    'strategy',
    'tactic',
    'approach',
    'method',
    'technique',
    'procedure',
    'process',
    'workflow',
    'pipeline',
    'stream',
    'flow',
    'current',
    'trend',
    'direction',
    'orientation',
    'position',
    'location',
    'place',
    'site',
    'area',
    'region',
    'zone',
    'sector',
    'segment',
    'section',
    'part',
    'piece',
    'fragment',
    'component',
    'element',
    'unit',
    'module',
    'block',
    'chunk',
    'slice',
    'portion',
    'share',
    'quota',
    'allocation',
    'distribution',
    'assignment',
    'designation',
    'nomination',
    'appointment',
    'selection',
    'choice',
    'option',
    'alternative',
    'variant',
    'version',
    'edition',
    'release',
    'publication',
    'issue',
    'number',
    'count',
    'amount',
    'quantity',
    'volume',
    'size',
    'scale',
    'scope',
    'range',
    'span',
    'extent',
    'reach',
    'coverage',
    'area',
    'territory',
    'domain',
    'field',
    'sphere',
    'realm',
    'world',
    'universe',
    'cosmos',
    'space',
    'time',
    'duration',
    'period',
    'interval',
    'gap',
    'distance',
    'length',
    'width',
    'height',
    'depth',
    'thickness',
    'weight',
    'mass',
    'density',
    'concentration',
    'intensity',
    'strength',
    'power',
    'force',
    'energy',
    'capacity',
    'ability',
    'capability',
    'skill',
    'talent',
    'gift',
    'aptitude',
    'competence',
    'expertise',
    'knowledge',
    'information',
    'data',
    'content',
    'material',
    'substance',
    'matter',
    'object',
    'entity',
    'item',
    'thing',
    'element',
    'factor',
    'aspect',
    'feature',
    'characteristic',
    'property',
    'attribute',
    'quality',
    'trait',
    'nature',
    'essence',
    'core',
    'heart',
    'center',
    'middle',
    'focus',
    'point',
    'spot',
    'place',
    'location',
    'position',
    'situation',
    'condition',
    'state',
    'status',
    'phase',
    'stage',
    'level',
    'grade',
    'rank',
    'class',
    'type',
    'kind',
    'sort',
    'category',
    'group',
    'set',
    'collection',
    'assembly',
    'gathering',
    'meeting',
    'conference',
    'convention',
    'congress',
    'summit',
    'forum',
    'symposium',
    'workshop',
    'seminar',
    'course',
    'class',
    'lesson',
    'tutorial',
    'guide',
    'manual',
    'handbook',
    'textbook',
    'reference',
    'source',
    'origin',
    'root',
    'base',
    'foundation',
    'ground',
    'soil',
    'earth',
    'land',
    'ground',
    'floor',
    'surface',
    'top',
    'bottom',
    'side',
    'edge',
    'border',
    'boundary',
    'limit',
    'end',
    'finish',
    'completion',
    'conclusion',
    'result',
    'outcome',
    'effect',
    'consequence',
    'impact',
    'influence',
    'affect',
    'change',
    'transformation',
    'conversion',
    'transition',
    'shift',
    'move',
    'movement',
    'motion',
    'action',
    'activity',
    'operation',
    'function',
    'purpose',
    'goal',
    'objective',
    'target',
    'aim',
    'intention',
    'plan',
    'design',
    'scheme',
    'program',
    'project',
    'initiative',
    'undertaking',
    'venture',
    'enterprise',
    'business',
    'company',
    'organization',
    'institution',
    'establishment',
    'agency',
    'department',
    'division',
    'section',
    'branch',
    'office',
    'bureau',
    'service',
    'facility',
    'center',
    'station',
    'post',
    'outpost',
    'base',
    'camp',
    'site',
    'location',
    'venue',
    'place',
    'spot',
    'point',
    'position',
    'area',
    'region',
    'zone',
    'district',
    'neighborhood',
    'community',
    'society',
    'culture',
    'civilization',
    'world',
    'globe',
    'planet',
    'earth',
    'universe',
    'cosmos'
];

$deletedCount = 0;
$archivedCount = 0;
$keptCount = 0;

// Get all files in root directory
$files = scandir(__DIR__);

echo "<h3>🗑️ Starting Cleanup Process</h3>\n";

foreach ($files as $file) {
    if ($file === '.' || $file === '..') continue;
    
    $filePath = __DIR__ . '/' . $file;
    
    // Skip directories
    if (is_dir($filePath)) {
        continue;
    }
    
    $shouldDelete = false;
    $shouldArchive = false;
    
    // Check if file should be deleted
    foreach ($deletePatterns as $category => $patterns) {
        foreach ($patterns as $pattern) {
            if (fnmatch($pattern, $file)) {
                $shouldDelete = true;
                break 2;
            }
        }
    }
    
    // Check if file should be archived
    foreach ($archivePatterns as $pattern) {
        if (fnmatch($pattern, $file)) {
            $shouldArchive = true;
            break;
        }
    }
    
    // Execute action
    if ($shouldDelete) {
        if (unlink($filePath)) {
            $deletedCount++;
            echo "<div style='color: red;'>🗑️ Deleted: $file</div>\n";
        }
    } elseif ($shouldArchive) {
        $archivePath = $archiveDir . '/' . $file;
        if (rename($filePath, $archivePath)) {
            $archivedCount++;
            echo "<div style='color: orange;'>📁 Archived: $file</div>\n";
        }
    } elseif (in_array($file, $essentialFiles)) {
        $keptCount++;
        echo "<div style='color: green;'>✅ Kept: $file</div>\n";
    } else {
        // For other files, check if they're important
        $importantExtensions = ['php', 'html', 'css', 'js', 'json', 'xml', 'txt', 'sql', 'md'];
        $extension = pathinfo($file, PATHINFO_EXTENSION);
        
        if (in_array($extension, $importantExtensions)) {
            // Keep important files but note them
            $keptCount++;
            echo "<div style='color: blue;'>📄 Reviewed: $file</div>\n";
        }
    }
}

echo "<h3>📊 Cleanup Results</h3>\n";
echo "<div style='background: #f8f9fa; padding: 15px; border-radius: 8px;'>\n";
echo "<div><strong>Files Deleted:</strong> $deletedCount</div>\n";
echo "<div><strong>Files Archived:</strong> $archivedCount</div>\n";
echo "<div><strong>Files Kept:</strong> $keptCount</div>\n";
echo "<div><strong>Total Processed:</strong> " . ($deletedCount + $archivedCount + $keptCount) . "</div>\n";
echo "</div>\n";

echo "<h3>✅ Cleanup Complete!</h3>\n";
echo "<p>Root directory has been cleaned and organized. Essential files preserved, duplicates and test files removed.</p>\n";
?>
