<?php $this->layout = 'layouts/admin'; ?>

<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">AI Property Valuation Reports</h1>
    <div>
      <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#filterModal">
        <i class="fas fa-filter"></i> Filters
      </button>
      <a href="/admin/property-valuations/generate" class="btn btn-success">
        <i class="fas fa-plus"></i> Generate New
      </a>
    </div>
  </div>

  <!-- Stats Cards -->
  <div class="row mb-4">
    <div class="col-md-3 mb-3">
      <div class="card bg-primary text-white">
        <div class="card-body text-center">
          <h2 class="mb-0"><?= number_format($stats['total_valuations'] ?? 0) ?></h2>
          <small>Total Valuations</small>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <div class="card bg-success text-white">
        <div class="card-body text-center">
          <h2 class="mb-0">₹<?= number_format(($stats['avg_valuation'] ?? 0) / 100000, 2) ?>L</h2>
          <small>Avg Valuation</small>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <div class="card bg-info text-white">
        <div class="card-body text-center">
          <h2 class="mb-0"><?= number_format($stats['unique_properties'] ?? 0) ?></h2>
          <small>Properties Valued</small>
        </div>
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <div class="card bg-warning text-white">
        <div class="card-body text-center">
          <h2 class="mb-0">₹<?= number_format(($stats['total_base_valuation'] ?? 0) / 10000000, 2) ?>Cr</h2>
          <small>Total Valued</small>
        </div>
      </div>
    </div>
  </div>

  <!-- Reports Table -->
  <div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between">
      <span>Recent Valuation Reports</span>
      <span class="badge bg-secondary"><?= count($reports ?? []) ?> reports</span>
    </div>
    <div class="card-body p-0">
      <?php if (empty($reports)): ?>
        <div class="text-center py-5">
          <i class="fas fa-chart-line fa-3x text-muted mb-3"></i>
          <p class="text-muted">No valuation reports yet. Generate your first report.</p>
        </div>
      <?php else: ?>
        <div class="table-responsive">
          <table class="table table-hover mb-0">
            <thead class="table-light">
              <tr>
                <th>#</th>
                <th>Property</th>
                <th>Type</th>
                <th>Area (sqft)</th>
                <th>Base Valuation</th>
                <th>Final Valuation</th>
                <th>Confidence</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($reports as $report): ?>
                <tr>
                  <td><?= $report['id'] ?></td>
                  <td><?= htmlspecialchars($report['property_code'] ?? 'N/A') ?> <span class="text-muted">(ID: <?= $report['property_id'] ?>)</span></td>
                  <td><?= ucfirst($report['property_type'] ?? 'plot') ?></td>
                  <td><?= number_format($report['area_sqft'] ?? 0, 0) ?></td>
                  <td>₹<?= number_format($report['base_valuation'] ?? 0, 0) ?></td>
                  <td>₹<?= number_format($report['final_valuation'] ?? 0, 0) ?></td>
                  <td>
                    <span class="badge bg-<?= ($report['confidence_score'] ?? 0) >= 0.8 ? 'success' : (($report['confidence_score'] ?? 0) >= 0.6 ? 'warning' : 'danger') ?>">
                      <?= number_format(($report['confidence_score'] ?? 0) * 100, 0) ?>%
                    </span>
                  </td>
                  <td><?= htmlspecialchars($report['generated_by_name'] ?? 'System') ?></td>
                  <td><?= date('M d, Y', strtotime($report['generated_at'] ?? 'now')) ?></td>
                  <td>
                    <a href="/admin/property-valuations/view/<?= $report['id'] ?>" class="btn btn-sm btn-outline-primary">
                      <i class="fas fa-eye"></i> View
                    </a>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>

<!-- Filter Modal -->
<div class="modal fade" id="filterModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="GET">
    <?php echo CSRFProtection::csrfField(); ?>
        <div class="modal-header">
          <h5 class="modal-title">Filter Reports</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <label class="form-label">Date From</label>
            <input type="date" name="date_from" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label">Date To</label>
            <input type="date" name="date_to" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label">Min Valuation (₹)</label>
            <input type="number" name="min_value" class="form-control" step="100000">
          </div>
          <div class="mb-3">
            <label class="form-label">Max Valuation (₹)</label>
            <input type="number" name="max_value" class="form-control" step="100000">
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Apply Filters</button>
          <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal">Reset</button>
        </div>
      </form>
    </div>
  </div>
</div>
