<?php $this->layout = 'layouts/admin'; ?>

<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">Valuation Report #<?= $report['id'] ?></h1>
    <a href="/admin/property-valuations" class="btn btn-outline-secondary">
      <i class="fas fa-arrow-left"></i> Back to Reports
    </a>
  </div>

  <div class="row">
    <div class="col-md-8">
      <!-- Valuation Summary -->
      <div class="card shadow-sm mb-4">
        <div class="card-header">
          <h5 class="mb-0">Valuation Summary</h5>
        </div>
        <div class="card-body">
          <div class="row text-center mb-4">
            <div class="col-4">
              <h4 class="text-primary">₹<?= number_format($report['base_valuation'] ?? 0, 0) ?></h4>
              <small class="text-muted">Base Valuation</small>
            </div>
            <div class="col-4">
              <h4 class="text-success">₹<?= number_format($report['final_valuation'] ?? 0, 0) ?></h4>
              <small class="text-muted">Final Valuation</small>
            </div>
            <div class="col-4">
              <h4 class="text-warning"><?= number_format(($report['confidence_score'] ?? 0) * 100, 0) ?>%</h4>
              <small class="text-muted">Confidence</small>
            </div>
          </div>

          <table class="table table-bordered">
            <tr>
              <th>Property ID</th>
              <td><?= $report['property_id'] ?></td>
            </tr>
            <tr>
              <th>Property Code</th>
              <td><?= htmlspecialchars($report['property_code'] ?? 'N/A') ?></td>
            </tr>
            <tr>
              <th>Location</th>
              <td><?= htmlspecialchars($report['location'] ?? 'N/A') ?></td>
            </tr>
            <tr>
              <th>Property Type</th>
              <td><?= ucfirst($report['property_type'] ?? 'plot') ?></td>
            </tr>
            <tr>
              <th>Area (sqft)</th>
              <td><?= number_format($report['area_sqft'] ?? 0) ?></td>
            </tr>
            <tr>
              <th>Current Price</th>
              <td>₹<?= number_format($report['current_price'] ?? 0, 0) ?></td>
            </tr>
            <tr>
              <th>Location Multiplier</th>
              <td><?= $report['location_multiplier'] ?? 1.0 ?></td>
            </tr>
            <tr>
              <th>Type Multiplier</th>
              <td><?= $report['type_multiplier'] ?? 1.0 ?></td>
            </tr>
            <tr>
              <th>Market Adjustment</th>
              <td><?= $report['market_adjustment_pct'] ?? '0%' ?></td>
            </tr>
            <tr>
              <th>Generated By</th>
              <td><?= htmlspecialchars($report['generated_by_name'] ?? 'System') ?></td>
            </tr>
            <tr>
              <th>Generated At</th>
              <td><?= date('M d, Y H:i', strtotime($report['generated_at'] ?? 'now')) ?></td>
            </tr>
          </table>
        </div>
      </div>

      <!-- AI Analysis -->
      <?php if ($report['ai_analysis']): ?>
        <div class="card shadow-sm mb-4">
          <div class="card-header">
            <h5 class="mb-0">AI Analysis</h5>
          </div>
          <div class="card-body">
            <?php
            $analysis = json_decode($report['ai_analysis'], true) ?: $report['ai_analysis'];
            if (is_array($analysis)):
              echo '<pre class="bg-light p-3 rounded">' . print_r($analysis, true) . '</pre>';
            else:
              echo '<p>' . htmlspecialchars($analysis) . '</p>';
            endif;
            ?>
          </div>
        </div>
      <?php endif; ?>

      <!-- Recommendations -->
      <?php if ($report['recommendations']): ?>
        <div class="card shadow-sm">
          <div class="card-header">
            <h5 class="mb-0">AI Recommendations</h5>
          </div>
          <div class="card-body">
            <?php
            $recs = json_decode($report['recommendations'], true) ?: [];
            if (is_array($recs) && !empty($recs)):
              foreach ($recs as $rec):
                echo '<p class="mb-2">• ' . htmlspecialchars($rec) . '</p>';
              endforeach;
            else:
              echo '<p>' . htmlspecialchars($report['recommendations']) . '</p>';
            endif;
            ?>
          </div>
        </div>
      <?php endif; ?>
    </div>

    <div class="col-md-4">
      <!-- Comparable Properties -->
      <?php if ($report['comparable_properties']): ?>
        <div class="card shadow-sm mb-4">
          <div class="card-header">
            <h5 class="mb-0">Comparable Properties</h5>
          </div>
          <div class="card-body">
            <?php
            $comps = json_decode($report['comparable_properties'], true) ?: [];
            if (is_array($comps) && !empty($comps)):
              foreach ($comps as $comp):
                echo '<div class="border-bottom pb-2 mb-2">';
                echo '<strong>' . htmlspecialchars($comp['plot_number'] ?? $comp['property_code'] ?? 'N/A') . '</strong><br>';
                echo '<small class="text-muted">Price: ₹' . number_format($comp['total_price'] ?? $comp['final_valuation'] ?? 0, 0) . '</small>';
                echo '</div>';
              endforeach;
            else:
              echo '<p class="text-muted">No comparable properties found.</p>';
            endif;
            ?>
          </div>
        </div>
      <?php endif; ?>

      <!-- Market Analysis -->
      <?php if ($report['market_analysis']): ?>
        <div class="card shadow-sm">
          <div class="card-header">
            <h5 class="mb-0">Market Analysis</h5>
          </div>
          <div class="card-body">
            <?php
            $market = json_decode($report['market_analysis'], true) ?: $report['market_analysis'];
            if (is_array($market)):
              echo '<pre class="bg-light p-3 rounded">' . print_r($market, true) . '</pre>';
            else:
              echo '<p>' . htmlspecialchars($market) . '</p>';
            endif;
            ?>
          </div>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>
