<?php $page_title = $page_title ?? 'Generated Documents'; ?>
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="h3 mb-0"><i class="fas fa-robot me-2"></i>Generated Documents</h1>
        <a href="<?= BASE_URL ?>/admin/documents" class="btn btn-outline-secondary"><i class="fas fa-arrow-left me-1"></i>Back</a>
    </div>

    <div class="card shadow-sm">
        <div class="card-header aps-cp-card-header"><i class="fas fa-list me-2"></i>All Generated Documents</div>
        <div class="card-body aps-cp-card-body">
            <?php if (!empty($records)): ?>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="table-light">
                            <tr><th>ID</th><th>Template</th><th>Entity</th><th>Entity ID</th><th>Generated By</th><th>Date</th></tr>
                        </thead>
                        <tbody>
                            <?php foreach ($records as $r): ?>
                                <tr>
                                    <td><?= (int)$r['id'] ?></td>
                                    <td><?= htmlspecialchars($r['template_name'] ?? 'ID: ' . ($r['template_id'] ?? 0)) ?></td>
                                    <td><span class="badge bg-info"><?= htmlspecialchars($r['entity_type'] ?? '-') ?></span></td>
                                    <td><?= (int)($r['entity_id'] ?? 0) ?></td>
                                    <td><?= htmlspecialchars($r['generated_by_name'] ?? '-') ?></td>
                                    <td><?= htmlspecialchars($r['created_at'] ?? '-') ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <div class="text-center py-5">
                    <i class="fas fa-robot fa-3x text-muted mb-3"></i>
                    <p class="text-muted">No generated documents yet.</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
