<?php
// Feature permissions for each role (1 = enabled, 0 = disabled)
return [
    'admin' => [
        'dashboard' => 1,
        'add_property' => 1,
        'view_analytics' => 1,
        'manage_users' => 1,
        'manage_employees' => 1,
        'settings' => 1,
        'ai_tools' => 1,
    ],
    'superadmin' => [
        'dashboard' => 1,
        'add_property' => 1,
        'view_analytics' => 1,
        'manage_users' => 1,
        'manage_employees' => 1,
        'settings' => 1,
        'ai_tools' => 1,
    ],
    'associate' => [
        'dashboard' => 1,
        'add_property' => 1,
        'view_analytics' => 0,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
    'user' => [
        'dashboard' => 1,
        'add_property' => 0,
        'view_analytics' => 0,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
    'builder' => [
        'dashboard' => 1,
        'add_property' => 1,
        'view_analytics' => 1,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
    'agent' => [
        'dashboard' => 1,
        'add_property' => 1,
        'view_analytics' => 0,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
    'employee' => [
        'dashboard' => 1,
        'add_property' => 0,
        'view_analytics' => 0,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
    'customer' => [
        'dashboard' => 1,
        'add_property' => 0,
        'view_analytics' => 0,
        'manage_users' => 0,
        'manage_employees' => 0,
        'settings' => 0,
        'ai_tools' => 0,
    ],
];
