-- Enterprise App Store
CREATE TABLE IF NOT EXISTS app_store (
  id INT AUTO_INCREMENT PRIMARY KEY,
  app_name VARCHAR(255) NOT NULL,
  provider VARCHAR(255),
  app_url VARCHAR(255),
  price DECIMAL(10,2) DEFAULT 0.0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
