#!/bin/bash
# APS Dream Home - GitKraken MCP Authentication Helper

echo '🔐 GitKraken MCP Authentication Helper'
echo '======================================'

echo '📋 Steps to authenticate GitKraken MCP:'
echo ''
echo '1. 🔗 Click this authentication link in your browser:'
echo '   windsurf://eamodio.gitlens/link/command/login?source=mcp'
echo ''
echo '2. 💻 Alternative terminal command:'
echo '   gk auth login'
echo ''
echo '3. 🌐 Sign in with your GitKraken account'
echo ''
echo '4. 🔗 Connect your Git hosting accounts (GitHub, GitLab, etc.)'
echo ''
echo '5. 🔄 Restart Windsurf IDE'
echo ''
echo '6. ✅ Check if GitKraken MCP shows green status'
echo ''
echo '🎯 Test commands after authentication:'
echo '   - git status'
echo '   - git fetch'
echo '   - git pull'
echo '   - git push'
echo ''
echo '🎉 Authentication complete!'
