<?php
// Functionality mapping: for each dropped table, check if equivalent functionality exists
$root = dirname(__DIR__);
$config = require $root . '/config/database.php';
$pdo = new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$config['database']};charset=utf8mb4",
    $config['username'], $config['password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

$old = json_decode(file_get_contents('_old_db_schema.json'), true);
$current = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
$dropped = array_diff(array_keys($old), $current);

// Mapping rules: dropped table -> where functionality should be (current table or "MISSING")
// Based on schema analysis
$mapping = [
    // AI features - most are in ai_* or chatbot tables that SURVIVED
    'ai_chat_history' => 'chat_messages',
    'ai_chatbot_config' => 'ai_settings',
    'ai_conversation_states' => 'ai_context_memory OR ai_conversations',
    'ai_learning_progress' => 'module_progress (training)',
    'ai_user_preferences' => 'ai_user_interactions (general AI)',
    'ai_user_profiles' => 'users + ai_settings',
    'ai_property_suggestions' => 'user_properties + properties',
    'ai_knowledge_graph' => 'ai_knowledge_base',
    'ai_recommendations' => 'ai_user_suggestions',
    'ai_tools_directory' => 'MISSING (1000 rows of test data)',
    'ai_workflows' => 'workflows / workflow_definitions',
    'ai_implementation_guides' => 'MISSING (100 rows test data)',
    'ai_audit_log' => 'activity_logs_unified OR system_logs',
    'ai_ecosystem_tools' => 'MISSING (82 rows - likely test data)',

    // Voice/Calling
    'call_logs' => 'MISSING (call log functionality not implemented yet)',
    'ai_call_logs' => 'ai_call_sessions (merged)',
    'ai_call_scripts' => 'ai_call_scripts (SURVIVED)',
    'ai_calling_agents' => 'ai_calling_agents (SURVIVED)',
    'ai_calling_schedule' => 'ai_calling_schedule (SURVIVED)',
    'ai_call_extracted_leads' => 'ai_call_extracted_leads (SURVIVED)',
    'telecaller_daily_tasks' => 'MISSING (telecaller workflow not implemented)',
    'telecaller_performance' => 'MISSING (no performance dashboard for telecaller)',

    // MLM/Network
    'mlm_earnings' => 'mlm_commission_ledger (earnings are tracked there)',
    'mlm_points' => 'wallet_points (point balance)',
    'mlm_referrals' => 'referrals',
    'mlm_notification_log' => 'notifications (general)',
    'mlm_commission_levels' => 'mlm_profiles (level field)',
    'mlm_rank_rates' => 'MISSING (rank-based rate table)',
    'mlm_settings' => 'site_settings OR settings (general config)',
    'mlm_import_audit' => 'activity_logs_unified (audit)',
    'sponsor_running_no' => 'MISSING (sponsor counter)',
    'commission_preferences' => 'MISSING (per-user commission config)',
    'agent_commission_rates' => 'MISSING (agent rate table)',
    'commission_calculation_rules' => 'MISSING (calculation engine config)',
    'associate_commission_calculations' => 'MISSING (calculation history)',
    'revenue_commission_daily' => 'MISSING (daily revenue commission)',
    'associate_commission_structure' => 'MISSING (per-associate rates)',
    'mlm_commission_plans' => 'MISSING (commission plan definitions)',
    'mlm_payouts' => 'payouts',
    'payouts' => 'payouts (SURVIVED - 2 rows)',
    'salary_payouts' => 'salary_payments (related but separate)',
    'telecaller_commissions' => 'MISSING (telecaller-specific)',
    'telecaller_commission_rules' => 'MISSING',
    'commission_payouts' => 'payouts OR mlm_commission_ledger',
    'farmer_commission_structures' => 'MISSING (farmer-specific)',
    'farmer_commissions' => 'MISSING',
    'hybrid_commission_records' => 'MISSING (hybrid model)',
    'mlm_commission_agreements' => 'MISSING (contract terms)',
    'resale_commissions' => 'MISSING (resale-specific)',
    'traditional_commissions' => 'MISSING',
    'commission_rules' => 'MISSING (rule engine)',
    'hybrid_commission_plans' => 'MISSING',

    // Property/Plot
    'plot_master' => 'plots (master-detail relationship)',
    'plot_categories' => 'property_categories',
    'plot_cuttings' => 'plots (with dimensions)',
    'plot_emi_schedule' => 'emi_installments',
    'plot_images' => 'property_images',
    'plot_rate_calculations' => 'plot_development_costs OR property_valuations',
    'property_ai_tags' => 'MISSING (AI-tagged property features)',
    'property_bookings' => 'bookings (general booking)',
    'property_categories' => 'property_categories (SURVIVED)',
    'property_features' => 'property_features (SURVIVED)',
    'property_feature_map' => 'property_feature_map (SURVIVED)',
    'property_feature_mappings' => 'property_feature_map',
    'property_amenities' => 'property_features',
    'property_analytics' => 'MISSING (property-level analytics)',
    'property_comparisons' => 'property_comparison_sessions',
    'property_development_costs' => 'plot_development_costs',
    'property_documents' => 'documents (polymorphic)',
    'property_inquiries' => 'inquiries (general)',
    'property_maintenance' => 'MISSING (post-sale maintenance)',
    'property_market_data' => 'MISSING (market intelligence)',
    'property_performance' => 'MISSING (performance dashboard)',
    'property_performance_metrics' => 'performance_metrics (general)',
    'property_portfolios' => 'MISSING (buyer portfolio)',
    'property_ratings' => 'property_reviews',
    'property_sales' => 'sales (SURVIVED)',
    'property_submissions' => 'user_properties (user-submitted)',
    'property_summary' => 'MISSING (summary view)',
    'property_valuations' => 'MISSING (valuation history)',
    'property_views' => 'visitor_page_views',
    'resell_properties' => 'MISSING (resale-specific listing)',
    'resell_property_images' => 'property_images',
    'resell_commission_structure' => 'MISSING',

    // Lead/CRM
    'crm_leads' => 'leads',
    'leaderboards' => 'MISSING (gamification leaderboard)',
    'leaderboard_entries' => 'MISSING',
    'lead_assignments' => 'leads (assignment_id field)',
    'lead_assignment_approvals' => 'MISSING (approval workflow)',
    'lead_assignment_history' => 'lead_activities',
    'lead_custom_fields' => 'MISSING (dynamic fields)',
    'lead_custom_field_values' => 'MISSING',
    'lead_deals' => 'deals',
    'lead_events' => 'lead_activities',
    'lead_export_logs' => 'MISSING (export audit)',
    'lead_files' => 'documents (polymorphic, entity_type=lead)',
    'lead_pipeline' => 'pipeline_stages',
    'lead_scoring_models' => 'lead_scoring_rules',
    'lead_status_history' => 'lead_activities',
    'lead_statuses' => 'MISSING (status master)',
    'lead_tag_mapping' => 'lead_tags',
    'incomplete_registrations' => 'MISSING (incomplete form tracking)',
    'progressive_registrations' => 'MISSING (step-by-step registration)',
    'customer_inquiries' => 'inquiries',
    'customer_alerts' => 'notifications',
    'customer_behavior_analysis' => 'MISSING (behavior tracking)',
    'customer_journeys' => 'MISSING (customer lifecycle)',
    'customers_ledger' => 'MISSING (customer account ledger)',
    'customer_summary' => 'MISSING (summary view)',
    'follow_ups' => 'lead_activities',

    // Booking/Visit
    'booking_logs' => 'MISSING (booking event log)',
    'booking_emis' => 'emi_installments',
    'booking_payments' => 'payments',
    'land_allocations' => 'plot_allocations',
    'site_visit_requests' => 'site_visits',
    'site_visits' => 'site_visits (SURVIVED)',
    'visit_reminders' => 'notifications',
    'visitor_leads' => 'leads',
    'visitor_sessions' => 'MISSING (session tracking)',
    'visitor_page_views' => 'visitor_page_views (SURVIVED)',

    // HRM/Payroll
    'attendance_settings' => 'MISSING (settings table)',
    'company_employees' => 'employees',
    'employee_activities' => 'MISSING',
    'employee_advances' => 'MISSING (salary advance)',
    'employee_attendance' => 'employee_attendance (SURVIVED)',
    'employee_bonuses' => 'MISSING (bonus tracking)',
    'employee_documents' => 'documents (polymorphic)',
    'employee_leave_balances' => 'employee_leaves',
    'employee_leaves' => 'employee_leaves (SURVIVED)',
    'employee_payroll' => 'employee_payroll (SURVIVED)',
    'employee_payrolls' => 'employee_payroll',
    'employee_salary_structure' => 'employee_salary_structure (SURVIVED)',
    'employee_shifts' => 'shift_schedules',
    'employee_tasks' => 'tasks',
    'payroll_entries' => 'MISSING (payroll run details)',
    'payroll_runs' => 'payroll_runs (SURVIVED)',
    'salary_contracts' => 'MISSING',
    'salary_history' => 'MISSING',
    'salary_plans' => 'MISSING',
    'salary_records' => 'salary_records (SURVIVED)',
    'salary_structures' => 'employee_salary_structure (merged)',
    'salary_tracker' => 'MISSING (MLM-specific)',
    'shift_schedules' => 'shift_schedules (SURVIVED)',
    'shift_types' => 'shift_types (SURVIVED)',
    'team' => 'team (SURVIVED)',
    'team_members' => 'team',
    'department_assignments' => 'MISSING',
    'department_budgets' => 'MISSING',
    'jobs' => 'jobs (SURVIVED)',
    'job_applications' => 'job_applications (SURVIVED)',

    // Document/File
    'business_documents' => 'documents (polymorphic)',
    'customer_documents' => 'documents (polymorphic)',
    'document_categories' => 'document_categories (SURVIVED)',
    'document_classification' => 'MISSING (auto-classification)',
    'document_gallery' => 'document_gallery (SURVIVED)',
    'document_reviews' => 'MISSING',
    'document_templates' => 'document_templates (SURVIVED)',
    'document_types' => 'document_types (SURVIVED)',
    'employee_documents' => 'documents (polymorphic)',
    'files' => 'file_uploads OR media',
    'file_access_logs' => 'MISSING',
    'file_shares' => 'file_shares (SURVIVED)',
    'file_tag_relations' => 'file_tag_relations (SURVIVED)',
    'file_tags' => 'file_tags (SURVIVED)',
    'file_uploads' => 'file_uploads (SURVIVED)',
    'file_versions' => 'file_versions (SURVIVED)',
    'generated_documents' => 'documents (polymorphic)',
    'legal_documents' => 'documents (polymorphic)',
    'legal_document_templates' => 'document_templates',
    'message_attachments' => 'documents (polymorphic)',
    'ocr_documents' => 'MISSING (OCR-processed docs)',
    'ocr_extracted_fields' => 'MISSING (OCR data extraction)',
    'ocr_processing_queue' => 'MISSING (OCR job queue)',
    'ocr_templates' => 'MISSING',
    'user_documents' => 'documents (polymorphic)',

    // Notification/Communication
    'communication_interactions' => 'communications OR messages',
    'communication_logs' => 'MISSING',
    'communications' => 'MISSING (parallel comms system)',
    'conversation_participants' => 'conversation_participants (SURVIVED)',
    'conversations' => 'chatbot_conversations',
    'email_logs' => 'email_queue',
    'email_queue' => 'email_queue (SURVIVED)',
    'email_templates' => 'email_templates (SURVIVED)',
    'email_tracking' => 'MISSING (open/click tracking)',
    'email_verifications' => 'MISSING (email verification tokens)',
    'messages' => 'MISSING (generic messages)',
    'message_reactions' => 'MISSING',
    'message_templates' => 'message_templates (SURVIVED)',
    'notification_campaigns' => 'notification_campaigns (SURVIVED)',
    'notification_feed' => 'notifications',
    'notification_queue' => 'notification_queue (SURVIVED)',
    'notification_settings' => 'MISSING (user prefs)',
    'notification_templates' => 'MISSING (template master)',
    'notifications' => 'notifications (SURVIVED)',
    'notifications_unified' => 'notifications_unified (SURVIVED)',
    'otp_verifications' => 'MISSING (OTP tokens)',
    'push_notifications' => 'MISSING',
    'push_subscriptions' => 'MISSING',
    'realtime_notifications' => 'MISSING (websocket push)',
    'sms_queue' => 'sms_queue (SURVIVED)',
    'sms_templates' => 'MISSING',
    'typing_indicators' => 'MISSING (chat feature)',
    'whatsapp_automation_config' => 'whatsapp_automation_config (SURVIVED)',
    'whatsapp_campaigns' => 'whatsapp_campaigns (SURVIVED)',
    'whatsapp_lead_shares' => 'MISSING',
    'whatsapp_messages' => 'whatsapp_messages (SURVIVED)',
    'whatsapp_templates' => 'MISSING',

    // Logs/Audit/Analytics
    'activity_log' => 'activity_logs_unified OR audit_log',
    'activity_logs' => 'activity_logs_unified',
    'admin_activity_log' => 'activity_logs_unified',
    'admin_dashboard_stats' => 'MISSING (dashboard cache)',
    'admin_reports' => 'reports',
    'analytics_alerts' => 'MISSING',
    'analytics_conversions' => 'MISSING',
    'analytics_dashboards' => 'MISSING',
    'analytics_events' => 'MISSING',
    'analytics_page_views' => 'analytics_page_views (SURVIVED)',
    'analytics_performance' => 'performance_metrics',
    'analytics_reports' => 'reports',
    'analytics_summary' => 'MISSING',
    'analytics_user_behavior' => 'user_behavior_tracking',
    'api_analytics' => 'MISSING',
    'api_logs' => 'MISSING',
    'api_request_logs' => 'MISSING',
    'audit_log' => 'audit_log (SURVIVED)',
    'audit_log_archive' => 'MISSING',
    'audit_schedules' => 'MISSING',
    'audit_trail' => 'audit_log',
    'communication_logs' => 'MISSING',
    'comparison_analytics' => 'MISSING',
    'conversion_analytics' => 'MISSING',
    'crash_reports' => 'error_logs',
    'daily_activity_tracker' => 'MISSING',
    'daily_metrics_summary' => 'MISSING',
    'data_change_log' => 'MISSING',
    'data_stream_events' => 'MISSING',
    'employee_kpis' => 'MISSING',
    'employee_reporting' => 'MISSING',
    'error_logs' => 'error_logs (SURVIVED)',
    'event_log' => 'MISSING',
    'file_access_logs' => 'MISSING',
    'financial_integration_log' => 'MISSING',
    'forecast_results' => 'forecast_results (SURVIVED)',
    'foreclosure_logs' => 'MISSING',
    'integration_activity_logs' => 'MISSING',
    'integration_logs' => 'MISSING',
    'inventory_log' => 'MISSING',
    'kpis' => 'MISSING',
    'load_test_metrics' => 'MISSING',
    'market_analytics_summary' => 'MISSING',
    'mcp_config_history' => 'MISSING',
    'mcp_logs' => 'MISSING',
    'mobile_app_analytics' => 'MISSING',
    'performance_analytics' => 'MISSING',
    'performance_benchmarks' => 'MISSING',
    'performance_feedback' => 'feedback',
    'performance_goals' => 'MISSING',
    'performance_logs' => 'MISSING',
    'performance_metrics' => 'performance_metrics (SURVIVED)',
    'performance_reports' => 'reports',
    'performance_reviews' => 'MISSING',
    'plan_status_history' => 'MISSING',
    'portfolio_analytics' => 'MISSING',
    'portfolio_reports' => 'reports',
    'quick_actions_log' => 'MISSING',
    'registry_activity_log' => 'MISSING',
    'reports' => 'reports (SURVIVED)',
    'saved_reports' => 'MISSING',
    'security_audit_log' => 'security_audit_log (SURVIVED)',
    'security_blacklist' => 'MISSING',
    'security_events' => 'MISSING',
    'security_logs' => 'MISSING',
    'security_rate_limits' => 'MISSING',
    'security_sessions' => 'MISSING',
    'sync_log' => 'MISSING',
    'sync_mappings' => 'MISSING',
    'sync_queue' => 'sync_queue (SURVIVED)',
    'sync_queue_summary' => 'MISSING',
    'system_activities' => 'activity_logs_unified',
    'system_alerts' => 'notifications',
    'system_analytics_metrics' => 'MISSING',
    'system_backups' => 'MISSING',
    'system_health' => 'MISSING',
    'system_health_logs' => 'MISSING',
    'system_logs' => 'system_logs (SURVIVED)',
    'system_metrics' => 'MISSING',
    'system_status' => 'MISSING',
    'task_execution_logs' => 'MISSING',
    'traffic_stats' => 'MISSING',
    'training_analytics' => 'MISSING',
    'upload_audit_log' => 'MISSING',
    'user_activity' => 'user_activity (SURVIVED)',
    'user_activity_logs' => 'activity_logs_unified',
    'user_analytics' => 'MISSING',
    'user_behavior_analytics' => 'MISSING',
    'user_behavior_tracking' => 'MISSING',
    'user_browsing_history' => 'MISSING',
    'user_search_history' => 'MISSING',
    'user_summary' => 'MISSING (summary view)',

    // Gamification
    'achievements' => 'achievements (SURVIVED)',
    'badges' => 'badges (SURVIVED)',
    'challenge_participants' => 'MISSING',
    'gamification_badges' => 'badges',
    'gamification_challenges' => 'MISSING',
    'gamification_points' => 'wallet_points OR loyalty_points',
    'user_achievements' => 'user_achievements (SURVIVED)',
    'user_badges' => 'user_badges (SURVIVED)',

    // Training/Course
    'chatbot_training_data' => 'MISSING (training data)',
    'course_modules' => 'training_modules',
    'learning_paths' => 'MISSING',
    'module_progress' => 'module_progress (SURVIVED)',
    'personalized_learning_plans' => 'MISSING',
    'training_certificates' => 'MISSING',
    'training_courses' => 'training_courses (SURVIVED)',
    'training_enrollments' => 'MISSING (or training_enrollments SURVIVED)',
    'training_lessons' => 'training_modules',
    'training_modules' => 'training_modules (SURVIVED)',
    'training_quiz_results' => 'MISSING',
    'training_quizzes' => 'MISSING',
    'user_course_enrollments' => 'training_enrollments',

    // Settings/Config
    'accounting_settings' => 'MISSING',
    'app_config' => 'site_settings',
    'api_configs' => 'api_configs (SURVIVED)',
    'api_integrations' => 'api_integrations (SURVIVED)',
    'company_projects' => 'MISSING',
    'company_settings' => 'settings OR site_settings',
    'dashboard_widgets_config' => 'dashboard_widgets',
    'email_config' => 'MISSING',
    'gst_settings' => 'MISSING',
    'integration_settings' => 'MISSING',
    'integrations' => 'MISSING',
    'layout_settings' => 'MISSING',
    'mcp_server_configs' => 'MISSING',
    'mcp_servers' => 'MISSING',
    'mobile_app_settings' => 'MISSING',
    'recommendation_settings' => 'MISSING',
    'settings' => 'settings (SURVIVED)',
    'site_settings' => 'site_settings (SURVIVED)',
    'sms_config' => 'MISSING',
    'system_settings' => 'MISSING',
    'third_party_integrations' => 'MISSING',
    'user_dashboard_configs' => 'MISSING',
    'webhook_events' => 'MISSING',
    'webhooks' => 'MISSING',

    // Content/CMS
    'about' => 'pages (general content)',
    'agent_reviews' => 'agent_reviews (SURVIVED)',
    'blog_categories' => 'MISSING',
    'blog_posts' => 'blogs',
    'blogs' => 'blogs (SURVIVED)',
    'content_backups' => 'MISSING',
    'content_translations' => 'translations',
    'dynamic_footers' => 'MISSING',
    'dynamic_headers' => 'MISSING',
    'faq_categories' => 'MISSING',
    'faqs' => 'faqs (SURVIVED)',
    'feedback' => 'feedback_tickets',
    'feedback_tickets' => 'feedback_tickets (SURVIVED)',
    'knowledge_base' => 'knowledge_base (SURVIVED)',
    'languages' => 'MISSING',
    'legal_pages' => 'legal_pages (SURVIVED)',
    'media' => 'media (SURVIVED)',
    'media_library' => 'media',
    'multi_language_translations' => 'translations',
    'news' => 'news (SURVIVED)',
    'newsletter_schedules' => 'MISSING',
    'newsletter_subscribers' => 'newsletter_subscribers (SURVIVED)',
    'page_templates' => 'MISSING',
    'pages' => 'pages (SURVIVED)',
    'rating' => 'MISSING',
    'reviews' => 'property_reviews OR agent_reviews',
    'seo_metadata' => 'MISSING',
    'site_content' => 'pages',
    'special_offers' => 'MISSING',
    'testimonials' => 'testimonials (SURVIVED)',
    'todays_highlights' => 'MISSING',
    'translations' => 'translations (SURVIVED)',

    // Media
    'document_gallery' => 'document_gallery (SURVIVED)',
    'gallery' => 'gallery (SURVIVED)',
    'gallery_images' => 'gallery',
    'image_categories' => 'MISSING',
    'images' => 'media',
    'project_gallery' => 'MISSING',
    'social_media_links' => 'MISSING',

    // Finance/Accounting
    'budget_expenses' => 'expenses',
    'budget_items' => 'budget_items (SURVIVED)',
    'budget_planning' => 'MISSING',
    'budgets' => 'MISSING',
    'builder_payments' => 'MISSING',
    'cash_flow_projections' => 'MISSING',
    'chart_of_accounts' => 'chart_of_accounts (SURVIVED)',
    'commission_transactions' => 'mlm_commission_ledger',
    'emi_calculator_history' => 'MISSING',
    'emi_installments' => 'emi_installments (SURVIVED)',
    'emi_payments' => 'payments',
    'emi_plans' => 'emi_plans (SURVIVED)',
    'emi_schedule' => 'emi_installments',
    'expenses' => 'expenses (SURVIVED)',
    'farmer_transactions' => 'MISSING',
    'financial_integration_log' => 'MISSING',
    'financial_transactions' => 'transactions',
    'funding_investors' => 'MISSING',
    'gst_returns' => 'MISSING',
    'hr_reminders' => 'notifications',
    'income_records' => 'MISSING (or income_records SURVIVED)',
    'interaction_reminders' => 'notifications',
    'investment_plans' => 'MISSING',
    'invoice_items' => 'invoice_items (SURVIVED)',
    'invoice_payments' => 'payments',
    'invoice_templates' => 'invoice_templates (SURVIVED)',
    'invoices' => 'invoices (SURVIVED)',
    'investor_details' => 'MISSING',
    'journal_entries' => 'journal_entries (SURVIVED)',
    'journal_entry_details' => 'journal_entry_details (SURVIVED)',
    'journal_entry_lines' => 'journal_entry_lines (SURVIVED)',
    'loan_emi_schedule' => 'MISSING',
    'loans' => 'loans (SURVIVED)',
    'mlm_transactions' => 'mlm_commission_ledger',
    'mortgage_inquiries' => 'MISSING',
    'payment_gateway_config' => 'MISSING',
    'payment_gateway_logs' => 'MISSING',
    'payment_history' => 'MISSING',
    'payment_notifications' => 'notifications',
    'payment_orders' => 'MISSING',
    'payment_plans' => 'MISSING',
    'payment_receipts' => 'MISSING',
    'payment_settings' => 'MISSING',
    'payment_summary' => 'MISSING',
    'payment_transactions' => 'transactions',
    'payments' => 'payments (SURVIVED)',
    'point_rules' => 'points_rules (SURVIVED)',
    'points_transactions' => 'points_transactions (SURVIVED)',
    'purchase_invoice_items' => 'MISSING',
    'purchase_invoices' => 'MISSING',
    'recurring_transactions' => 'MISSING',
    'rent_payments' => 'MISSING',
    'retained_earnings' => 'MISSING',
    'revenue_summary' => 'MISSING',
    'reward_history' => 'MISSING',
    'reward_redemptions' => 'MISSING',
    'rewards_catalog' => 'rewards_catalog (SURVIVED)',
    'sales_funnel' => 'MISSING',
    'tax_reminders' => 'MISSING',
    'tax_slabs' => 'MISSING',
    'tax_types' => 'MISSING',
    'transactions' => 'transactions (SURVIVED)',
    'user_payment_methods' => 'MISSING',
    'user_wallets' => 'wallet_points',
    'wallet_configuration' => 'MISSING',
    'wallet_points' => 'wallet_points (SURVIVED)',
    'wallet_transactions' => 'points_transactions OR transactions',
    'withdrawal_requests' => 'withdrawal_requests (SURVIVED)',

    // Marketing
    'ad_slots' => 'MISSING',
    'campaign_deliveries' => 'MISSING',
    'campaign_members' => 'MISSING',
    'campaigns' => 'campaigns (SURVIVED)',
    'marketing_analytics' => 'MISSING',
    'marketing_automations' => 'MISSING',
    'marketing_campaigns' => 'campaigns',
    'marketing_leads' => 'leads',
    'marketing_strategies' => 'MISSING',
    'popups' => 'MISSING',
    'popup_dismissals' => 'MISSING',

    // Farmer/Agriculture
    'farmer_activities' => 'MISSING',
    'farmer_agreements' => 'MISSING',
    'farmer_commissions' => 'MISSING',
    'farmer_commission_structures' => 'MISSING',
    'farmer_documents' => 'documents (polymorphic)',
    'farmer_land_holdings' => 'MISSING',
    'farmer_loans' => 'MISSING',
    'farmer_profiles' => 'MISSING',
    'farmer_support_requests' => 'MISSING',
    'farmer_transactions' => 'MISSING',
    'farmers' => 'MISSING (or farmers_legacy)',
    'farmers_legacy' => 'MISSING',
    'gata_master' => 'MISSING (legacy land records)',
    'khatabook_sales' => 'MISSING',
    'kisaan_land_management' => 'MISSING',
    'kissan_master' => 'MISSING',

    // Auth/Permission
    'admin' => 'users (admin role)',
    'admin_role_menu_permissions' => 'MISSING (cleaned up)',
    'admin_user_menu_permissions' => 'MISSING',
    'admin_users' => 'users',
    'agent_details_backup_20260531' => 'agents',
    'blocked_ips' => 'MISSING',
    'customers' => 'users (customer role)',
    'failed_login_attempts' => 'MISSING',
    'jwt_blacklist' => 'MISSING',
    'mobile_app_tokens' => 'MISSING',
    'password_reset_tokens' => 'MISSING (or password_reset_tokens SURVIVED)',
    'permissions' => 'MISSING (cleaned up)',
    'possession_checklist' => 'MISSING (possession workflow)',
    'remember_tokens' => 'MISSING',
    'role_change_approvals' => 'MISSING',
    'role_menus' => 'MISSING',
    'role_permissions' => 'MISSING',
    'roles' => 'roles (SURVIVED)',
    'two_factor_tokens' => 'MISSING',
    'user_permissions' => 'MISSING',
    'user_role_permissions' => 'MISSING',
    'user_sessions' => 'MISSING',
    'user_roles' => 'roles',

    // Workflow/Task
    'async_tasks' => 'async_tasks (SURVIVED)',
    'compliance_tasks' => 'compliance_tasks (SURVIVED)',
    'employee_tasks' => 'tasks',
    'scheduled_tasks' => 'scheduled_tasks (SURVIVED)',
    'task_dependencies' => 'MISSING',
    'task_executions' => 'MISSING',
    'task_queue' => 'MISSING',
    'tasks' => 'tasks (SURVIVED)',
    'workflow_actions' => 'workflow_actions (SURVIVED)',
    'workflow_automations' => 'MISSING',
    'workflow_definitions' => 'workflow_definitions (SURVIVED)',
    'workflow_executions' => 'workflow_executions (SURVIVED)',
    'workflow_instances' => 'workflow_instances (SURVIVED)',
    'workflow_steps' => 'workflow_steps (SURVIVED)',
    'workflows' => 'workflow_definitions',

    // Builder/Company
    'builder_details' => 'MISSING',
    'builders' => 'MISSING (or builders SURVIVED)',
    'companies' => 'MISSING (or companies SURVIVED)',
    'company_property_levels' => 'MISSING',

    // Address/Location
    'addresses' => 'MISSING',
    'countries' => 'countries (SURVIVED)',
    'real_estate_properties' => 'properties',
    'sites' => 'colonies (renamed)',
    'user_addresses' => 'MISSING',

    // User
    'agents' => 'agents (SURVIVED)',
    'mobile_devices' => 'MISSING',
    'mobile_users' => 'MISSING',
    'user_preferences' => 'MISSING',
    'user_engagement' => 'MISSING',
    'users_backup_20260320' => 'users',

    // Sales/Deal
    'deal_activities' => 'deal_history',
    'deal_history' => 'deal_history (SURVIVED)',
    'deals' => 'deals (SURVIVED)',
    'opportunities' => 'deals',
    'pipeline_activities' => 'pipeline_activities (SURVIVED)',
    'pipeline_analytics' => 'MISSING',
    'pipeline_filters' => 'MISSING',
    'pipeline_movement_history' => 'deal_history',
    'pipeline_stages' => 'pipeline_stages (SURVIVED)',
    'saved_comparisons' => 'MISSING',
    'saved_properties' => 'MISSING',
    'saved_searches' => 'saved_searches (SURVIVED)',
    'sales_data' => 'MISSING',
    'sales_pipeline_stages' => 'pipeline_stages',
    'favorites' => 'favorites (SURVIVED)',
    'customer_favorites' => 'favorites',
    'customer_wishlist' => 'favorites',

    // Career
    'career_applications' => 'career_applications (SURVIVED)',
    'careers' => 'careers (SURVIVED)',

    // Support
    'support_ticket_replies' => 'ticket_replies',
    'support_ticket_responses' => 'ticket_replies',
    'ticket_replies' => 'ticket_replies (SURVIVED)',

    // Package
    'marketplace_apps' => 'MISSING',
    'packages' => 'MISSING',
    'partner_certification' => 'MISSING',
    'partner_rewards' => 'MISSING',
    'saas_instances' => 'MISSING',
    'tier_benefits' => 'MISSING',

    // Other misc
    'alert_triggers' => 'MISSING',
    'app_store' => 'MISSING',
    'ar_vr_tours' => 'MISSING',
    'area_amenities' => 'MISSING',
    'automated_triggers' => 'MISSING',
    'automation_triggers' => 'MISSING',
    'chatbot_conversations' => 'chatbot_conversations (SURVIVED)',
    'chatbot_fallback' => 'MISSING',
    'comparison_criteria' => 'MISSING',
    'components' => 'MISSING',
    'custom_features' => 'MISSING',
    'data_stream_events' => 'MISSING',
    'files' => 'file_uploads',
    'forecast_results' => 'forecast_results (SURVIVED)',
    'heatmap_data' => 'MISSING',
    'import_jobs' => 'MISSING',
    'incomplete_registrations' => 'MISSING',
    'interaction_routing' => 'MISSING',
    'iot_device_events' => 'MISSING',
    'iot_devices' => 'MISSING',
    'kisan_land_management' => 'MISSING',
    'kisan_master' => 'MISSING',
    'land_acquisitions' => 'land_acquisitions (SURVIVED)',
    'land_management_activities' => 'MISSING',
    'land_projects' => 'MISSING',
    'land_purchases' => 'MISSING',
    'land_records' => 'land_records (SURVIVED)',
    'layout_templates' => 'MISSING',
    'leadership' => 'MISSING',
    'legal_activities' => 'MISSING',
    'legal_deadlines' => 'MISSING',
    'legal_disputes' => 'MISSING',
    'legal_services' => 'legal_services (SURVIVED)',
    'mcp_data' => 'MISSING',
    'message_reactions' => 'MISSING',
    'migration_errors' => 'error_logs',
    'mobile_app_keys' => 'MISSING',
    'ocr_processing_queue' => 'MISSING',
    'partner_certification' => 'MISSING',
    'portfolio_goals' => 'MISSING',
    'predictive_models' => 'MISSING',
    'property_summary' => 'MISSING',
    'quick_replies' => 'MISSING',
    'quiz_questions' => 'MISSING',
    'recommendation_cache' => 'MISSING',
    'regional_performance' => 'MISSING',
    'seasonality_patterns' => 'MISSING',
    'smart_contracts' => 'MISSING',
    'user_ai_profiles' => 'MISSING',
    'user_similarity' => 'MISSING',
    'virtual_tour_assets' => 'MISSING',
    'virtual_tours' => 'virtual_tours (SURVIVED)',
    'websocket_channels' => 'MISSING',
];

// Now generate the report
$missing = [];
$implemented = [];
$partial = [];
$unknown = [];

foreach ($dropped as $t) {
    if (!isset($mapping[$t])) {
        $unknown[] = $t;
    } elseif (stripos($mapping[$t], 'MISSING') === 0) {
        // Get reason
        $reason = trim(str_replace('MISSING', '', $mapping[$t]), " ()");
        $missing[$t] = ['reason' => $reason, 'old_rows' => $old[$t]['rows'] ?? 0, 'old_cols' => $old[$t]['col_count'] ?? 0];
    } elseif (stripos($mapping[$t], 'SURVIVED') !== false) {
        $implemented[$t] = $mapping[$t];
    } else {
        $partial[$t] = $mapping[$t];
    }
}

echo "=== FUNCTIONALITY MAPPING RESULTS ===\n";
echo "Total dropped: " . count($dropped) . "\n";
echo "Survived/migrated to existing table: " . count($implemented) . "\n";
echo "Partial mapping (similar concept in different table): " . count($partial) . "\n";
echo "MISSING (functionality not implemented): " . count($missing) . "\n";
echo "Unmapped: " . count($unknown) . "\n\n";

echo "=== MISSING FUNCTIONALITY (where to implement) ===\n";
ksort($missing);
foreach ($missing as $t => $info) {
    echo sprintf("  %-45s %3d cols  %4d rows  | %s\n", $t, $info['old_cols'], $info['old_rows'], $info['reason']);
}

echo "\n=== UNMAPPED TABLES ===\n";
sort($unknown);
foreach ($unknown as $t) {
    $info = $old[$t] ?? ['rows' => 0, 'col_count' => 0];
    echo sprintf("  %-45s %3d cols  %4d rows\n", $t, $info['col_count'], $info['rows']);
}?>