<?php
/**
 * Quick Database Verification
 * Test if all required tables exist after setup
 */

define('INCLUDED_FROM_MAIN', true);
require_once 'includes/db_connection.php';

echo "<h1>Database Tables Verification</h1>";

if (!$pdo) {
    echo "<div style='color: red; font-size: 18px;'>❌ Database connection failed!</div>";
    exit;
}

echo "<div style='color: green; font-size: 18px;'>✅ Database connection successful!</div>";

$required_tables = [
    'company_settings',
    'properties',
    'property_types',
    'users',
    'customers',
    'agents',
    'bookings'
];

$all_tables_exist = true;

foreach ($required_tables as $table) {
    try {
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM $table LIMIT 1");
        $result = $stmt->fetch();

        echo "<div style='color: green; font-size: 16px;'>✅ $table table exists</div>";

        // Show record count for some tables
        if (in_array($table, ['company_settings', 'properties', 'property_types'])) {
            $stmt = $pdo->query("SELECT COUNT(*) as count FROM $table");
            $count = $stmt->fetch()['count'];
            echo "<small style='color: blue;'>   ↳ $count records found</small><br>";
        }

    } catch (Exception $e) {
        echo "<div style='color: red; font-size: 16px;'>❌ $table table missing: " . $e->getMessage() . "</div>";
        $all_tables_exist = false;
    }
}

echo "<hr>";

if ($all_tables_exist) {
    echo "<div style='color: green; font-size: 20px; padding: 20px; background: #d4edda; border-radius: 5px;'>";
    echo "🎉 ALL REQUIRED TABLES EXIST!<br>";
    echo "✅ Your database is ready for the APS Dream Homes system!";
    echo "</div>";

    echo "<div style='margin-top: 20px;'>";
    echo "<a href='about_template.php' style='color: green; text-decoration: none; font-size: 18px;'>🧪 Test About Page</a> | ";
    echo "<a href='contact_template.php' style='color: green; text-decoration: none; font-size: 18px;'>📞 Test Contact Page</a> | ";
    echo "<a href='properties_template.php' style='color: green; text-decoration: none; font-size: 18px;'>🏠 Test Properties Page</a> | ";
    echo "<a href='index_template.php' style='color: green; text-decoration: none; font-size: 18px;'>🏡 Test Homepage</a>";
    echo "</div>";

} else {
    echo "<div style='color: red; font-size: 18px; padding: 20px; background: #f8d7da; border-radius: 5px;'>";
    echo "⚠️ Some tables are still missing. Please run the database setup again.";
    echo "</div>";

    echo "<div style='margin-top: 20px;'>";
    echo "<a href='database_setup.php' style='color: blue; text-decoration: none; font-size: 18px;'>🔧 Run Database Setup</a>";
    echo "</div>";
}

echo "<hr>";
echo "<small>Generated by APS Dream Homes Database Verification Tool</small>";
?>
