#!/usr/bin/env python3

file_path = 'C:/xampp/htdocs/apsdreamhome/routes/web.php'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

old = "Document E-Sign management\n$router->get('/admin/document-esign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@index');\n$router->post('/admin/document-esign/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@store');\n$router->get('/admin/document-esign/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@show');\n$router->post('/admin/document-esign/{id}/sign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@sign');\n$router->post('/admin/document-esign/{id}/cancel', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@cancel');\n$router->get('/api/v2/audit/log', 'Admin\\\\AuditLogController@api');\n$router->get('/api/v2/notifications/poll', 'Api\\\\NotificationStreamController@poll');\n$router->post('/api/v2/notifications/read', 'Api\\\\NotificationStreamController@markRead');\n$router->get('/api/v2/notifications/stream', 'Api\\\\NotificationStreamController@stream');"

new = "Document E-Sign management\n$router->get('/admin/document-esign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@index');\n$router->post('/admin/document-esign/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@store');\n$router->get('/admin/document-esign/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@show');\n$router->post('/admin/document-esign/{id}/sign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@sign');\n$router->post('/admin/document-esign/{id}/cancel', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@cancel');\n\n// Property Verification Badge management\n$router->get('/admin/property-verification', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@index');\n$router->get('/admin/property-verification/levels', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@levels');\n$router->post('/admin/property-verification/levels/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@storeLevel');\n$router->post('/admin/property-verification/levels/{id}/update', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@updateLevel');\n$router->post('/admin/property-verification/levels/{id}/delete', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@deleteLevel');\n$router->get('/admin/property-verification/requests', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@requests');\n$router->get('/admin/property-verification/requests/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@showRequest');\n$router->post('/admin/property-verification/requests/{id}/approve', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@approveRequest');\n$router->post('/admin/property-verification/requests/{id}/reject', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@rejectRequest');\n$router->post('/admin/property-verification/requests/{id}/assign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@assignRequest');\n$router->get('/admin/property-verification/badges', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@badges');\n$router->post('/admin/property-verification/badges/{id}/revoke', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@revokeBadge');\n$router->get('/admin/property-verification/stats', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@stats');\n\n$router->get('/api/v2/audit/log', 'Admin\\\\AuditLogController@api');\n$router->get('/api/v2/notifications/poll', 'Api\\\\NotificationStreamController@poll');\n$router->post('/api/v2/notifications/read', 'Api\\\\NotificationStreamController@markRead');\n$router->get('/api/v2/notifications/stream', 'Api\\\\NotificationStreamController@stream');"

with open('C:/xampp/htdocs/apsdreamhome/routes/web.php', 'r', encoding='utf-8') as f:
    content = f.read()

old = "Document E-Sign management\n$router->get('/admin/document-esign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@index');\n$router->post('/admin/document-esign/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@store');\n$router->get('/admin/document-esign/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@show');\n$router->post('/admin/document-esign/{id}/sign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@sign');\n$router->post('/admin/document-esign/{id}/cancel', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@cancel');\n$router->get('/api/v2/audit/log', 'Admin\\\\AuditLogController@api');\n$router->get('/api/v2/notifications/poll', 'Api\\\\NotificationStreamController@poll');\n$router->post('/api/v2/notifications/read', 'Api\\\\NotificationStreamController@markRead');\n$router->get('/api/v2/notifications/stream', 'Api\\\\NotificationStreamController@stream');"

new = "Document E-Sign management\n$router->get('/admin/document-esign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@index');\n$router->post('/admin/document-esign/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@store');\n$router->get('/admin/document-esign/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@show');\n$router->post('/admin/document-esign/{id}/sign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@sign');\n$router->post('/admin/document-esign/{id}/cancel', 'App\\\\Http\\\\Controllers\\\\Admin\\\\DocumentEsignController@cancel');\n\n// Property Verification Badge management\n$router->get('/admin/property-verification', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@index');\n$router->get('/admin/property-verification/levels', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@levels');\n$router->post('/admin/property-verification/levels/store', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@storeLevel');\n$router->post('/admin/property-verification/levels/{id}/update', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@updateLevel');\n$router->post('/admin/property-verification/levels/{id}/delete', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@deleteLevel');\n$router->get('/admin/property-verification/requests', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@requests');\n$router->get('/admin/property-verification/requests/{id}', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@showRequest');\n$router->post('/admin/property-verification/requests/{id}/approve', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@approveRequest');\n$router->post('/admin/property-verification/requests/{id}/reject', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@rejectRequest');\n$router->post('/admin/property-verification/requests/{id}/assign', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@assignRequest');\n$router->get('/admin/property-verification/badges', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@badges');\n$router->post('/admin/property-verification/badges/{id}/revoke', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@revokeBadge');\n$router->get('/admin/property-verification/stats', 'App\\\\Http\\\\Controllers\\\\Admin\\\\PropertyVerificationController@stats');\n\n$router->get('/api/v2/audit/log', 'Admin\\\\AuditLogController@api');\n$router->get('/api/v2/notifications/poll', 'Api\\\\NotificationStreamController@poll');\n$router->post('/api/v2/notifications/read', 'Api\\\\NotificationStreamController@markRead');\n$router->get('/api/v2/notifications/stream', 'Api\\\\NotificationStreamController@stream');"

with open('C:/xampp/htdocs/apsdreamhome/routes/web.php', 'r', encoding='utf-8') as f:
    content = f.read()

if old in content:
    content = content.replace(old, new)
    with open('C:/xampp/htdocs/apsdreamhome/routes/web.php', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Routes updated successfully!")
else:
    print("Pattern not found!")